### ISSUE TITLE
在ios里，好像有一些页面跳转不了啊

### ISSUE THREAD

**Issue by hopkinson** [SilurianYang/uni-simple-router#1]

**Comment by hopkinson** [comment]
应该是跳转得很慢

**Comment by SilurianYang** [comment]
@hopkinson  5s测试没有问题，你指的很慢是什么意思？用github上提供的测试包进行测试下 看看会不会有这样的问题

**Comment by wjg0615** [comment]
我也会出现ios真机上微信小程序无法跳转的问题

**Comment by SilurianYang** [comment]
@wjg0615 贴出代码 我看看

**Comment by wjg0615** [comment]
![image](https://user-images.githubusercontent.com/24453923/62343269-ba405200-b51c-11e9-935d-1e3a9089b4f8.png)
![image](https://user-images.githubusercontent.com/24453923/62343303-e1971f00-b51c-11e9-9fed-4109dd86dca8.png)

**Comment by wjg0615** [comment]
只是简单的调push而已，安卓的就没问题，但ios就点击跳不了

**Comment by SilurianYang** [comment]
@wjg0615 其他端是否有这样的表现，如果没有。那在ios试试使用uni的api跳转下。

**Comment by wjg0615** [comment]
试过了，改成这个uni.navigateTo就可以跳，然后还有就是路由push在百度小程序的安卓和ios就可以跳，唯独就是ios的微信小程序跳不了

**Comment by SilurianYang** [comment]
> 试过了，改成这个uni.navigateTo就可以跳，然后还有就是路由推在百度小程序的安卓和IOS就可以跳，唯独就是IOS的微信小程序跳不了

你加我QQ 1606726660  具体说下情况
