### ISSUE TITLE
微信小程序端，会导致报错common/vendor.js报错【追踪到了包里vueRouter/concat.js的bug】

### ISSUE THREAD

**Issue by devilwjp** [SilurianYang/uni-simple-router#107]
版本1.5.2
微信小程序端
只要import uni-simple-router，就会导致报错common/vendor.js报错

![QQ截图20200405233740](https://user-images.githubusercontent.com/38802722/78502986-77fb9e80-7796-11ea-92ce-5e3eb653960b.jpg)

应该是你包里的vueRouter/concat.js里的bug。
使用const定义el，下面又试图去修改el的值，导致报错了

**Comment by SilurianYang** [comment]
这并不是 `bug`  首先你可以在报错上看到  这是h5下的节点  说明 在编译的同时 没编译到指定端。 你需要尝试 [使用这个文章里面的解决方法](https://github.com/SilurianYang/uni-simple-router/issues/94)
