### ISSUE TITLE
路由守卫

### ISSUE THREAD

**Issue by 15939054361** [SilurianYang/uni-simple-router#108]
路由守卫在h5页面正常使用 ,在小程序端不起作用

**Comment by 15939054361** [comment]
## vue中打印`this.$router`
![image](https://user-images.githubusercontent.com/52627267/78557802-0bd77400-7844-11ea-99a2-47c1c95270bb.png)
## 小程序里面打印`this.$router`
![image](https://user-images.githubusercontent.com/52627267/78557863-2b6e9c80-7844-11ea-9710-dde33c2ce130.png)

**Comment by SilurianYang** [comment]
## 请先查看一遍文档可以么？ 文档里可没说是用 `$router` 或者是 `$route`

**Comment by yanpeng926** [comment]
> ## 请先查看一遍文档可以么？ 文档里可没说是用 `$router` 或者是 `$route`

所以前置路由钩子无效是为啥
