### ISSUE TITLE
引入uni-simple-router之后App.vue中的onLaunch等钩子触发不了了

### ISSUE THREAD

**Issue by zouyaoji** [SilurianYang/uni-simple-router#112]
**Describe the bug**
如题，通过vue-cli初始化的uni-app默认模板工程，引入uni-simple-router之后App.vue中的onLaunch等钩子触发不了了，但vue生命周期的mounted等钩子是可以触发的。测试平台是微信小程序。

**To Reproduce**
1. 下载附件。
2. 解压打开工程。
3. npm install
4. npm run dev:mp-weixin
5. 用微信开发者中心即可重现问题。

**Expected behavior**
希望onLaunch能触发。

**Screenshots**
![image](https://user-images.githubusercontent.com/24430116/79098665-0d99be00-7d95-11ea-9695-71ad73d8fdd0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. 微信开发者工具]
 - Version [e.g. 2.10.4]

**Additional context**
感谢提供优秀的轮子，我用这个插件主要想用类似vue-router的路由守卫功能，目前暂时测到这一个问题，烦请空了瞧瞧。重现工程：
[uni-simple-router-test.zip](https://github.com/SilurianYang/uni-simple-router/files/4468346/uni-simple-router-test.zip)

**Comment by SilurianYang** [comment]
![Uploading 22222.png…]()
![111111](https://user-images.githubusercontent.com/31280665/79100279-bc8bc900-7d98-11ea-9d93-e680101d5370.png)

**Comment by zouyaoji** [comment]
啊哈 把这一茬给漏了 谢了
