### ISSUE TITLE
$Router.back无法触发路由守卫

### ISSUE THREAD

**Issue by zouyaoji** [SilurianYang/uni-simple-router#113]
**Is your feature request related to a problem? Please describe.**
微信小程序平台，测试通过编程式导航退回路由时，无法触发路由守卫。

**Describe the solution you'd like**
希望能触发路由守卫，可以参考vue-router。

**Describe alternatives you've considered**
如果$Router.back能触发路由守卫，应该算更完善了吧。

**Additional context**
无

**Comment by SilurianYang** [comment]
# v1.5.4 已添加
