### ISSUE TITLE
遍历路由和动态修改路由？

### ISSUE THREAD

**Issue by j4587698** [SilurianYang/uni-simple-router#114]
路由有办法遍历吗？
我打出来发现this.$Router.CONFIG.routes中是所有的路由信息，遍历这个数组受支持吗？
或者有其他办法可以遍历路由吗？

另外有没有办法可以动态修改路由？
因为我发现没有注册的路由在路由守卫里path为空，如果可以动态修改就能搞一些骚操作了。

**Comment by SilurianYang** [comment]
遍历路由是什么意思？ 另外目前不支持动态添加路由

**Comment by j4587698** [comment]
@SilurianYang 就是在某个页面查询所有的可用路由，获取里面的一些路由信息。

**Comment by SilurianYang** [comment]
目前没有动态路由  `CONFIG.routes` 都是可用路由

**Comment by j4587698** [comment]
@SilurianYang 就是可用路由，就是CONFIG.routes中的信息其实是受支持的？我现在用了CONFIG.routes中的路由信息不会后面某个版本获取不到了吧

**Comment by SilurianYang** [comment]
不是公开api 后面可能会变

**Comment by j4587698** [comment]
@SilurianYang 那可以在后面的某个版本提供一个公开API吗？
这个需求估计挺有用的吧。现在我是想根据路由动态生成菜单。

**Comment by SilurianYang** [comment]
new  时候传递的路由自己导入一份不就ok了？  为什么要去插件里面取？

**Comment by j4587698** [comment]
动态路由的思路吧。。。没有动态路由的话的确可以直接去取。
动态路由用惯了没转过弯来
