### ISSUE TITLE
文件查找失败：'uni-hold-tabbar' 

### ISSUE THREAD

**Issue by lixing0323** [SilurianYang/uni-simple-router#117]
**Describe the bug**

**To Reproduce**
1. 文件查找失败：'uni-hold-tabbar' at utils/hhyang-uni-simple-router/appRouter/init.js:5
2. ERROR  Build failed with errors.\

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SilurianYang** [comment]
## 提issue前先试着搜索下 [这里和你的问题一样](https://github.com/SilurianYang/uni-simple-router/issues/89)
