### ISSUE TITLE
uniapp  首页加载不出来

### ISSUE THREAD

**Issue by RajanZhan** [SilurianYang/uni-simple-router#118]
//*************** pages.json*********
{
	"pages": [ 
		//pages数组中第一项表示应用启动页，
		//参考：https://uniapp.dcloud.io/collocation/pages
		{
			"path": "pages/index/index",
			"style": {
				"navigationBarTitleText": "首页",
				"navigationStyle": "custom", // 隐藏系统导航栏
				"navigationBarTextStyle": "white" // 状态栏字体为白色，只能为 white-白色，black-黑色 二选一
			}
		},
		{
			"path": "pages/workspace/workspace",
			"style": {}
		}, {
			"path": "pages/userCenter/userCenter",
			"style": {}
		}, {
			"path": "pages/login/register",
			"style": {}
		},
		{
			"path": "pages/login/login",
			"style": {}
		}, {
			"path": "pages/login/forget",
			"style": {}
		}
		
	],
	"easycom": {
		"^u-(.*)": "@/uview/components/u-$1/u-$1.vue"
	},
	"globalStyle": {
		"navigationBarTextStyle": "black",
		"navigationBarTitleText": "字节空间",
		"navigationBarBackgroundColor": "#F8F8F8",
		"backgroundColor": "#F8F8F8",
		"navigationStyle": "custom"
	}
}

//*************** main.js*********
 import router from './router'
import { RouterMount } from 'uni-simple-router'
const app = new Vue({
  store,
    ...App
})

//v1.3.5起 H5端 你应该去除原有的app.$mount();使用路由自带的渲染方式
// #ifdef H5
	RouterMount(app,'#app');
// #endif

// #ifndef H5
	app.$mount(); //为了兼容小程序及app端必须这样写才有效果
// #endif

***************router/index.js***************
import Vue from 'vue'
//这里仅示范npm安装方式的引入，其它方式引入请看最上面【安装】部分
import Router from 'uni-simple-router'

Vue.use(Router)

//初始化
const router = new Router({
	routes: [
		{
			//注意：path必须跟pages.json中的地址对应，最前面别忘了加'/'哦
			path: '/pages/index/index',
			aliasPath: '/', //对于h5端你必须在首页加上aliasPath并设置为/
			name: 'index',
			meta: {
				// title: '首页',
			},
		},
		{
			path: '/pages/workspace/workspace',
			name: 'workspace',
			meta: {
		
			},
		}, {
			path: '/pages/userCenter/userCenter',
			name: 'userCenter',
			meta: {
		
			},
		}, {
			path: '/pages/login/register',
			name: 'register',
			meta: {
		
			},
		}, {
			path: '/pages/login/login',
			name: 'login',
			meta: {
		
			},
		}, {
			path: '/pages/login/forget',
			name: 'forget',
			meta: {
		
			},
		}, {
			path: '/pages/transition_demo/transition_demo',
			name: 'transition_demo',
			meta: {
		
			},
		},
	] //路由表
});

//全局路由前置守卫
router.beforeEach((to, from, next) => {
	console.log("路由前置守卫",to);
	next()
})

// 全局路由后置守卫
router.afterEach((to, from) => {})

export default router;

**Comment by SilurianYang** [comment]
朋友你这是什么端上出现无法加载出来的问题 是cli项目还是ide初始化项目？

**Comment by RajanZhan** [comment]
@SilurianYang  感谢解答，已经解决了，问题是我跳转的时候使用的是$router 改成 $Router 就可以了
