### ISSUE TITLE
cli引入的时候报错

### ISSUE THREAD

**Issue by whoopsHzh** [SilurianYang/uni-simple-router#119]
h5中：
![image](https://user-images.githubusercontent.com/32846446/80390888-a117d680-88df-11ea-9e1f-068f3e9663de.png)
小程序中：
![image](https://user-images.githubusercontent.com/32846446/80390922-ac6b0200-88df-11ea-8914-f15e73de08b7.png)

**Comment by SilurianYang** [comment]
你升级下uni-cli 并正确配置  transpileDependencies:['uni-simple-router'] 即可生效
