### ISSUE TITLE
Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by pppshiwen** [SilurianYang/uni-simple-router#12]
![image](https://user-images.githubusercontent.com/40817872/63402387-c6c61500-c40d-11e9-9b97-dacb8d06f95d.png)
用vue cli 初始化项目试过，也用hx初始化项目试过，都出现这个错误

代码
![image](https://user-images.githubusercontent.com/40817872/63402504-4358f380-c40e-11e9-867f-a083854a363d.png)

**Comment by SilurianYang** [comment]
使用hx创建的项目也会这样么？是创建不是初始化

**Comment by SilurianYang** [comment]
@pppshiwen  如果实现不行 请把你的测试demo发我邮箱1606726660@qq.com

**Comment by pppshiwen** [comment]
@SilurianYang 已经发送了，麻烦您了

**Comment by SilurianYang** [comment]
> @SilurianYang 已经发送了，麻烦您了

已确认问题，初始化时 当前的路由未在实例化Router时注册
![QQ截图20190821144601](https://user-images.githubusercontent.com/31280665/63408798-6a212500-c422-11e9-9e7b-71fdea97f1fd.png)

**Comment by pppshiwen** [comment]
@SilurianYang 那我这边需要怎么解决

**Comment by SilurianYang** [comment]
> @SilurianYang 那我这边需要怎么解决

我截图了啊

**Comment by pppshiwen** [comment]
@SilurianYang ok,根据你说的已成功解决，谢谢~
