### ISSUE TITLE
路由缓存的问题

### ISSUE THREAD

**Issue by RajanZhan** [SilurianYang/uni-simple-router#120]
每次调换页面都是重新渲染，而且存在渲染期间短暂的空白，没有路由缓存的功能，把特定的页面缓存起来就像H5的vue-router 的路由缓存一样

**Comment by SilurianYang** [comment]
keepAlive？ 你想的是在app把需要缓存的页面缓存下来  然后新开页面的时候直接把那个页面调用出来？ 但是uni-app每个页面都是一个webview而想把缓存下来会吃很多的内存。就想mui以前的预加载一样。低端手机缓存上几个就开始特么卡顿了。你说的白屏多半是出现在tabbar切换的时候吧！官方不是已经在做这方便的改进了么。当然你这个建议也可以尝试下！

**Comment by RajanZhan** [comment]
@SilurianYang 感谢解答， 现在tab切换页面时确实明显，页面重新渲染的时间太长了。

**Comment by SilurianYang** [comment]
@RajanZhan 你是用的官方的tab还是自定义的  白屏时间长你需要优化  一般官方提供的tab在优化好的情况下基本不会出现白屏   除非是很低端的手机

**Comment by RajanZhan** [comment]
@SilurianYang  感谢您的解答，之前没有用官方的tabbar， 现在改成了官方的tabbar  ，切换tab时页面不会重新渲染了，流畅度正常了，再次感谢您的关注
