### ISSUE TITLE
开了v3后，ios上白屏，报这个错Unhandled promise rejection TypeError: Object.values is not a function. (In 'Object.values(Le)', 'Object.values' is undefined) __ERROR 

### ISSUE THREAD

**Issue by 13250815190YMJ** [SilurianYang/uni-simple-router#121]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SilurianYang** [comment]
你的手机太老了吧，配置 vue.config.js  然后babel去帮你处理下 transpileDependencies:['uni-simple-router','uni-hold-tabbar']
