### ISSUE TITLE
uni-app中使用uni-simple-router在android端app首次加载白屏bug的demo提交

### ISSUE THREAD

**Issue by yingbing-developer** [SilurianYang/uni-simple-router#122]
微信端和h5端无问题，android端app首次加载白屏,无报错
[uni-simple-router-demo-bug.zip](https://github.com/SilurianYang/uni-simple-router/files/4608001/uni-simple-router-demo-bug.zip)

**Comment by SilurianYang** [comment]
### 一些错误的写法导致生命周期没有按预期执行。
![QQ截图20200511152208](https://user-images.githubusercontent.com/31280665/81534862-57c58d80-939b-11ea-8dc1-25b0e369250a.png)
改为
![QQ截图20200511152332](https://user-images.githubusercontent.com/31280665/81534897-67dd6d00-939b-11ea-8a1b-72401732858c.png)

或者 在 `getAuth` 返回一个完整的 `Promise` 别一会返回 `Boolean`  一会返回 `Promise`

### 在提醒下：
像token判断什么的你应该放在全局守卫下， 而不是放在onload生命周期下。这样就失去拦截的意义啦。把路由拦截做到最大收益！
