### ISSUE TITLE
一直提示这个错误

### ISSUE THREAD

**Issue by AK47-dadada** [SilurianYang/uni-simple-router#123]
TypeError: Cannot set property 'type' of null
![image](https://user-images.githubusercontent.com/30396595/81685837-cdf4ed80-948a-11ea-8355-982c2f52348e.png)
请问这是什么原因导致的

**Comment by SilurianYang** [comment]
你是怎么调用的？

**Comment by 690591397** [comment]
我也是报这个错，完全按照官网这个home index 来的有点儿懵，要配置什么type么

**Comment by 690591397** [comment]
> 我也是报这个错，完全按照官网这个home index 来的有点儿懵，要配置什么type么

解了，`/**
 * 把一个未知的路由跳转规则进行格式化为 hash、history 可用的,主要表现在 history模式下直接传入path会报错__id__错误的问题
 * @param {*} path 需要判断修改的路径规则
 */
export const strPathToObjPath = function (path) {
    if (path == null) { // 我们也不用管啦,这个情况是路由守卫中传递的
        return path;
    }
    if (isObject(path)) { // 是对象我们不用管
        return path;
    }
    return { // 这种情况就是只有path时,直接返回path对象了
        path,
    };
};`


多半是path 带 斜杠 / 和不带斜杠出的问题，小程序的pages json不要带，router这边要带。。
