### ISSUE TITLE
H5刷新后会无限加query

### ISSUE THREAD

**Issue by imyellow** [SilurianYang/uni-simple-router#124]
使用动态路由时，刷新页面会无限叠加 query

例如路由设置为：

```
[
  {
    path: '/:pageid',
    name: 'home',
    component: () => import('@/pages/index/index.vue')
  }
]
```

页面刷新几次后，地址会变为：
`http://sample.com/001/?query=%257B%2522query%2522%253A%2522%257B%255C%2522query%255C%2522%253A%255C%2522%25257B%252522query%252522%25253A%252522%25257B%25255C%252522query%25255C%252522%25253A%25255C%252522%2525257B%25252522query%25252522%2525253A%25252522%2525257B%2525257D%25252522%2525257D%25255C%252522%25257D%252522%25257D%255C%2522%257D%2522%257D`

**Comment by SilurianYang** [comment]
你好可以提供一个可复现的demo么？

我尝试按你提供的配置进行测，没有发现相关问题

#### 我的配置：
```
const router = new Router({
	h5: {
		vueRouterDev: true
	},
	routes: [{
		path: '/:pageid',
		name: 'home',
		component: () => import('@/pages/index/index.vue'),
	},{
			path: '/page1/:id',
			name:'page1',
			component: () => import('@/pages/page1/page1.vue'),
	}]
});
```
#### 操作步骤：
1. 打开 `http://192.168.0.183:8080/#/123` 进入到首页
2. 重复刷新 地址栏不变
3. 尝试在首页下提供一个按钮 到 `page1` 页面
4. 在 `page1` 页面 重复刷新 未发现以上问题

#### 我的测试工程

[demo.zip](https://github.com/SilurianYang/uni-simple-router/files/4647897/demo.zip)

**Comment by imyellow** [comment]
@SilurianYang 感谢回复，模式从 hash 变为 history 就可以复现了
![image](https://user-images.githubusercontent.com/3270774/82282472-801a4100-99c6-11ea-8820-1af795c5e8fb.png)

**Comment by SilurianYang** [comment]
已确认是 `bug` !   先使用 `hash` 过度下吧  很快会修复

**Comment by SilurianYang** [comment]
## 1.5.5已修复

**Comment by andyWHJ** [comment]
复现例子  http://localhost:8080/website/pages/index/index?xxx=123 这样的刷新 就跳转到 http://localhost:8080/website/pages/index/index?query=%257B%257D
[my-project3.zip](https://github.com/SilurianYang/uni-simple-router/files/4992219/my-project3.zip)
