### ISSUE TITLE
默认keep-alive？

### ISSUE THREAD

**Issue by weixisheng** [SilurianYang/uni-simple-router#127]
**Describe the bug**
其实就是有个疑问，在H5平台时，页面会缓存，导致热更新失效

**Expected behavior**
热更新正常

**Screenshots**
![image](https://user-images.githubusercontent.com/16042305/82801843-86ba2400-9eb0-11ea-8ed2-28043ada351b.png)

**Comment by SilurianYang** [comment]
这个是 uni-app 内置的 和 插件无关系  而且 热更新 和 `keep-alive` 无关系
