### ISSUE TITLE
cli创建的项目使用uni-simple-router在IOS9下白屏

### ISSUE THREAD

**Issue by zyq664975** [SilurianYang/uni-simple-router#128]
**Describe the bug**
ios9下使用uni-simple-router没有按预期打开首页

**To Reproduce**
1. 下载示例工程
2.npm install
3.npm run serve

**Expected behavior**
使用uni-simple-router在ios下没有按预期打开首页，在高版本ios和Android下能正常打开

**Screenshots**
![微信图片_20200526150303](https://user-images.githubusercontent.com/63764833/82870812-233cfe80-9f63-11ea-9089-5f1478ee9239.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone6S
 - OS: iOS9.3.2
 - Browser UCBrowser,    QQBrowser,     safari
 - Version V12.5.7.1203,   9.6.2.4196

**Additional context**
示例工程
[uni.zip](https://github.com/SilurianYang/uni-simple-router/files/4680479/uni.zip)

**Comment by SilurianYang** [comment]
`ide` 初始化项目 默认是包涵 `node_modules`  而 `cli` 则没有 你需要在 `vue.config.js` 下 这样配置  `transpileDependencies:['uni-simple-router','uni-hold-tabbar']`  即可

**Comment by zyq664975** [comment]
没有用到tabbar, `vue.config.js`下已经配置`transpileDependencies:['uni-simple-router']`。
这是在Android下打开的样子：
![微信图片_20200527093835](https://user-images.githubusercontent.com/63764833/82966833-5bdde600-9ffe-11ea-8897-6325e7816ace.jpg)

**Comment by zyq664975** [comment]
已解决，谢谢

**Comment by qicainiao** [comment]
怎么解决的
