### ISSUE TITLE
使用uni-simple-router导致第一次进入小程序无法从页面的onload获取路由参数

### ISSUE THREAD

**Issue by a1095114983** [SilurianYang/uni-simple-router#129]
重现方法：小程序开发工具内新增编译模式（选择一个非入口页面），带上参数，会发现onload获取不到参数

**Comment by legiongeneral** [comment]
我也遇到这种情况了，请问如何解决，紧急

**Comment by scdtxdy** [comment]
我也是这个问题,没办法只能先卸载掉路由.

**Comment by SilurianYang** [comment]
`onload` 无法获取属于正常   你应该在标准的 `uniapp` 生命周期下 使用 `this.$Route.query` 来获取。当然页面排除非对应模式下传参。   

#### 例如：
**encodeURI:false** :  `?id=123&name=hhyang`
**encodeURI:true** :  `query=encodeURIComponent(JSON.stringify({name:'hhyang',id:123}))`

**Comment by scdtxdy** [comment]
在uni onload中 使用this.$Route.query 获取到的是{}url是id=111&name=222这种格式

**Comment by SilurianYang** [comment]
@scdtxdy 老铁加我qq 我们聊下 1606726660

**Comment by SilurianYang** [comment]
## 请尝试把 `encodeURI` 设置为 `false`  像这样

```js
const router =new Router({
	encodeURI:false,
	routes:[
		...ROUTES
	],
})
```

**Comment by a1095114983** [comment]
即使是使用this.$Route.query,这个值也是undefined。直接进入非首页的情况下，在APP的onlaunch里面是可以拿到参数的，但是在页面的onLoad无法获取

**Comment by SilurianYang** [comment]
#### 无法复现 请提供demo和详细操作步骤

**Comment by a1095114983** [comment]
重现方法：小程序开发工具内新增编译模式（选择一个非入口页面），带上参数，会发现onload获取不到参数，按照这个不能重现吗？

**Comment by a1095114983** [comment]
[](url)

**Comment by SilurianYang** [comment]
#### 这个步骤我尝试了很多次 依旧无法复现 且达到预期效果 使用 `this.$Route.query` 请提供你的路由版本

**Comment by a1095114983** [comment]
1.5.4

**Comment by SilurianYang** [comment]
@a1095114983  无法复现 可否加我联系方式 远程看看？

**Comment by a1095114983** [comment]
好，今天稍晚些时候我从QQ群加你

**Comment by zsmile** [comment]
话说这个问题有进度了吗？
### 版本 1.5.4 
#### pages.json
``` 
"condition": {
	"current": 0,
	"list": [{
		"path" : "pages/test/test",
		"name": "test",
		"query":"uuid=1000"
	}]
}
```

#### 前置守卫
```
router.beforeEach((to, from, next) => {
	console.log(to);
	next();
});

控制台打印为：{"path":"/pages/test/test","name":"test","params":{},"query":{"uuid":"1000"}}
```

#### test页面 onLoad获取
```
onLoad() {
	console.log('route: ',this.$Route);
}

控制台打印为：{"path":"/pages/test/test","name":"test","params":{},"query":{}}
```

**Comment by SilurianYang** [comment]
## 试试这个demo
[ideCreateBase.zip](https://github.com/SilurianYang/uni-simple-router/files/4935674/ideCreateBase.zip)

**Comment by zsmile** [comment]
> ## 试试这个demo
> [ideCreateBase.zip](https://github.com/SilurianYang/uni-simple-router/files/4935674/ideCreateBase.zip)

非常感谢，已解决。是由于encodeURI未对应的问题
