### ISSUE TITLE
大佬啊，1.1.3有BUG啊，路径传参有错误

### ISSUE THREAD

**Issue by kenhy** [SilurianYang/uni-simple-router#13]
如：this.$mRouter.push({path:'/pages/column/main',query: {itemid:id}});
跳转页面后，路径是会变成query={itemid:id}

**Comment by SilurianYang** [comment]
> 如：this.$mRouter.push({path:'/pages/column/main',query: {itemid:id}});
> 跳转页面后，路径是会变成query={itemid:id}

是这样的 修复了之前说的参数传递不一致的问题，之前是深度对象扁平成一个大对象。现在是你传什么样通过this.$Route获取就长什么样

**Comment by kenhy** [comment]
> > 如：this.$mRouter.push({path:'/pages/column/main',query: {itemid:id}});
> > 跳转页面后，路径是会变成query={itemid:id}
> 
> 是这样的 修复了之前说的参数传递不一致的问题，之前是深度对象扁平成一个大对象。现在是你传什么样通过this.$Route获取就长什么样 [详细请看这个](https://github.com/SilurianYang/uni-simple-router/issues/4)

不大理解，意思是要通过this.$Route获取参数，自己拼接url吗？如果我想跳转页面，url是http://xxx.com/submit?id=123，需要怎么做？

**Comment by SilurianYang** [comment]
比如传递了一个名为name的参数
```
this.$Router.push({
   	path: '/pages/tabbar/tabbar-4/tabbar-4',
	query: {
		 name: 'hhyang'
	   }
});
```
获取参数

```
this.$Route.query.name
```

**Comment by SilurianYang** [comment]
@kenhy 

比如传递了一个名为name的参数
```
this.$Router.push({
   	path: '/pages/tabbar/tabbar-4/tabbar-4',
	query: {
		 name: 'hhyang'
	   }
});
```
获取参数

```
this.$Route.query.name
```
