### ISSUE TITLE
微信浏览器打开路由失败

### ISSUE THREAD

**Issue by 277584579** [SilurianYang/uni-simple-router#130]
部分老旧机型/pc端微信点开h5链接会白屏  我检查过代码逻辑 去掉路由插件用uniapp自带的路由就行 也在网上求助别人给的意见  应该是插件里的 es6 代码不兼容

**Comment by 277584579** [comment]
![image](https://user-images.githubusercontent.com/22782505/83265720-7a0d3700-a1f4-11ea-963a-346a6aa8cc65.png)
这个是图片

**Comment by SilurianYang** [comment]
和 https://github.com/SilurianYang/uni-simple-router/issues/121 这个问题相同 **重复项** 脚手架项目记得配置 `vue.config.js`
