### ISSUE TITLE
地址栏拼接参数后会重定向到根目录

### ISSUE THREAD

**Issue by lm356536** [SilurianYang/uni-simple-router#131]
**问题描述**
 后端返回一个地址拼接相应参数地址，然后根据当前地址跳转时，参数丢失，页面会丢失后端拼接到参数。如在地址栏中输入：http://192.168.10.11:8081/pages/page/index?p=100, 完成后h5会自动重定向到http://192.168.10.11:8081，导致当前页面的参数获取失败。（用vue原生的路由没发现这个问题）

**预期结果**
当前页面
http://192.168.10.11:8081/pages/page/index?p=100

**实际结果**
http://192.168.10.11:8081

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [ios]
 - HBuilderX版本 [2.7.8.20200525-alpha]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [ iPhone11 Plus]
 - uni-simple-router版本 [v1.8.4]

**补充信息**
/pages/page/index 为项目根目录
```javascript
const home = [
	{
		//注意：path必须跟pages.json中的地址对应，最前面别忘了加'/'哦
		path: '/pages/index/index',
		aliasPath:'/',  //对于h5端你必须在首页加上aliasPath并设置为/
		name: 'index', 
		//可以自定义路由元信息
		myDiy:{
            isTab:true
        },
		meta: {
				title: '首页',
		},
  }
]
export default home
```

**Comment by SilurianYang** [comment]
#### 尝试把 `encodeURI` 设置为 `false`  像这样

```js
const router =new Router({
	encodeURI:false,
	routes:[
		...ROUTES
	],
})
```

**Comment by lm356536** [comment]
> #### 尝试把 `encodeURI` 设置为 `false` 像这样
> ```js
> const router =new Router({
> 	encodeURI:false,
> 	routes:[
> 		...ROUTES
> 	],
> })
> ```

可以了， 🙏🙏🙏🙏🙏🙏

**Comment by xiejibiao** [comment]
我也遇到这个问题了，就是无论页面跳转了多少次，重新后又会回去首页，请问您是怎么解决的？
