### ISSUE TITLE
首页路由后面的?p1=v1&p2=v2参数无法在onLoad里获取到

### ISSUE THREAD

**Issue by jsperorg** [SilurianYang/uni-simple-router#132]
**问题描述**

程序/pages/index/index路由是数组中的第一个，默认主页。  
有一个业务需求是，从第三方应用跳转而来，url后面会带上参数来标记用户是谁，界面会根据用户id显示用户信息，以及提供该用户的其他业务功能。  
http://localhost:8080/#/pages/index/index?uid=111  
但是在index.vue里的onLoad里获取不到uid这个参数，使用Vue的生命周期也获取不到。访问上面url会发生跳转，跳转到本路由，且后面的参数会被去掉。
使用http://localhost:8080/#/?uid=111这种方式也获取不到参数，不知道为何。

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/131  和这个相似
