### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'lifeCycle' of undefined

### ISSUE THREAD

**Issue by jackluo2012** [SilurianYang/uni-simple-router#136]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
在引用 的时候，报了这相错
**复现步骤**
[复现问题的步骤]
1. 启动 的时候就直接报了这个错
![image](https://user-images.githubusercontent.com/2638586/84341807-9dfa5080-abd6-11ea-8e98-bf7c16a5f006.png)

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/2638586/84341848-b7030180-abd6-11ea-9623-041e3a6efb40.png)

**系统信息:**
 - 发行平台: [微信小程序]
微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
![image](https://user-images.githubusercontent.com/2638586/84341914-d863ed80-abd6-11ea-81a4-7517cd574b3e.png)

 - uni-simple-router版本 [如 v1.5.4]
1.5.5

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
看报错大概是没有实例化 这里有懒人实例化 **需要重启**

[点我查看](http://hhyang.cn/src/router/tutorial/rgRoutes.html)
