### ISSUE TITLE
在H5平台获取refs为undefined

### ISSUE THREAD

**Issue by Tron1234** [SilurianYang/uni-simple-router#137]
比如有三个页面first.vue,second.vue,third.vue,second页面用了unipopup，所以这个组件会保存在refs里，当从first跳转到second后，再从second跳转到third，再从third返回second，再从second返回first用前置守卫读当前页面参数也就是second页面的内容，refs里的参数为undefined

**Comment by SilurianYang** [comment]
请按照模板提问
