### ISSUE TITLE
#64 这个问题麻烦再帮忙确认下，我这边最新的 1.5.5 的，依然有这个问题，cli创建的必须cli的方式能复现，代码用的github上的ideCreateBase这个demo。

### ISSUE THREAD

**Issue by qicainiao** [SilurianYang/uni-simple-router#139]
#64 这个问题麻烦再帮忙确认下，我这边最新的 1.5.5 的，依然有这个问题，cli创建的必须cli的方式能复现，代码用的github上的ideCreateBase这个demo。
 h5 chroma运行

**Comment by qicainiao** [comment]
//全局路由前置守卫
router.beforeEach((to, from, next) => {
	console.log('beforeEach----守卫')
	console.log(to)
	//next()
})

注释掉 next() 首页依然会打开

**Comment by SilurianYang** [comment]
无效的issue   请按照模板提问
