### ISSUE TITLE
1.2.2版本h5端不兼容安卓

### ISSUE THREAD

**Issue by godbobo** [SilurianYang/uni-simple-router#14]
安卓端微信直接跳转非主页链接，页面一直处于加载中（显示进度条）。
而IOS端和PC端正常显示，安卓模拟器同样正常显示。
感觉应该是新版本加了h5端的链接拦截导致的，在切换回旧版本后则没有此问题。

顺便提一句参数的变化有点大呀，原来都是直接用普通的方式添加URL参数的，现在组装一个地址还要加`query=`.(直接在浏览器输入的那种，命名路由传参的方式我知道的。。。)

**Comment by SilurianYang** [comment]
@godbobo 

经过测试 
hx 版本：2.2.2.20190816
微信版本：7.0.6
安卓：小米5x  安卓8.1.0

未复现你说的问题，请检查代码是否正确的调用 `next()` 。 query的形式传参是保证能传递深度对象，后续会继续考虑优化。占时是url丑了点  但是功能能保证正常使用
