### ISSUE TITLE
H5端无法获取到refs中的值

### ISSUE THREAD

**Issue by Tron1234** [SilurianYang/uni-simple-router#140]
**问题描述**
H5端页面跳转后无法通过getCurrentPages[getCurrentPages.length-1]获取不到refs中的值

**复现步骤**
[复现问题的步骤]
1.存在index,index1,index2三个页面
2.从index进入index1，打印当前页面信息，refs里面有那个tip：VueComponent,当从index1进入index2,在从index2回到index1，index1回到index时tip：undefined

**预期结果**
refs内的值不管页面怎么跳转都会存在保持原有的值

**实际结果**
![image](https://user-images.githubusercontent.com/47961959/84573812-5f7eb480-add5-11ea-8673-0319c57aa11e.png)

**系统信息:**
 - 发行平台: H5和app
 - 操作系统  iOS 13.5.1、Android 9.0
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]      2.7.9.20200527
 - 项目创建方法  HBuilderX
 - 设备信息  iphone8 zuk dege
 - uni-simple-router版本     v1.5.4

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
H5 没有任何问题

你打印的引用数据类型  跳转页面后自然会销毁   跳转之前你可以通过打印是否为undefined 来判断
[demo.zip](https://github.com/SilurianYang/uni-simple-router/files/4775810/demo.zip)
