### ISSUE TITLE
应用uni-smiple-router后除小程序外，在apk和h5浏览器中显示白屏，只有底部tabbar

### ISSUE THREAD

**Issue by wjs1995** [SilurianYang/uni-simple-router#141]
**问题描述**
[问题描述：在浏览器和app白屏，只显示底部tabbar，刷新网页的瞬间会出现页面的title然后消失

**复现步骤**
[复现问题的步骤]
1. 启动 '...' uniapp 安装 u-s-router, 安装 u-s-r- read 
2. 点击  '启动
3. 查看 出现tabbar 首页一闪 

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
## 99% 配置问题 检测你的配置和挂载点

```js
//v1.3.5起 H5端 你应该去除原有的app.$mount();使用路由自带的渲染方式
// #ifdef H5
	RouterMount(app,'#app');
// #endif

// #ifndef H5
	app.$mount(); //为了兼容小程序及app端必须这样写才有效果
// #endif
```

**Comment by wjs1995** [comment]
小程序端是可以的，打包app 和h5不行, 麻烦问一下
![image](https://user-images.githubusercontent.com/53244202/85245217-85612480-b479-11ea-9848-bfc9601db76d.png) 这个#app 是哪里的

**Comment by SilurianYang** [comment]
这个是uni-app在h5中的节点 如果你有自定义模板就换成自己的挂载点id

**Comment by wjs1995** [comment]
![image](https://user-images.githubusercontent.com/53244202/85245733-1edd0600-b47b-11ea-8d70-09f44d3a9e13.png)

**Comment by wjs1995** [comment]
<template>
	<view id="app"></view>
</template>  App.vue我是这样写的

**Comment by wjs1995** [comment]
<template>
	<view id="app"></view>
</template>

**Comment by wjs1995** [comment]
##<template>
##	<view id="app"></view>
##</template>

**Comment by wjs1995** [comment]
`<template>
	<view id="app"></view>
</template>`
