### ISSUE TITLE
H5 dev模式下，编程式导航，replaceAll()的表现与replace()相同

### ISSUE THREAD

**Issue by 1414044032** [SilurianYang/uni-simple-router#143]
**问题描述**

- 标准uni-app，h5模式

- 从首页（index）开始跳转==》跳转使用this.$Router.push(...)方式跳转。

- 到达最后结果页（result）时，使用this.$Router.replaceAll(...)方式跳回首页（index）。

- 到达首页后，按照我的理解此时首页应该又成为了history中第一条了，这时候如果我在手机移动端浏览器中点击浏览器的返回按钮，浏览器应该提示（‘再按一次退出’），因为这个时候index是第一页了。

- 当我点击浏览器返回按钮后，history把我定位到了 **结果页（result）的前一页**。这种表现形式并不是replaceAll()的表现形式。而是replace()

**复现步骤**

1. [我已将代码传git仓库。](https://github.com/1414044032/dy-shop-h5)https://github.com/1414044032/dy-shop-h5
2. 启动==》dev h5模式==》首页==》 点击 产品列表（标题 更多）==》点击任意产品==》点击购物车==》点击提交==》点击结算==》结果页（result）点击 “出去逛逛” ==》之后到达首页，此时点击浏览器返回按钮。会发现页面会跳转回结算页面（这个表现形式完全就是replace()，并不是replaceAll()）
3.

[或者可以直接贴源代码]

**预期结果**
预期结果：结果页返回首页后，点击浏览器返回键 应该是提示退出浏览器，而不是history还存在其他记录

**实际结果**
实际结果：结果页返回首页后，点击浏览器返回键 返回到了history中倒数第二条记录中

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Android
 - HBuilderX版本  命令行启动模式，直接 npm install 后  npm run serve（dev h5模式）
 - 项目创建方法 ： 使用Vue-cli创建
 - 设备信息 小米自带浏览器 
 - uni-simple-router版本 ：npm install 即可 最新的

**补充信息**
[可选]
可能您是不是这块replaceAll与replace()写一样了？具体我还没看源码。

**Comment by SilurianYang** [comment]
## 很抱歉 在浏览器端无法写入 `history`。 所以 h5 端  `replaceAll`、`pushTab` 都是 `replace` 一样的效果

**Comment by 1414044032** [comment]
好滴，谢谢您的解惑
