### ISSUE TITLE
uniapp如果用history模式获取不到url参数

### ISSUE THREAD

**Issue by bbzhengcheng** [SilurianYang/uni-simple-router#144]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
如果hisory模式，例子，地址会变这样http://localhost:8080/fruit_h5/pages/template/mall/loadding/loadding?query=%257B%257D
这样this.$Route.query 返回的是空{}，请问怎样解决，劳烦能及时回复一下我吗~
**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
  onLoad: function(options) {
	  console.log("this.$Route.query:",this.$Route.query,options);

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
http://hhyang.cn/src/router/start/cross/params.html

**Comment by bbzhengcheng** [comment]
> http://hhyang.cn/src/router/start/cross/params.html

其实就是这个问题咯，我有个需求这个url是腾讯那边自己帮我组装的，也就是腾讯那边自己帮我url加上?code=1233&state=222这样返回这个url我。。但是这个路由自己又搞会query={}这样了。。而且还没办法拿到query的值。。能给个解决方案吗

**Comment by SilurianYang** [comment]
上面不是写了吗？
```js
encodeURI:false
``

**Comment by bbzhengcheng** [comment]
> 上面不是写了吗？
> 
> ```js
> encodeURI:false
> ```我试下看看

**Comment by bbzhengcheng** [comment]
> 上面不是写了吗？
> 
> ```js
> encodeURI:false
> ```

感谢大佬的，可以了！送上鲜花！

**Comment by SilurianYang** [comment]
## [v2.0.0-alpha.1](https://github.com/SilurianYang/uni-simple-router/releases/tag/v2.0.0-alpha.1) 已调整

**Comment by Ifover** [comment]
> http://hhyang.cn/src/router/start/cross/params.html

😘😘😘

**Comment by gzxxy110506** [comment]
```
const router = new Router({
    h5: {
        mode: 'history'
    },
	encodeURI: false, // 序列化参数格式配置
	routes: [...modules] //路由表
});
```

版本："uni-simple-router": "^1.5.5"

路由配置如上，H5想要开启使用history模式，这样设置，启动到谷歌浏览器运行，依然还是hash模式，请问是我哪里没配对吗

求指导

**Comment by SilurianYang** [comment]
@gzxxy110506  路由插件没有提供这样的构建选项，请注意看文档。 这个配置需要你在 `manifest.json` 下  配置这个即可
```js
    "h5" : {
        "router" : {
            "mode" : "history"
        }
    }
```

**Comment by estarsyang** [comment]
@SilurianYang 配置了 manifest.json 后，依旧是hash模式。可以帮忙看下不

**Comment by estarsyang** [comment]
`"h5": {
"router": {
"mode": "history",
"base": "./"
}
},`

**Comment by estarsyang** [comment]
`
"h5": {
"router": {
"mode": "history",
"base": "./"
}
},
`

**Comment by estarsyang** [comment]
```js
"h5": {
"router": {
"mode": "history",
"base": "./"
}
},
```

**Comment by SilurianYang** [comment]
重新开一个issue 上传demo 我排除下

**Comment by gzxxy110506** [comment]
> @gzxxy110506 路由插件没有提供这样的构建选项，请注意看文档。 这个配置需要你在 `manifest.json` 下 配置这个即可
> 
> ```json
>     "h5" : {
>         "router" : {
>             "mode" : "history"
>         }
>     }
> ```

非常感谢，可以了

**Comment by estarsyang** [comment]
> 重新开一个issue 上传demo 我排除下

**Comment by estarsyang** [comment]
> 重新开一个issue 上传demo 我排除下

下午试了一下，是因为 base 的值导致的。```router:{base: './'}``` base这里会自动拼接到url中。比如设置了 ```router:{base:'test'}```，路由跳转时就会自动加上。之前以为这里只是打包出来的路径，没想到本地开发也会。
