### ISSUE TITLE
app端启动后，点击跳转报错

### ISSUE THREAD

**Issue by hujin0618** [SilurianYang/uni-simple-router#145]
错误描述：TypeError: undefined is not an object (evaluating 'this.$router.push')

引入方式：
![image](https://user-images.githubusercontent.com/13267079/87310366-750c0900-c550-11ea-889b-ac3e75784ae3.png)

**Comment by SilurianYang** [comment]
## 文档可没说是 `$router` 请不要把 h5端的带到通端上来  仔细看文档 是 `$Router`

**Comment by hujin0618** [comment]
> ## 文档可没说是 `$router` 请不要把 h5端的带到通端上来 仔细看文档 是 `$Router`

好的~第一次用，文档过的不仔细。不好意思
