### ISSUE TITLE
1.2.2 url会自动添加:  query=%7B%7D， 小程序会报错

### ISSUE THREAD

**Issue by freedom-zt** [SilurianYang/uni-simple-router#15]
1.2.2 url会自动添加:  query=%7B%7D， 小程序会报错

**Comment by SilurianYang** [comment]
> 1.2.2 url会自动添加: query=%7B%7D， 小程序会报错

你指的是微信小程序还是什么? 这种传参的方式是可取的，只不过新版本默认加上 `checkSiteMap` 并设置为开启状态。如果不想看见这么烦人的警告可以在 `manifest.json` 中 微信小程序选项下配置 `"checkSiteMap":false` 。 如果你那边确实发现有bug  可以扔我一个demo  感谢配合。

![1](https://user-images.githubusercontent.com/31280665/63775454-eda2b080-c911-11e9-9b73-34dc1c7c8d81.png)
![2](https://user-images.githubusercontent.com/31280665/63775455-eda2b080-c911-11e9-869a-b5c34c2980ad.png)
![3](https://user-images.githubusercontent.com/31280665/63775456-eda2b080-c911-11e9-9e5c-89fac35f5476.png)

**Comment by freedom-zt** [comment]
h5也会再url中加 query=%7B%7D

我的使用方式主要是这两种：
![image](https://user-images.githubusercontent.com/18046344/63822812-3004d580-c984-11e9-9444-2c8abd77dd53.png)
![image](https://user-images.githubusercontent.com/18046344/63822849-54f94880-c984-11e9-8c01-32beb2e560ef.png)

**Comment by SilurianYang** [comment]
@freedom-zt  是会自动加上这个query={}。虽然不影响功能，有点丑陋！我应该在没传递参数的时候去掉 

### 感谢！感谢！

**Comment by freedom-zt** [comment]
微信小程序每次切换路由时会报错
![image](https://user-images.githubusercontent.com/18046344/63833190-01e3bd80-c9a5-11e9-8c79-26f4f4b27545.png)

**Comment by SilurianYang** [comment]
@freedom-zt  你发个测试demo到我的邮箱吧1606726660@qq.com  经过多次测试未复现你说的那个问题

**Comment by freedom-zt** [comment]
我退回到1.1.2版本了

**Comment by SilurianYang** [comment]
> 我退回到1.1.2版本了

哥 你发个测试demo到我邮箱好吧。不然这样问题都解决不了

**Comment by SilurianYang** [comment]
## 1.2.4 已修复

**Comment by rason560** [comment]
我已经更新了1.2.4。为什么还依然出现query=%7B%7D 呢

**Comment by SilurianYang** [comment]
> 我已经更新了1.2.4。为什么还依然出现query=%7B%7D 呢

你确定是没传递参数时还会带上这个? 你先卸载然后再安装

**Comment by rason560** [comment]
> > 我已经更新了1.2.4。为什么还依然出现query=%7B%7D 呢
> 
> 你确定是没传递参数时还会带上这个? 你先卸载然后再安装

哦。那看来是我误会了。我以为传参的时候也不会有这个出现。
其实为何不能做成跟uniapp框架一样格式那样传参呢，能跟框架兼容。守卫里面的to.query也能获取到

**Comment by SilurianYang** [comment]
@rason560 只要你按照文档的传参方式 在守卫中to.query依然能获取到
