### ISSUE TITLE
咨询一个有关文档官网的问题！

### ISSUE THREAD

**Issue by 1414044032** [SilurianYang/uni-simple-router#152]
**问题描述**
[http://hhyang.cn/](http://hhyang.cn/)
[https://ustbhuangyi.github.io/vue-analysis/](https://ustbhuangyi.github.io/vue-analysis/)
[https://cn.vuejs.org/](https://cn.vuejs.org/)
你的文档说明网站还有下面vue官网。还有一个其他人的网站。看着好像一个模子里刻出来的一样。我想问一下这个是有什么类似Mockdown的工具来生成博客吗？还是自己写出来的这种效果？

我搜索到了gitBook 这个可以生成文档。但是不知道是否能达到作者这种效果。跟VUe官网类似的这种

**Comment by SilurianYang** [comment]
## [用的这个库](https://github.com/vuejs/vuepress)

**Comment by 1414044032** [comment]
Ok 谢谢 ，了解了
