### ISSUE TITLE
出现path未定义错误

### ISSUE THREAD

**Issue by wodrow** [SilurianYang/uni-simple-router#154]
**问题描述**
Uncaught (in promise) TypeError: Cannot read property 'path' of undefined
    at ruleToUniNavInfo (chunk-vendors.js:94329)
    at Router.appletsTransitionTo

**复现步骤**
import Router from 'uni-simple-router'
Vue.use(Router);
然后出现这个错误

**系统信息:**
 - 发行平台: H5
 - 操作系统 windows 10
 - 项目创建方法 vue-cli
 - uni-simple-router版本 [如 v1.5.5]

**补充信息**
![微信截图_20200729192934.png](https://i.loli.net/2020/07/29/WlFmsq2KgXDjnMr.png)

**Comment by SilurianYang** [comment]
##没实例化 没条件编译  没配置vue.config.js 路由表配置错误

**Comment by wodrow** [comment]
### 在vue.config.js添加配置

```
....
module.exports = {
    transpileDependencies:['uni-simple-router'],
    ....
};
```
