### ISSUE TITLE
微信小程序：用户初始直接从直播间卡片进入小程序，不会触发app的onLaunch和onShow钩子

### ISSUE THREAD

**Issue by cb3570594** [SilurianYang/uni-simple-router#160]
**问题描述**
[问题描述：微信小程序，直播间卡片进入场景，不会触发app的onLaunch和onShow钩子]

**复现步骤**
直接从用户分享的直播间卡片进入小程序
没有触发app的onLaunch和onShow

**Comment by SilurianYang** [comment]
ok  等我验证
