### ISSUE TITLE
Hbuiler升级到2.8 以上 运行app 报错 

### ISSUE THREAD

**Issue by zhailin233** [SilurianYang/uni-simple-router#161]
**问题描述**
[问题描述：Hbuilder升级到2.8 以上 运行app 报错信息为 Error in onLoad hook: "TypeError: Cannot read property 'path' of undefined"]

**复现步骤**
[复现问题的步骤]
1、直接Hbuilder运行app就会出现

**预期结果**
在Hbuilder版本为最新版本时 能正常运行app

**实际结果**
1、报错信息为 Error in onLoad hook: "TypeError: Cannot read property 'path' of undefined"

**系统信息:**
 - 发行平台: App
 - 操作系统 Android 9.0
 - HBuilderX版本 2.8.6
 - 项目创建方法 HBuilderX
 - 设备信息 HONOR 20i
 - uni-simple-router版本 1.5.1

**补充信息**
重新安装依赖 发现
![image](https://user-images.githubusercontent.com/42528987/90350524-026edb80-e070-11ea-9b7b-2630474766d9.png)所以我觉得是uni-simple-router问题

**Comment by SilurianYang** [comment]
试试最新版本的

**Comment by zhailin233** [comment]
> 试试最新版本的

谢谢 可以了
