### ISSUE TITLE
不支持router.addRoutes动态路由方法

### ISSUE THREAD

**Issue by BrUsHcyl** [SilurianYang/uni-simple-router#163]
由于权限控制功能的需要，故使用动态路由API，但设置
h5:{
    vueRouterDev:true,  //完全使用vue-router开发 默认 false  
}
仍无法使用router.addRoutes动态路由方法

**Comment by SilurianYang** [comment]
你可以用页面组件对象下的`$router`也可以使用路由插件实例下的`$route`进行调用 vue-router 的api。在 `vueRouterDev:true` 模式下你跳转、获取参数等操作都是使用 vue-router 的api 而非是使用路由插件的api

### 比如
```js
const router = new Router({
	encodeURI:false,
	routes: [...ROUTES] //路由表
});
//全局路由前置守卫
router.beforeEach((to, from, next) => {
	console.log(router.$route)
	next()
})
``
