### ISSUE TITLE
微信小程序不支持beforeEach增加多个控制

### ISSUE THREAD

**Issue by ErrorJe** [SilurianYang/uni-simple-router#165]
**问题描述**
微信小程序不支持beforeEach增加多个控制

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

```js
Object.values(hooks).forEach(hook => {
  router.beforeEach(hook.bind(router))
})
```

**预期结果**
若 hooks 里有2个方法，则2个方法都有效

**实际结果**
只会执行 hooks 里第一个方法，后面的均无效

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
不支持 仅支持注册一个生命周期
