### ISSUE TITLE
uni-app 使用 cli方式创建的时候 是否也支持该 该插件?

### ISSUE THREAD

**Issue by fujianlijiahan** [SilurianYang/uni-simple-router#166]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

chunk-vendors.js:54069 Uncaught (in promise) TypeError: Cannot set property 'query' of undefined
    at formatFrom (chunk-vendors.js:54069)
    at Router.appletsTransitionTo (chunk-vendors.js:53774)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
支持

**Comment by fujianlijiahan** [comment]
哪个版本的脚手架是可以的?我看最新版的报了一个错误

**Comment by SilurianYang** [comment]
> 哪个版本的脚手架是可以的?我看最新版的报了一个错误

全部都支持，请按照[文档配置](http://hhyang.cn/src/router/start/quickstart.html)

**Comment by fujianlijiahan** [comment]
问题已经解决，非常感谢！



---原始邮件---
发件人: "hhyang"<notifications@github.com&gt;
发送时间: 2020年9月3日(星期四) 下午2:36
收件人: "SilurianYang/uni-simple-router"<uni-simple-router@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"fujianlijiahan"<569280750@qq.com&gt;;
主题: Re: [SilurianYang/uni-simple-router] uni-app 使用 cli方式创建的时候 是否也支持该 该插件? (#166)




  
哪个版本的脚手架是可以的?我看最新版的报了一个错误
  
全部都支持，请按照文档配置

**Comment by wenjianli92** [comment]
你有遇到了这个问题，你是怎么解决的

**Comment by fujianlijiahan** [comment]
1:
http://www.hhyang.cn/src/router/start/quickstart.html
