### ISSUE TITLE
发现的几个h5端bug

### ISSUE THREAD

**Issue by wuliankui86** [SilurianYang/uni-simple-router#167]
最近试用了一下，发现几个问题：
1.h5端 全局前置路由守卫beforeEach，在进行页面跳转的时候会触发两次
2.h5端，引入该插件后uni.navigateTo() 被改写，跳转后不会缓存上一个页面的内容，而原uni.navigateTo()是可以缓存的。
3.微信小程序端，引入该插件后会报几个hook错误，但是不影响使用。

**Comment by wuliankui86** [comment]
再补充一下，
this.$Router.push({ path: 'router1', query: { plan: 'private' }})
无法使用相对路径

**Comment by SilurianYang** [comment]
* 路由守卫执行两次？ 多次use了？ 请检查代码
* uni.navigateTo 可以缓存
* 报错多半是你配置错误，而正常的情况是不会出现这样的问题的
* path跳转只能使用绝对路径，没说过可以使用相对路径

### 此外你可以查看示例是否有这样的问题
