### ISSUE TITLE
首页刷新白屏

### ISSUE THREAD

**Issue by Linceo** [SilurianYang/uni-simple-router#170]
**问题描述**
首页打开刷新就会白屏，只显示底部tab栏，切换其他路由也是白屏，再次刷新其他页面，正常显示，切换首页正常显示，一旦在首页刷新就会白屏

**复现步骤**
[复现问题的步骤]
1. 启动 '首页刷新'
2. 点击  '切换页面，再次刷新'
3. 查看  切换首页

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/43595749/93282928-0a05d980-f802-11ea-8dae-9a98eefdf0d5.png)
![image](https://user-images.githubusercontent.com/43595749/93282945-1853f580-f802-11ea-86a1-b98a53ca903e.png)

**系统信息:**
 - 发行平台: H5平台
 - HBuilderX版本  2.8.11.20200904-alpha
 - 项目创建方法  HBuilderX
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
请帖出你的`mian.js`完整代码

**Comment by Linceo** [comment]
import Vue from 'vue'
import App from './App'
import router from './router'
import { RouterMount } from 'uni-simple-router';
 
Vue.config.productionTip = false

App.mpType = 'app'

// #ifdef H5
	RouterMount(app,'#app');
// #endif

const app = new Vue({
	...App
})

app.$mount();

**Comment by Linceo** [comment]
谢谢，是main.js写的不对

**Comment by guxuehua** [comment]
我的也是这样的，tabbar重复多次点击页面又会显示

**Comment by Linceo** [comment]
> 我的也是这样的，tabbar重复多次点击页面又会显示

我是mian.js写的不对，导致的刷新问题，没有多次点击显示的问题

**Comment by Linceo** [comment]
我是main.js写的不对导致的刷新匹配不到路由，没有重复点击显示的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilurianYang/uni-simple-router"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 下午2:01
收件人:&nbsp;"SilurianYang/uni-simple-router"<uni-simple-router@noreply.github.com&gt;;
抄送:&nbsp;"1574364586"<1574364586@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [SilurianYang/uni-simple-router] 首页刷新白屏 (#170)





 
我的也是这样的，tabbar重复多次点击页面又会显示
