### ISSUE TITLE
`beforeRouteLeave ` 方法调用一次之后再次从页面后退就不触发了

### ISSUE THREAD

**Issue by flawless95** [SilurianYang/uni-simple-router#171]
**问题描述**
功能：用户没有填完信息如果点了浏览器后退按钮，需要弹出确认弹窗确认。 
问题：在组件中使用beforeRouteLeave方法，第一次点了后退可以进入这个方法正常执行，但是第二次再点后退就不能执行了

**复现步骤**
![uni-simple-router](https://user-images.githubusercontent.com/31276180/93415626-88cc4680-f8d6-11ea-97e9-c28adec54271.gif)

1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5 
 - 操作系统 chrome
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法： HbuilderX
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本：1.5.4

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
这就比较尴尬了 你可以这样暂时解决

```js
		beforeRouteLeave(to, from, next) {
			uni.showModal({
			    title: '提示',
			    content: '这是一个模态弹窗',
			    success:  (res)=> {
			        if (res.confirm) {
						next();
			        } else if (res.cancel) {
						next(false);
						this._HHYANGbeforeRouteLeaveCalled=false
			        }
			    }
			});
```

**Comment by flawless95** [comment]
![1600315364(1)](https://user-images.githubusercontent.com/31276180/93418898-f9c32c80-f8dd-11ea-9714-b5175fd90bc4.jpg)

emmmmm 老哥 哈哈哈哈

**Comment by SilurianYang** [comment]
## [v2.0.0-alpha.1](https://github.com/SilurianYang/uni-simple-router/releases/tag/v2.0.0-alpha.1) 已修复

**Comment by Tron1234** [comment]
![image](https://user-images.githubusercontent.com/47961959/107134212-fbdc6500-692a-11eb-9cd2-f6f52b0057fb.png)
修改concat.js中的源码，我老早就和作者提出这个问题了，他觉得没问题，我自己改源码修好的

**Comment by SilurianYang** [comment]
@Tron1234 有啥建议我没有采纳的你可以新开一个issue 描述全  这个issue已经处于解决并修复的状态

**Comment by Tron1234** [comment]
没事我用的1.5.5自己改了下源码就可以正常使用了，QQ群里@你了
