### ISSUE TITLE
小程序端路由参数中带有特殊字符会做encode处理

### ISSUE THREAD

**Issue by iversong** [SilurianYang/uni-simple-router#172]
**问题描述**
小程序端对路由参数中的特殊字符处理与其它端不一致，小程序端会对参数做encodeURIComponent处理，期望多端统一。

**复现步骤**
1. 分别在微信开发者工具和浏览器启动附件中demo
2. 点击去路由1页面
3. 在控制台查看打印出来的路由参数

**核心代码**

```
<button type="default" @click="$Router.push({path: '/pages/router1/router1', query:{keyword: 'air jordan'}})">去路由1页面</button>
```

**预期结果**
希望uni-simple-router对小程序端特殊字符的路由参数不做encode处理，和uni.navigateTo保持一致，多端统一。

**实际结果**

```
//小程序端
{keyword: "air%20jordan"}

// H5端
{keyword: "air jordan"}
```

**系统信息:**
 - 发行平台: [微信小程序、H5平台]
 - 操作系统 [iOS、Android]
 - HBuilderX版本 [2.8.11.20200907]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [iPhone Xs]
 - uni-simple-router版本 [v1.5.5]

**补充信息**
[demo](https://snake-xy.oss-cn-hangzhou.aliyuncs.com/xy-web/ideCreateBase.zip)

**Comment by SilurianYang** [comment]
已确认小程序端 特殊字符转码后无法自动回转

**Comment by SilurianYang** [comment]
## [v2.0.0-alpha.1](https://github.com/SilurianYang/uni-simple-router/releases/tag/v2.0.0-alpha.1) 已修复
