### ISSUE TITLE
uniapp H5 关于文件夹层级和uni-simple-router的关系

### ISSUE THREAD

**Issue by foreverwaiting** [SilurianYang/uni-simple-router#173]
**问题描述**
[问题描述：当文件夹层级有src且main.js，pages.json，App.vue，在src内时，使用并配置uni-simple-router和 uni-read-pages后，使用uni.navigateTo无法触发路由前置守卫？]

**复现步骤**
[复现问题的步骤]
1. 新建一个uniapp h5项目，并建立分包src等文件夹层级
2. 按uni-simple-router文档安装配置使用，在路由前置守卫随便console一些内容
3. 写几个uni.navigateTo跳转，则不触发console的内容

[或者可以直接贴源代码]

**预期结果**
[点击uni.navigateTo后应该打印相关信息]

**实际结果**
[未打印]

**系统信息:**
 - 发行平台: [H5平台]

**补充信息**
[可选]
[根据你的分析，层级问题？]

**Comment by SilurianYang** [comment]
看你的项目结构是脚手架生成的，请对比下 **快速上手头部黄色警告部分**
