### ISSUE TITLE
劫持小程序生命周期报错

### ISSUE THREAD

**Issue by flawless95** [SilurianYang/uni-simple-router#175]
**问题描述**
提示 onShow 取不到

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
![QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMjAxODg1NzI4OV92MlxJbWFnZUZpbGVzXDE2MDA5MzY4ODc5MTdfNzk5NDg5Q0UtREE3NS00MDg1LTgxMzMtMUMxNzQ1QkZEOEY1LnBuZw==](https://user-images.githubusercontent.com/31276180/94122550-4631dd80-fe85-11ea-9867-ad06ac7eba7f.png)
![uuuu](https://user-images.githubusercontent.com/31276180/94122551-47630a80-fe85-11ea-99b8-43e3b39f5330.png)
![yyy](https://user-images.githubusercontent.com/31276180/94122556-48943780-fe85-11ea-9b1f-d364c8b92b20.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by flawless95** [comment]
this.$options  里面没有onShow

**Comment by SilurianYang** [comment]
这个一个已知的bug  你可以在app.vue声明全 `onLaunch`、`onShow` 生命周期即可

### 像这样：
```js
//app.vue

    export default {  
        onLaunch: function() {  
            console.log('App Launch，app启动')  
        },  
        onShow: function() {  
            console.log('App Show，app展现在前台')  
        },  
        onHide: function() {  
            console.log('App Hide，app不再展现在前台')  
        }  
    }  
```

**Comment by SilurianYang** [comment]
## [v2.0.0-alpha.1](https://github.com/SilurianYang/uni-simple-router/releases/tag/v2.0.0-alpha.1) 已调整
