### ISSUE TITLE
页面回退刷新问题

### ISSUE THREAD

**Issue by gc18773375617** [SilurianYang/uni-simple-router#177]
第一次返回的时候为什么 页面会重新加载 第二次返回的时候就没有这种情况

**Comment by SilurianYang** [comment]
上传一个demo 我帮你排除下

**Comment by gc18773375617** [comment]
> 上传一个demo 我帮你排除下
我的uniapp_router项目 从/pages/index/aaaa/aaaa地址 点击 跳转按钮 跳转到bbb页面然后点击返回按钮 第一次 aaa页面刷新了 然后重复操作 aaa页面就没有刷新了

**Comment by SilurianYang** [comment]
按你的demo测试 没任何问题

**Comment by gc18773375617** [comment]
> 按你的demo测试 没任何问题

第一次回退aaa页面执行了mounted周期 第二次以后回退aaa页面mounted就没执行了

**Comment by SilurianYang** [comment]
[uniapp_router.zip](https://github.com/SilurianYang/uni-simple-router/files/5383250/uniapp_router.zip)
这是你自己的demo 你可以看看

**Comment by gc18773375617** [comment]
> [uniapp_router.zip](https://github.com/SilurianYang/uni-simple-router/files/5383250/uniapp_router.zip)
> 这是你自己的demo 你可以看看

你看下我手机录的屏
[b657b0a50c1c3bd1e6b939379e6727e0.zip](https://github.com/SilurianYang/uni-simple-router/files/5383374/b657b0a50c1c3bd1e6b939379e6727e0.zip)

**Comment by SilurianYang** [comment]
@gc18773375617  按你的理解试试 不用路由插件 看官方的会这样吗？

**Comment by gc18773375617** [comment]
> @gc18773375617 按你的理解试试 不用路由插件 看官方的会这样吗？

我去掉路由插件就没有这个问题了 我也换过其他的路由插件没有这个问题

**Comment by SilurianYang** [comment]
把index 作为首页，然后刷新后，进入a接着继续你的操作。别刷新 你这样操作的？

**Comment by gc18773375617** [comment]
> 把index 作为首页，然后刷新后，进入a接着继续你的操作。别刷新 你这样操作的？

我是直接进入的a页面 然后跳转b页面返回的

**Comment by SilurianYang** [comment]
非首页会做一个重定向，所以会这样

**Comment by gc18773375617** [comment]
> 非首页会做一个重定向，所以会这样

这个可以有方法解决吗?

**Comment by alphayan** [comment]
这有办法解决吗？

**Comment by SilurianYang** [comment]
## [v2.0.0-alpha.1](https://github.com/SilurianYang/uni-simple-router/releases/tag/v2.0.0-alpha.1) 已修复

**Comment by gc18773375617** [comment]
感谢 大佬牛皮
