### ISSUE TITLE
微信授权跳转  这个路由把链接code参数去掉了，导致无限循环

### ISSUE THREAD

**Issue by xiuyuan-wang** [SilurianYang/uni-simple-router#179]
**问题描述**
微信授权跳转  这个路由把链接code参数去掉了，导致无限循环，不断授权因为没有code参数

**复现步骤**

微信的授权：
https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx626fcef379eb1711&redirect_uri=https%3A%2F%2Fmysi.mayitest.cn%2F%3Fquery%3D%25257B%25257D&response_type=code&scope=snsapi_userinfo&state=&uin=MTgxNTI5OTEyOA%3D%3D&key=d351b67a5619f02f41263758d84a3201519bca16c329e9820c008c9687bb4550d4a37b025423508035c179a4a0d4c88a&pass_ticket=rU2bVF+OOeIJud9pqncEtJycQXt1iHy46hzzYRyChfq+SAqgKYx4QkyVFHZyPQ5t61FtxGam8JmSYY9wYaXEBA==
跳转到
域名/?query=%257B%257D&code=081Cax000bNKvK1xgQ200rgkQg2Cax0I&state=
 此时页面进入 自动被截取参数了
域名/?query=%257B%257D

**预期结果**
跳转链接不要遍。我是读取page.json的路由 路由是没有参数的
域名/?query=%257B%257D&code=081Cax000bNKvK1xgQ200rgkQg2Cax0I&state=

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/15852591/97070516-85ca2180-160b-11eb-82a9-3b847352b00a.png)
![image](https://user-images.githubusercontent.com/15852591/97070540-af834880-160b-11eb-9156-2fba6545181b.png)

**系统信息:**
 - 发行平台: [如 H5平台、微信公众号]

**补充信息**
就是路由路径的参数被截取了 。不用你们这个没事。

**Comment by SilurianYang** [comment]
``` js
 encodeURI:false
```
