### ISSUE TITLE
使用`uni-simple-router `后,`map` 标签报错

### ISSUE THREAD

**Issue by sc32024826** [SilurianYang/uni-simple-router#180]
**问题描述**
使用`<map>`标签时会报错:
1.打开有`map`标签的页面时:`Error in mounted hook:"TypeError: Cannot read property 'id' of undefined"`
2.关闭有`map`标签的页面时:`Error in beforeDestroy hook: "TypeError: Cannot read property 'id' of undefined"`
**复现步骤**
[复现问题的步骤]
1. '任意uniapp项目,安装`uni-simple-router`'
2. '在页面中使用`map`标签'
3. '运行项目,打开相应页面,'

[或者可以直接贴源代码]

**预期结果**
没有报错,

**实际结果**
地图有显示出来,但是有报错
![QQ图片20201029104202](https://user-images.githubusercontent.com/8088068/97534754-80971900-19f5-11eb-825a-39fa678575e1.png)

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [windows PC端]
 - HBuilderX版本 [2.9.3]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
注释掉`map`标签即没有报错,  或者不引入 `uni-simple-router` 使用 `pages.js`也不会报错

**Comment by SilurianYang** [comment]
## 新版2.0见

**Comment by SilurianYang** [comment]
## [v2.0.0-alpha.1](https://github.com/SilurianYang/uni-simple-router/releases/tag/v2.0.0-alpha.1) 已修复
