### ISSUE TITLE
导航守卫拦截跳转问题优化

### ISSUE THREAD

**Issue by UMS2016** [SilurianYang/uni-simple-router#181]
**问题描述**
以【登录状态校验】为例  
如没有配置【detectBeforeLock】
在beforeEach中调用【next('/pages/login/login');】
就会报错【{type:2, msg:'当前页面正在处于跳转状态，请稍后再进行跳转...' }】

**复现步骤**
// 路由配置

```js
const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,
	detectBeforeLock: ()=>{ router.$lockStatus=false; }, // 配置解锁[重要]
	routes: []
});

```

// 路由拦截
```js
router.beforeEach((to, from, next) => {
	var isLogin = true; // 登录状态
	if( isLogin === false && to.path!=='/pages/login/login') {
		uni.showToast({ : '请先登录', icon: 'none', duration: 1500 });
		setTimeout(function(){ next('/pages/login/login'); }, 1500);
		return;
	}
	next();
});

```

**预期结果**
首先已与插件作者取得联系 作者已帮我解决 在此表示非常感谢，
应作者要求 在此提出issue 并希望：
1-与vue框架的路由配置相似(解锁为默认配置)
2-完善说明文档
3-在demo中能完善一些经典的功能(如登录校验)
再次感谢

**Comment by SilurianYang** [comment]
文档已在构建中，感谢你的反馈

**Comment by XuCe** [comment]
next 跳转登录页之后白屏 要刷新才显示 @SilurianYang 
![image](https://user-images.githubusercontent.com/4842592/98975793-83dfe800-2551-11eb-9687-88304efab5a5.png)
