### ISSUE TITLE
微信小程序环境下，首页（同时是tabbar页面）onLoad会触发两次

### ISSUE THREAD

**Issue by WangEn** [SilurianYang/uni-simple-router#182]
**问题描述**
uniapp编译到微信小程序环境下，首页（pages数组的第一项）onLoad会触发两次

**补充信息**
~~~
// package.json
{
"dependencies": {
    "uni-read-pages": "^1.0.5",
    "uni-simple-router": "^2.0.0-alpha.1"
  }
}

~~~

![index](https://user-images.githubusercontent.com/12842804/98799134-ae467e00-2449-11eb-85d6-d1d0a7030f5b.png)

**Comment by WangEn** [comment]
开发者工具下添加编译模式，设置其他页面为启动页面时，启动页面同样会出现此情况，onload触发两次

**Comment by SilurianYang** [comment]
可以提供一个demo吗？

**Comment by WangEn** [comment]
> 可以提供一个demo吗？

精简了一份demo，删除了一些无关的内容，可以看下行不

[router-demo1111.zip](https://github.com/SilurianYang/uni-simple-router/files/5524452/router-demo1111.zip)

**Comment by SilurianYang** [comment]
@WangEn  我现在帮你看看

**Comment by WangEn** [comment]
> @WangEn 我现在帮你看看

好的，感谢，辛苦啦

**Comment by SilurianYang** [comment]
这个确实是之前 `alpha.1` 的bug  我最近没提交。我现在发布 `alpha.2`

**Comment by WangEn** [comment]
> 这个确实是之前 `alpha.1` 的bug 我最近没提交。我现在发布 `alpha.2`。安装新的即可！

嗯嗯，好的👌
