### ISSUE TITLE
uniapp typescript ，npm run dev:h5，报错：Failed to mount component: template or render function not defined.  (found in <Root>)

### ISSUE THREAD

**Issue by catx1726** [SilurianYang/uni-simple-router#184]
**问题描述**
使用 uniapp typescript  uni-simple-router
`npm run dev:h5`，控制台报错如下：
`Failed to mount component: template or render function not defined.  (found in <Root>)`

**报错信息**
![图片](https://user-images.githubusercontent.com/45514446/99048582-b5e45f00-25d0-11eb-89c2-218086529faf.png)

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [WIN10]
 - VSCODE
 - 项目创建方法 [ uniapp-cli ]
 - uni-simple-router版本 [ v1.5.5 ]

**代码块**
`router/modules/index.ts`
![图片](https://user-images.githubusercontent.com/45514446/99048421-7d448580-25d0-11eb-98e3-f0d176cf5548.png)

`router/modules/home.ts`
![图片](https://user-images.githubusercontent.com/45514446/99048291-58501280-25d0-11eb-8ed0-f43b6bb970f5.png)

`router/index.ts`
![图片](https://user-images.githubusercontent.com/45514446/99048487-964d3680-25d0-11eb-8e49-77a313426575.png)

`main.ts`
![图片](https://user-images.githubusercontent.com/45514446/99048516-9fd69e80-25d0-11eb-8cd2-0baebad1d182.png)

`pages.json`
![图片](https://user-images.githubusercontent.com/45514446/99048721-e1ffe000-25d0-11eb-99ec-a19df530ad6b.png)
![图片](https://user-images.githubusercontent.com/45514446/99048745-e9bf8480-25d0-11eb-9543-b666d32e5c06.png)

找了半天，实在不知道问题出在哪里，希望指点一下，谢谢

**Comment by SilurianYang** [comment]
请在 `main.ts` 中加入 `App.mpType = 'app'` 告知 uni-app 编译器。其次你把 `h5节点下的vueRouterDev关闭后` 重新编译看能行不

**Comment by catx1726** [comment]
谢谢回复，我在刚开始的时候把 `App.mpType = ' app ' ` 加到 `main.ts`，ts语法检查会报出：
![图片](https://user-images.githubusercontent.com/45514446/99205304-22d73f00-27f3-11eb-84e9-4fb09886135c.png)
不过，我在 `App.vue` 的文件中也进行了指定，不知道他们是否是同一作用：
![图片](https://user-images.githubusercontent.com/45514446/99205476-a09b4a80-27f3-11eb-85f8-765545501fbd.png)

然后，我把 `RouterMount(app, '#app')` 给注释掉了，重新运行，报错消失了，但是页面仍是空白，我在想是不是我 `pages` 的配置出了问题?

**Comment by catx1726** [comment]
我在 `beforeEach` 中写了一个 `console` ，结果发现，并没打印 console 的内容

![图片](https://user-images.githubusercontent.com/45514446/99206890-777cb900-27f7-11eb-9b55-f3be9fba0d96.png)


![图片](https://user-images.githubusercontent.com/45514446/99206845-5c11ae00-27f7-11eb-9028-1ff213ff52d4.png)

**Comment by SilurianYang** [comment]
直接上传一个demo吧

**Comment by laozei6401** [comment]
版本 1.5.5 
App.vue 必须要有onLaunch,onShow这两个周期，没有判断为空
子页面 created周期不触发

**Comment by SilurianYang** [comment]
必须写onLaunch,onShow这两个周期 是已知问题  在2.0y已修复

但是你说的子页面？created 不触发? 具体是什么端？是子组件还是子页面？ 或者上个demo?

**Comment by SilurianYang** [comment]
ts初始化的项目，把 `app.vue` 改成这样：
```js
<script>
	export default {
		onLaunch: function() {
			console.log('App Launch')
		},
		onShow: function() {
			console.log('App Show')
		},
		onHide: function() {
			console.log('App Hide')
		}
	}
</script>

<style>
	/*每个页面公共css */
</style>
```

**Comment by zhenizhui** [comment]
@catx1726 朋友，最后你是怎么解决的？我也遇到一摸一样的问题啊，我也是用ts
