### ISSUE TITLE
设置路由之后 第一次启动会出现白屏 再次刷新才可以显示出页面

### ISSUE THREAD

**Issue by liyuling486** [SilurianYang/uni-simple-router#185]
**问题描述**
在beforeEach中判断路由  跳转 第一次会出现白屏 刷新才能显示页面

**复现步骤**

在HBuilderX新建一个uni-ui项目
安装uni-simple-router uni-read-pages 修改beforeEach 后会出现问题

**预期结果**
希望启动后 可以正常显示页面

**实际结果**

![微信截图_20201113185124](https://user-images.githubusercontent.com/42409013/99065050-c94bf600-25e1-11eb-8cb4-bc7400274c81.png)
![image](https://user-images.githubusercontent.com/42409013/99065713-c1d91c80-25e2-11eb-8d99-6f8adc0ed47f.png)

**系统信息:**
 - uni-simple-router版本 [2.0.0-alpha]
[demo.zip](https://github.com/SilurianYang/uni-simple-router/files/5536338/demo.zip)

**Comment by liyuling486** [comment]
@SilurianYang

**Comment by SilurianYang** [comment]
对不起 这是个bug   讲在下个版本中修复

**Comment by Dylanchouxd** [comment]
> 对不起 这是个bug 讲在下个版本中修复

请问下 下个版本 是什么时候出呢，因为这边也遇到这个问题了。

**Comment by SilurianYang** [comment]
可以暂时这样解决，添加后置路由即可

```js
router.afterEach((to, from) => {
  // ...
})
```
