### ISSUE TITLE
配置路由之后 会影响之前的分包加载吗

### ISSUE THREAD

**Issue by zc20081989** [SilurianYang/uni-simple-router#187]
配置路由之后 会影响之前的分包加载吗

**Comment by SilurianYang** [comment]
不会！ [uni-read-pages](https://github.com/SilurianYang/uni-read-pages) 会把你配置的 `分包对象` 和 `pages` 合并， 输出最终结果

**Comment by boycot2015** [comment]
分包加载适用于1.5.5版本的路由吗
