### ISSUE TITLE
小程序环境，fullPath undefined如何解决

### ISSUE THREAD

**Issue by embracelong** [SilurianYang/uni-simple-router#188]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
TypeError: Cannot read property 'fullPath' of undefined

代码断点：page.$page.fullPath

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 2.7.14
 - 项目创建方法 [HBuilderX]
 - uni-simple-router版本 2.0.0-alpha.2

**Comment by embracelong** [comment]
小程序不等同于H5 小程序已经固定好入口文件了 新版路由已经代理了 首页的生命周期，只不过页面会显示出来。 在小程序端你应该这样做 如果有权限需要验证登录，你可以在pages.json 中 针对小程序 新增一个空白页面 来做过度界面。等待判断完成后再显示正真的首页。

如果是小程序不推荐使用这个插件么？

**Comment by SilurianYang** [comment]
请问 你是在什么情况下访问的 `$Route` ??  是在vue的生命周期里面吗？  还是在标准的`uni-app`生命周期下？

**Comment by embracelong** [comment]
> 请问 你是在什么情况下访问的 `$Route` ?? 是在vue的生命周期里面吗？ 还是在标准的`uni-app`生命周期下？

小程序首页访问的时候报错

**Comment by SilurianYang** [comment]
@embracelong  你是有访问 `$Route` ? 还是运行就报错啦？ 如果有使用 请帖上如何访问的代码

**Comment by embracelong** [comment]
可能是hbuiler 插件市场安装有缺少，用npm install 就正常了
