### ISSUE TITLE
使用H5完全vue-router模式，使用路由守卫跳转白屏

### ISSUE THREAD

**Issue by denzw** [SilurianYang/uni-simple-router#189]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
使用H5完全vue-router模式，使用路由守卫跳转白屏
仓库地址：https://gitee.com/denzw/uni_cloud_admin.git

**复现步骤**
[复现问题的步骤]
1. 安装 'yarn'
2. 启动  'yarn serve'
3. 打开 ‘打开浏览器输入 http://localhost:8080/'

默认应该会跳转到 /login 页面，但显示白屏，没有正常显示该页面。

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [win10, chrome]
 - HBuilderX版本 [HBuilderX，2.9.8 ]
 - 项目创建方法 [Vue-cli创建]
 - 设备信息 [win10]
 - uni-simple-router版本 [2.0.0-alpha.2]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
### 我下载你提供的实例 启动正常 看下图
![1](https://user-images.githubusercontent.com/31280665/99899544-2b44e380-2ce5-11eb-9e46-4a15146104ef.gif)

**Comment by denzw** [comment]
在我的浏览器，手机中都不能正常显示跳转后的页面。看你的截图是正常显示出来了！
我重新删除，重新安装后再运行情况一样。
[屏幕截图](https://i.postimg.cc/xCkBHMbC/test.gif)

**Comment by SilurianYang** [comment]
试试升级个版本

**Comment by denzw** [comment]
谢谢，升级到 uni-simple-router@2.0.0-alpha.3后问题解决了
