### ISSUE TITLE
路由beforeEach无法拦截tabbar跳转？

### ISSUE THREAD

**Issue by ftcl** [SilurianYang/uni-simple-router#19]
大佬，使用tabbar的pages配置，点击tabbar切换，会出现先跳转tabbar页面1跳转到tabbar页面2成功后，再跳转到其他页面3，无法拦截tabbar的切换。
这个有办法处理？

**Comment by SilurianYang** [comment]
> 大佬，使用tabbar的pages配置，点击tabbar切换，会出现先跳转tabbar页面1跳转到tabbar页面2成功后，再跳转到其他页面3，无法拦截tabbar的切换。
> 这个有办法处理？

原生tab不受router api 控制所以是先被执行后走生命钩子 你可以舍弃掉原生tabbar 自定义
