### ISSUE TITLE
官方案例不能使用 http://hhyang.cn/v2/start/quickstart.html

### ISSUE THREAD

**Issue by Agaoquan** [SilurianYang/uni-simple-router#190]
你好。使用http://hhyang.cn/v2/start/quickstart.html  2.x 版本 快速上手案例。一起正常。当
![image](https://user-images.githubusercontent.com/19632534/99935530-db752380-2d9b-11eb-91f1-dd3c7653010b.png) next（）加入地址后不能正常跳转，白屏。控制台一直不停
![image](https://user-images.githubusercontent.com/19632534/99935604-fe9fd300-2d9b-11eb-9e43-d51980dbcd51.png)
谢谢

**Comment by SilurianYang** [comment]
你这是死循环啦，请注意逻辑。只有在`next()` 的情况下才表示本次守卫正常通行，否则会重新执行知道成功。

**Comment by Agaoquan** [comment]
> 你这是死循环啦，请注意逻辑。只有在`next()` 的情况下才表示本次守卫正常通行，否则会重新执行知道成功。

老铁。看我截图。next（xx）里面写了跳转的地址。我已经走了next了。 只是一直跳不出去。我初步估计是否和pages。json 的首页有关系
