### ISSUE TITLE
App.vue里加上template(为了使用keep-alive)后，uni.showModal等弹窗失效

### ISSUE THREAD

**Issue by xlkit456852** [SilurianYang/uni-simple-router#191]
为了对首页进行keep-alive，在App.vue里加上了一段<template>，原本是只有原始的<script>和<style>
加上的代码如下：
```
<template>
    <view id="app" >
		<keep-alive :include="/index/">
			<router-view></router-view>
		</keep-alive>
	</view>
</template>
```
这样的确是对首页进行了keep alive，但是发现项目里的所有uni.showToast、uni.showModal等弹出窗口全部都不能弹出，但是去掉<template>块后是可以正常弹出的。请问可以如何解决？或者keep-alive这里可以以别的方式使用来避免这种情况出现吗？

**Comment by xlkit456852** [comment]
刚刚问了一下uniapp官方，原来不用加这个<template>的，默认就是支持keep-alive的，我用一个空白项目来测试过的确如此。这里的template标签我已经去掉了，但是并没有像空白项目那样有keepalive，不知道uni-simple-router是否有某种特性影响了这个keepalive的执行呢？

**Comment by SilurianYang** [comment]
你的意思是在h5端 onload或者created有多次反复执行？

**Comment by xlkit456852** [comment]
我从页面栈观察到的现象是，当我从首页跳转到其他内部页面后，首页变为了inactive。然后返回时，这个inactive的首页没有重新激活，而是又新建了一个全新的首页页面。然后在这个新的首页重复上面的操作后，这次直接没有了keep alive的效果。那么值钱的inactive的首页就永远在那无法激活了

![image](https://user-images.githubusercontent.com/7323450/100616672-60d87500-3354-11eb-8e9e-08c00314bcbe.png)

**Comment by SilurianYang** [comment]
我需要排除下

**Comment by xlkit456852** [comment]
好 我也再测试下

**Comment by xlkit456852** [comment]
已经解决了，是因为我使用了$router而不是$Router...低级错误

**Comment by rzdxp15** [comment]
如何zaiuniapp中使用keepalive？
