### ISSUE TITLE
小程序对query参数中的中文字符未能自动解码

### ISSUE THREAD

**Issue by jingping-ye** [SilurianYang/uni-simple-router#192]
**问题描述**

小程序中，使用`this.$Router`携带query参数跳转，如果query参数中含有中文字符，跳转页面后使用`this.$Route.query`接收。此时，中文字符还是编码的状态。然而，在浏览器中表现正常。比如传递参数 `query:{type:"动物"}`, 小程序中表现为`%E5%8A%A8%E7%89%A9`, 浏览器正常。

**系统信息:**
 - 发行平台: 微信小程序、浏览器
 - 操作系统 :微信开发者工具中测试即可复现
 - HBuilderX版本:未使用
 - 项目创建方法:使用Vue-cli创建
 - 设备信息:微信开发者工具
 - uni-simple-router版本:2.0.0-alpha.4

**补充信息**
[根据你的分析，出现这个问题的原因可能在哪里？]
参数传递时，插件内部应该自动进行一次解码？？？

**Comment by SilurianYang** [comment]
### 可暂时这样解决：
```js
const router = createRouter({
        // ....
	parseQuery(query){
		let jsonQuery=query
		// #ifndef H5
			jsonQuery = JSON.parse(
				decodeURIComponent(JSON.stringify(query))
			)
		// #endif
		return jsonQuery
	}
});
```
