### ISSUE TITLE
什么时候可以支持 addRoutes 呢?

### ISSUE THREAD

**Issue by chenjidu** [SilurianYang/uni-simple-router#194]
想实现根据后端返回的路由表,动态渲染路由

**Comment by SilurianYang** [comment]
抱歉 目前没有这样的计划

**Comment by li1164267803** [comment]
> 抱歉 目前没有这样的计划

希望能加上这个功能，针对一些可以定制化的，权限类的。动态路由真的很有用

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
