### ISSUE TITLE
建议小程序和App也支持base参数

### ISSUE THREAD

**Issue by tomgao365** [SilurianYang/uni-simple-router#197]
**新功能描述**
建议小程序和App也支持base参数，比如避免每次都写/pages，减小调用时路由长度

**现状及问题**
复杂页面 path 挺长的

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by SilurianYang** [comment]
这个采纳  不过你现在可以通过 `name` 跳转。当然 `2.x` 以后 原生跳转也是支持的 所以避免不了 短url的情况。记录了

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性将会在 [V3.0](https://v3.hhyang.cn/)  版本中添加
