### ISSUE TITLE
`created` 生命周期调用 `this.$Route` 报错

### ISSUE THREAD

**Issue by zfowed** [SilurianYang/uni-simple-router#199]
**问题描述**
在页面组件的 `computed` `onLoad` `created` 的生命周期使用 `this.$Route` 时会报错:
TypeError: Cannot set property 'query' of undefined

**复现步骤**
1. 安装 `uni-simple-router`
2. `created` 生命周期调用 `this.$Route`
3. 运行项目,打开相应页面
![image](https://user-images.githubusercontent.com/23629388/102471625-65a96280-4090-11eb-8fee-f8ba2462e67f.png)

**预期结果**
没有报错

**实际结果**
![image](https://user-images.githubusercontent.com/23629388/102469347-95a33680-408d-11eb-9b30-c59d3a5e6d20.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 windows PC端
 - 项目创建方法 Vue-cli
 - uni-simple-router版本 [2.0.0-alpha.5.1]

**补充信息**
在页面组件的 `computed` `onLoad` `created` 的生命周期使用 `this.$Route` 时会报错，但是在 `mounted` 不会

**Comment by SilurianYang** [comment]
注册时机不对。跨端的情况下 统一在uni-app的生命周期下获取  不要再vue的生命周期中获取  特别是 mounted 之前的生命周期
