### ISSUE TITLE
在h5端，页面刷新之后，使用router.back就不能返回上一个页面了

### ISSUE THREAD

**Issue by cao1987** [SilurianYang/uni-simple-router#2]
使用uni-app原生的路由就是有这问题，所以我才找了插件，但是你这个好像还没解决，如何做到和vue-router的back一样呢？

**Comment by SilurianYang** [comment]
> 使用uni-app原生的路由就是有这问题，所以我才找了插件，但是你这个好像还没解决，如何做到和vue-router的back一样呢？

我去uni-app还有这种问题？刚才试了确实有，我现在修复下。1小时后等着更新

**Comment by SilurianYang** [comment]
@cao1987  请更新1.1.1已经修复此问题

**Comment by cao1987** [comment]
感谢
