### ISSUE TITLE
使用官方获取定位地址方法会报url未注册问题，路由已注册也不行

### ISSUE THREAD

**Issue by Avengervick** [SilurianYang/uni-simple-router#20]
调用uni的获取地址方法跳转报URL错误，我按照地址上的路径进行注册 还是报错，不知道怎么解决
![image](https://user-images.githubusercontent.com/18612691/64662802-429b0680-d47c-11e9-8d67-ced4b67a1c3d.png)
![image](https://user-images.githubusercontent.com/18612691/64662811-4dee3200-d47c-11e9-8b02-a4bd2458990e.png)
![image](https://user-images.githubusercontent.com/18612691/64662823-5ba3b780-d47c-11e9-83f0-aa19fb1a9f8b.png)

**Comment by SilurianYang** [comment]
这个路径是错的吧，写绝对路径 `/` 开头 
![QQ截图20190911103430](https://user-images.githubusercontent.com/31280665/64663890-dcb07e00-d47f-11e9-9bc8-3585266d20bd.png)

**Comment by Avengervick** [comment]
path路径写的/开头的哦

**Comment by SilurianYang** [comment]
> path路径写的/开头的哦

是脚手架项目么？

**Comment by Avengervick** [comment]
不是哦，但有些功能是从官网demo抄过去的，这个uni.getLocation是官方的方法，我内部自己的定义的跳转没什么问题

**Comment by SilurianYang** [comment]
> 不是哦，但有些功能是从官网demo抄过去的，这个uni.getLocation是官方的方法，我内部自己的定义的跳转没什么问题

那你发我一个测试demo  1606726660@qq.com

**Comment by Avengervick** [comment]
刚用git上test demo测的，就加了个按钮测试uni.getLocation 也是同样的错误
![image](https://user-images.githubusercontent.com/18612691/64665679-05d40d00-d486-11e9-885b-1128803c7bc8.png)
![image](https://user-images.githubusercontent.com/18612691/64665694-0f5d7500-d486-11e9-922d-18b379f918b7.png)
![image](https://user-images.githubusercontent.com/18612691/64665700-15ebec80-d486-11e9-850e-8ab800bd4433.png)
![image](https://user-images.githubusercontent.com/18612691/64665707-1be1cd80-d486-11e9-8c68-1be1512596f4.png)


> > 不是哦，但有些功能是从官网demo抄过去的，这个uni.getLocation是官方的方法，我内部自己的定义的跳转没什么问题
> 
> 那你发我一个测试demo [1606726660@qq.com](mailto:1606726660@qq.com)

刚用git上test demo测的，就加了个按钮测试uni.getLocation 也是同样的错误
![image](https://user-images.githubusercontent.com/18612691/64665679-05d40d00-d486-11e9-885b-1128803c7bc8.png)
![image](https://user-images.githubusercontent.com/18612691/64665694-0f5d7500-d486-11e9-922d-18b379f918b7.png)
![image](https://user-images.githubusercontent.com/18612691/64665700-15ebec80-d486-11e9-850e-8ab800bd4433.png)
![image](https://user-images.githubusercontent.com/18612691/64665707-1be1cd80-d486-11e9-8c68-1be1512596f4.png)

**Comment by junmao813** [comment]
出现同样的问题，无解吗？

**Comment by junmao813** [comment]
解决了，配置要用//open-location这种。。。
![image](https://user-images.githubusercontent.com/4514953/64666462-f73b2500-d488-11e9-96f0-769620817f32.png)

**Comment by Avengervick** [comment]
厉害~可以了
