### ISSUE TITLE
H5端报了 TypeError: Cannot read property 'replace' of null at t.RouterMount

### ISSUE THREAD

**Issue by RajanZhan** [SilurianYang/uni-simple-router#201]
**问题描述**
我使用ts 版本的uni-simple-router ，完全按照文档引入，在h5端运行时，网页控制台报错，错误信息如下
chunk-vendors.js:54690 Uncaught TypeError: Cannot read property 'replace' of null
    at t.RouterMount (chunk-vendors.js:54690)
    at eval (main.ts:20)
    at Object../src/main.ts (index.js:1192)
    at __webpack_require__ (index.js:854)
    at fn (index.js:151)
    at Object.1 (index.js:1725)
    at __webpack_require__ (index.js:854)
    at checkDeferredModules (index.js:46)
    at index.js:994
    at index.js:997
**复现步骤**
可以编译成功，启动也成功，但是进入页面就报错。
```typescript
// main.ts
import Vue from 'vue'
import App from './App.vue'
import vant from "vant"
import "vant/lib/index.less"
Vue.use(vant);
//router
import { router, RouterMount } from "./router/index.router"
Vue.use(router)
Vue.config.productionTip = false

const app = new Vue({
    ...App
})

// #ifdef H5
RouterMount(app, router, '#app')
// #endif

// #ifndef H5
app.$mount(); //为了兼容小程序及app端必须这样写才有效果
// #endif

```
```typescript
//  router.ts
import { RouterMount, createRouter } from 'uni-simple-router';
const router = createRouter({
    platform: process.env.VUE_APP_PLATFORM,
    keepUniOriginNav: false,
    routes: [...ROUTES]
});

router.beforeEach((to, from, next) => {
	next();
});
router.afterEach((to, from) => {
    console.log('跳转结束')
})
export {
    router,
    RouterMount
}

```

**预期结果**
 路由ok

**实际结果**
见问题描述

**系统信息:**
 - 发行平台: [H5平台、5+ App等]
 - 操作系统 [Android 7.0]
 - HBuilderX版本 [2.9.8.20201110]
 - 项目创建方法 [使用Vue-cli创建]
 - uni-simple-router版本 [如 v2.0]

**补充信息**
无

**Comment by SilurianYang** [comment]
请提供完整路由版本

目前我手上有个ts项目正在使用都正常使用  版本：`"uni-simple-router": "^2.0.0-beta.4"`

**Comment by RajanZhan** [comment]
@SilurianYang  我的版本为，
"uni-read-pages": "^1.0.5",
"uni-simple-router": "^2.0.0-beta.4",
方便提供demo，或者我提供我的demo给您看看吗

**Comment by SilurianYang** [comment]
请上传你的demo

**Comment by RajanZhan** [comment]
@SilurianYang demo地址 https://github.com/RajanZhan/ts-uni-simple-router-debug.git，麻烦看下，非常感谢

**Comment by SilurianYang** [comment]
![QQ截图20201224112126](https://user-images.githubusercontent.com/31280665/103057353-3471ea80-45da-11eb-9f8a-719eee02a13d.png)
自己品

**Comment by RajanZhan** [comment]
@SilurianYang  import {RouterMount,createRouter} from 'uni-simple-router';

```typescript
const router = createRouter({
    platform: process.env.VUE_APP_PLATFORM,
    keepUniOriginNav:false,  
	routes: [...ROUTES]
});
```
我确认下，是platform的问题吗？

**Comment by SilurianYang** [comment]
我表示很无奈  🤮🤮🤮
```js
// app.vue
<script>
	export default {
        mpType:'app',
		onLaunch: function() {
			console.log('App Launch')
		},
		onShow: function() {
			console.log('App Show')
		},
		onHide: function() {
			console.log('App Hide')
		}
	}
</script>

```

**Comment by RajanZhan** [comment]
@SilurianYang  got it

**Comment by JoeHR** [comment]
我也出现了这个问题

**Comment by JoeHR** [comment]
![image](https://user-images.githubusercontent.com/22998545/130385530-bbe31c06-6016-4c34-8c14-5366d7fd8415.png)

**Comment by JoeHR** [comment]
我的demo 地址为 https://github.com/JoeHR/uni-simple-router-debug.git，可以帮忙看下什么问题吗

**Comment by onestar1** [comment]
大家 解决了吗？ 我也遇到这个问题了

**Comment by realboyJJ** [comment]
解决了，如果main.ts中没有指明mpType，需要去app.vue中添加
