### ISSUE TITLE
H5启动，路由报错Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by bestRenekton** [SilurianYang/uni-simple-router#202]
**问题描述**

引入项目后，启动H5，路由报错

**复现步骤**

[代码在此   dome ](https://gitee.com/dx3906_059/router-test)

**预期结果**

**实际结果**

![image](https://user-images.githubusercontent.com/15810263/103056393-ce846380-45d7-11eb-8678-ec5d1218825c.png)

**补充信息**
打印出来，createRouter生产的router对象$route为null，导致RouterMount绑定报错

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/201
