### ISSUE TITLE
微信小程序 back时 登陆拦截失败

### ISSUE THREAD

**Issue by jeasonHu** [SilurianYang/uni-simple-router#203]
**问题描述**
在微信小程序中 通过router.back(1)/uni.navigateBack(1)返回时  路由中to from正常，但实际跳转错误

**复现步骤**
有3个页面  index、login、test
beforeEach中有登陆状态拦截 （index、test）,
1. 进入index ——> 登陆拦截——> login ——>登陆成功跳转index
2. index 按钮跳转 test ——> test页面中清除登陆信息——>按钮返回  
[或者可以直接贴源代码]

**预期结果**
在返回操作后 应该被拦截 跳转到 login页面

**实际结果**
 路由ti跳转信息正常，实际却返回了index页面
![image](https://user-images.githubusercontent.com/14819724/103074059-c9d5a480-4603-11eb-8e6e-b267033c077f.png)

**系统信息:**
  "@dcloudio/uni-mp-weixin": "^2.0.0-29820201110001",
  "uni-simple-router": "^2.0.0-beta.4",

**Comment by SilurianYang** [comment]
请提供一个可复现的demo， `beforeEach` next 时有无明确指定 [NAVTYPE](https://hhyang.cn/v2/api/routerInsatll.html#navtype-v-1-1-0)

**Comment by jeasonHu** [comment]
> 请提供一个可复现的demo， `beforeEach` next 时有无明确指定 [NAVTYPE](https://hhyang.cn/v2/api/routerInsatll.html#navtype-v-1-1-0)
开始未指定NAVTYPE是直接next(path)方式,加上后问题解决
