### ISSUE TITLE
v2.0.0-beta.5版本小程序自定义编译模式携带启动参数时，页面onLoad不执行

### ISSUE THREAD

**Issue by WangEn** [SilurianYang/uni-simple-router#206]
**问题描述**
使用uni-simple-router v2.0.0-beta.5版本
如果携带启动参数，第一次进入时只能在应用生命周期onLaunch中获取到this.$Route及路由参数，不能在页面生命周期onLoad中获取到this.$Route及路由参数【页面生命周期onLoad不执行】

如果未携带启动参数，则可以执行到页面生命周期onLoad

**复现步骤**
[复现问题的步骤]
1. 微信开发者工具启动 '小程序'
2. 编辑自定义编译模式，设置启动参数
3. 编译

![41BB3CF9E7840EB35058A9768715F79E](https://user-images.githubusercontent.com/12842804/103255428-39f97700-49c4-11eb-9b03-d5c0532ef393.jpg)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 macOS 10.15.7
 - HBuilderX版本 2.9.8.20201119
 - 项目创建方法 HBuilderX创建
 - uni-simple-router版本 v2.0.0-beta.5

**补充**
历史版本相似描述issue  
[https://github.com/SilurianYang/uni-simple-router/issues/129](https://github.com/SilurianYang/uni-simple-router/issues/129)

**Comment by SilurianYang** [comment]
不写单元测试的后果 😳😳😳😳
https://github.com/SilurianYang/uni-simple-router/blob/dd988394ccdd6b542ef09adb218ec7e5ea9a0a32/src/helpers/utils.ts#L355-L360

**Comment by WangEn** [comment]
> 不写单元测试的后果 😳😳😳😳
> https://github.com/SilurianYang/uni-simple-router/blob/dd988394ccdd6b542ef09adb218ec7e5ea9a0a32/src/helpers/utils.ts#L355-L360

🤣🤣🤣 你抽出时间优化的这么好已经很给力啦

**Comment by WangEn** [comment]
> 不写单元测试的后果 😳😳😳😳
> https://github.com/SilurianYang/uni-simple-router/blob/dd988394ccdd6b542ef09adb218ec7e5ea9a0a32/src/helpers/utils.ts#L355-L360

更新了2.0.0-beat.6问题已修复
不过不知道为啥 页面的生命周期onShow 比 onLoad执行要早，疑惑
![image](https://user-images.githubusercontent.com/12842804/103261501-c31ca800-49dc-11eb-91f8-56dce2b2aceb.png)

**Comment by SilurianYang** [comment]
因为还原的页面级生命周期为对象形式，对象没有顺序。 onshow 和onload 是同步执行 所以只是带过而且 执行前后其实无所谓 相差大概就几毫秒而已 而组件级生命周期则为数组各式 保证执行顺序

**Comment by WangEn** [comment]
> 因为还原的页面级生命周期为对象形式，对象没有顺序。 onshow 和onload 是同步执行 所以只是带过而且 执行前后其实无所谓 相差大概就几毫秒而已 而组件级生命周期则为数组各式 保证执行顺序

嗯嗯  好的

**Comment by SilurianYang** [comment]
你有自己的想法也可以 `pr` 哦

**Comment by WangEn** [comment]
> 你有自己的想法也可以 `pr` 哦

(๑‾ ꇴ ‾๑)好哒
