### ISSUE TITLE
读取pages.json自动构建路由表的方式，如何使用beforeEnter守卫？

### ISSUE THREAD

**Issue by zdiary** [SilurianYang/uni-simple-router#207]
在pages.json里没有办法配置函数，文档里也没看到此方面内容，烦请解答一下~

**Comment by SilurianYang** [comment]
需要在运行时 自己用循环加进去。` pages.json`无法声明函数，编译不过。这能用这样的方法

**Comment by zdiary** [comment]
就是对全局变量ROUTES进行二次处理吧，明白了，非常感谢！
给这个项目点个star！

**Comment by SilurianYang** [comment]
谢谢您的支持 ❤❤❤❤❤
