### ISSUE TITLE
异步守卫在微信小程序里无效

### ISSUE THREAD

**Issue by zyip** [SilurianYang/uni-simple-router#208]
**问题描述**
异步守卫在微信小程序里无效
router.beforeEach((to, from, next) => {
     //模拟一个异步操作
     setTimeout(() => {
            console.log(' router beforeEach')
            next()
      }, 2000)
})

**复现步骤**
[复现问题的步骤]
beforeEach里，把next放入异步方法里无效， 路由没等待异步里到next，直接返回里

**预期结果**
等待2000ms后跳转

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
1、如何是首次进入页面，无法拦截页面进入。但是会劫持生命周期，你可以清楚看到生命周期是否为2s后执行
2、如果是原生返回或者tabbar切换也是无法拦截的，需要你自定义
![QQ截图20201230104547](https://user-images.githubusercontent.com/31280665/103326622-329da080-4a8c-11eb-8fd1-0db41063f759.png)
