### ISSUE TITLE
H5调用uni.navigateBack报错，因内部改写此方法，未传参则报错

### ISSUE THREAD

**Issue by xiaojiangK** [SilurianYang/uni-simple-router#209]
H5调用uni.navigateBack报错，因内部改写此方法，未传参则报错
因此与uView u-navbar返回事件冲突，H5无法返回，希望官方能解决
![image](https://user-images.githubusercontent.com/30304529/103341568-43690900-4ac2-11eb-8af7-711db2e3b166.png)

**Comment by SilurianYang** [comment]
## 1.x 请关闭 `rewriteFun:false` 或者升级到 2.x
```js
const router = new Router({
    h5:{ 
         rewriteFun:false
    }
    routes: [...modules]
});
```
