### ISSUE TITLE
uni-simple-router 2.0.0-beta-6 vue 自身生命周期失效

### ISSUE THREAD

**Issue by MonchiLin** [SilurianYang/uni-simple-router#210]
### 问题描述
运行在微信小程序中

2.0.0-beta-6，2.0.0-beta-5 ，2.0.0-beta-4 这三个版本 vue 自身的生命周期（created, beforeMount, mounted）都没有被执行，我尝试回退到 2.0.0-beta-3 Vue 生命周期是正常的

注：小程序的生命周期是正常的

很抱歉，因为要加班没有时间提供复现 demo，等有空了我会补上

### 环境信息

uni-app v2.9.8
uni-app cli v2.0.0-29820201110001

Environment Info:

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.7.0/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.7.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: Not Found
    Safari: 13.1.3
  npmPackages:
    @dcloudio/types: * => 2.0.17 
    @dcloudio/uni-app-plus: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-cli-shared: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-h5: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-helper-json: * => 1.0.7 
    @dcloudio/uni-migration: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-mp-360: ^2.0.0-alpha-29920201212001 => 2.0.0-alpha-29920201212001 
    @dcloudio/uni-mp-alipay: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-mp-baidu: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-mp-qq: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-mp-vue: ^2.0.0-29320201014001 => 2.0.0-29320201014001 
    @dcloudio/uni-mp-weixin: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-quickapp-native: ^2.0.0-29320201014001 => 2.0.0-29320201014001 
    @dcloudio/uni-quickapp-webview: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-stat: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/uni-template-compiler: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-29820201110001 => 2.0.0-29820201110001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.9 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.9 
    @vue/cli-plugin-babel: ~4.5.9 => 4.5.9 
    @vue/cli-plugin-router:  4.5.9 
    @vue/cli-plugin-typescript: * => 4.5.8 
    @vue/cli-plugin-vuex:  4.5.9 
    @vue/cli-service: ~4.5.9 => 4.5.9 
    @vue/cli-shared-utils:  4.5.9 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.5 => 3.0.5 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.12 => 2.6.12 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.4 (16.0.0-beta.9, 15.9.4)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.12 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.6.0 => 3.6.0 
  npmGlobalPackages:
    @vue/cli: 4.5.8

**Comment by MonchiLin** [comment]
我用这个仓库下面的 /examples/uni-simple-router2.0 测试了一下，发现生命周期是正常的，很奇怪我的项目确实没有执行，我在排查排查

**Comment by SilurianYang** [comment]
是组件下的还是页面下的

**Comment by MonchiLin** [comment]
> 是组件下的还是页面下的

组件和页面页面都不会触发

**Comment by SilurianYang** [comment]
如果短时间无法提供重现 demo ，你可以先使用标准的页面生命周期来来带动组件生命周期。这是最糟糕的做法... 当然你也可以换到 `v2.0.0-beta.2` 之前的版本

**Comment by MonchiLin** [comment]
> 如果短时间无法提供重现 demo ，你可以先使用标准的页面生命周期来来带动组件生命周期。这是最糟糕的做法... 当然你也可以换到 `v2.0.0-beta.2` 之前的版本

是的，我现在还在用 alpha2

**Comment by MonchiLin** [comment]
应该可以通过对比 beta3 和 beta4 来判断是哪里出了问题

**Comment by SilurianYang** [comment]
beta2版本往后，是对除  `beforeCreate` 生命周期以外所有生命周期重写，可能在你项目中有更复杂的场景 或者是启动页带参数？
https://github.com/SilurianYang/uni-simple-router/blob/91c4004132cb483023dc3a71a2fb6133b609d927/src/helpers/mixins.ts#L61-L83

**Comment by SilurianYang** [comment]
是否和这个函数有关系  enterPath 和最后拿到的路径不一致的情况
https://github.com/SilurianYang/uni-simple-router/blob/91c4004132cb483023dc3a71a2fb6133b609d927/src/helpers/utils.ts#L434-L454

**Comment by SilurianYang** [comment]
是否和这个有关系  enterPath 和最后拿到的路径不一致的情况

https://github.com/SilurianYang/uni-simple-router/blob/91c4004132cb483023dc3a71a2fb6133b609d927/src/helpers/utils.ts#L359-L364

https://github.com/SilurianYang/uni-simple-router/blob/91c4004132cb483023dc3a71a2fb6133b609d927/src/helpers/utils.ts#L319-L322

**Comment by MonchiLin** [comment]
好，等过完这几天我在从头排查一下

**Comment by SilurianYang** [comment]
> 好，等过完这几天我在从头排查一下

辛苦了🍻🍻🍻

**Comment by MonchiLin** [comment]
终于找到问题，有些小程序开发工具的版本在 uniapp 启动后，控制台会报一个 “编译失败”，但是页面上部分功能又是可用的，让人看起来编译结果没问题

解决办法就是，清除缓存 -> 清除编译缓存，然后重新编译，如果不行就重启小程序开发者工具。
