### ISSUE TITLE
引入uni-simple-router之后App.vue中的onLaunch等钩子触发不了

### ISSUE THREAD

**Issue by arleyGuoLei** [SilurianYang/uni-simple-router#211]
**问题描述**

如题，测试：微信小程序

uniapp-ts-cli版本，版本：v3+
uni-simple-router: 2.0.0-beta.7

![image](https://user-images.githubusercontent.com/40717741/103442473-6ac20080-4c91-11eb-9c25-06fd80473c2d.png)

- main.ts
![image](https://user-images.githubusercontent.com/40717741/103442488-99d87200-4c91-11eb-8425-c555ff0e09b0.png)

- APP.vue
![image](https://user-images.githubusercontent.com/40717741/103442503-be344e80-4c91-11eb-8de8-e75bfdf701ad.png)

- router.ts
![image](https://user-images.githubusercontent.com/40717741/103442510-cee4c480-4c91-11eb-9754-7e7101bdb54c.png)

**复现步骤**

- 按照：https://hhyang.cn/v2/start/quickstart.html 和 https://hhyang.cn/v2/start/tsUse.html 引入
- 代码如上

```main.ts
// import Vue from 'vue'
// import App from './App.vue'
// import uniClientdb from '@/components/uni-clientdb.vue'
// import { router, RouterMount } from '@/router'

// Vue.use(router)

// Vue.config.productionTip = false
// Vue.component('unicloud-db', uniClientdb)

// const app = new Vue({
//   ...App,
// })

// // #ifdef H5
// RouterMount(app, router, '#app')
// // #endif

// // #ifndef H5
// app.$mount() //为了兼容小程序及app端必须这样写才有效果
// // #endif

import Vue from 'vue'
import App from './App.vue'
import { router, RouterMount } from './router'

Vue.use(router)

// import VConsole from 'vconsole'
// var vConsole = new VConsole();

App.mpType = 'app'

// Vue.mixin({
// 	onShow(){
// 		if(this._uid!=0){
// 			router.forceGuardEach()
// 		}
// 	}
// })

//console.log(__uniRoutes)

const app = new Vue({
  ...App,
})

//v1.3.5起 H5端 你应该去除原有的app.$mount();使用路由自带的渲染方式
// #ifdef H5
RouterMount(app, router, '#app')
// #endif

// #ifndef H5
app.$mount() //为了兼容小程序及app端必须这样写才有效果
// #endif

```

```APP.vue
export default Vue.extend({
  mpType: 'app',
  methods: {
  },
  onLaunch() {
    console.log('onLaunch')
  },
})
</script>

```

```router.ts
import { RouterMount, createRouter } from 'uni-simple-router'

const router = createRouter({
  platform: process.env.VUE_APP_PLATFORM,
  keepUniOriginNav: false,
  routes: [...ROUTES],
})

router.beforeEach((to, from, next) => {
  console.log('beforeEach', to)

  next()
})
router.afterEach((to, from) => {
  console.log('跳转结束')
})

export { router, RouterMount }
```

**预期结果**

    console.log('onLaunch')

**实际结果**

未执行

**补充信息**
注释了main.ts中的 Vue.use(router) 后就可以执行

**Comment by arleyGuoLei** [comment]
参照：https://github.com/SilurianYang/uni-simple-router/issues/112 未解决

**Comment by arleyGuoLei** [comment]
完全使用https://hhyang.cn/v2/start/tsUse.html中的代码也不会执行，怀疑是不是和v3版本cli有冲突

**Comment by arleyGuoLei** [comment]
![image](https://user-images.githubusercontent.com/40717741/103449520-362b6480-4ce4-11eb-91b0-7e91e146c1c1.png)

这样解决了

**Comment by SilurianYang** [comment]
app.vue 不要使用 继承的方式  像文档上的写法
![QQ截图20210102102630](https://user-images.githubusercontent.com/31280665/103449575-003ab000-4ce5-11eb-9eb9-20f50f011c10.png)
