### ISSUE TITLE
跳转方式用的不对，app就会卡死，或者在tabBar页面，没有push页面时，按android实体返回键，app也会直接卡死，跳转其他页面无反应。

### ISSUE THREAD

**Issue by yuyuea** [SilurianYang/uni-simple-router#213]
**问题描述**
[将插件引入成功后，打包成app，只要页面里有js报错，或者跳转方式用的不对，app就会卡死，或者在tabBar页面，没有push页面时，按android实体返回键，会保不存在页面栈，level为1，app也会直接卡死，跳转其他页面无反应。]

**复现步骤**
[复现问题的步骤]
1. 启动 '打包app启动后'
2. 点击  '触摸android实体返回按钮，点击其他tabBar页面，或者其他跳转按钮，app无反应了'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[报错提示是挺好的，但是不要让app直接卡死，这样会导致app直接用不了！！！]

**实际结果**
[在tabBar页面，之前没有页面push前，触摸实体返回按键，app直接卡死，跳转其他页面无效！！！在uniapp手机调试控制台输出“当前页面栈不存在，level为1...”、“页面正在跳转中，请稍后再试”]

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [Android 9.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [小米6]
 - uni-simple-router版本 [alpha]

**补充信息**
[可选]
[因为app的页面有些是之前vue项目写的，引入时想找个兼容vue-router用法的插件，修改的的工作量就会小些，引入之后觉得挺好用的，由于上面说的app卡死问题直接导致用不了，无奈把跳转方式又改回uniapp的跳转～ ～]

**Comment by SilurianYang** [comment]
既然有这样的主动提示，肯定会有相应的解决方案。你要相信这个插件不止一个人在用。这时细心的你应该去查阅文档、发现【[跳转路由锁](https://hhyang.cn/v2/start/cross/navLock.html)】【[退出应用](https://hhyang.cn/v2/start/app/runtimequit.html)】【[routerErrorEach](https://hhyang.cn/v2/api/routerInsatll.html#routererroreach-v-2-0-0)】这些都和我出现的报错相关，尝试解决下。

```js 
// 这是安卓退出应用的解决方案
const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	routerErrorEach:({type,msg})=>{
		console.log({type,msg});    //记得要打印，不然报错信息传递到这个方法后没输出。你会懵逼
		// #ifdef APP-PLUS
			if(type===3){
				router.$lockStatus=false;
				runtimeQuit();
			}
		// #endif
	},
	routes: [...ROUTES]
});

// 这是 routerErrorEach 其他报错时需要解锁的方案

// ..... .....   自己尝试实现一下
```

**Comment by yuyuea** [comment]
感谢大佬解惑，我再试试，我看过几遍文档，没想到能这么处理，时间有点紧，所以先稳一手改回去了～
