### ISSUE TITLE
使用uni-simple-router后tabbar消失了

### ISSUE THREAD

**Issue by act2009** [SilurianYang/uni-simple-router#214]
**问题描述**
按照安装步骤安装，然后自动读取 pages.json 作为路由表，样式没有显示出来，比如底部原生tabbar 没有了，顶部搜索框宽度变了，页面顶部标题不显示等

**复现步骤**
按官方文档安装，会出现h5页面白屏无报错，后参考[uniapp H5使用uni-simple-router完全使用vue-router开发 Demo](https://blog.csdn.net/qq_43194650/article/details/111170844) 这篇文章，在App.vue页面多加了下面的代码，其他的和官方一样
```
<template>
	<view>
		<router-view></router-view>
	</view>
</template>
```

[或者可以直接贴源代码]
项目结构：
![image](https://user-images.githubusercontent.com/48006419/103980694-5020e780-51bb-11eb-9847-2b6b8e4c0e17.png)

**pages.json：**
![image](https://user-images.githubusercontent.com/48006419/103980742-6af35c00-51bb-11eb-8b8b-c0b2443688b3.png)
**main.js：**
![image](https://user-images.githubusercontent.com/48006419/103980772-7cd4ff00-51bb-11eb-95d3-26e7fa03bfd9.png)
**vue.config.js：**
![image](https://user-images.githubusercontent.com/48006419/103980826-96764680-51bb-11eb-84a7-cbe0891189ac.png)
**index.js：**
![image](https://user-images.githubusercontent.com/48006419/103980929-c3c2f480-51bb-11eb-9883-49e29265e73d.png)

**App.vue：**
![image](https://user-images.githubusercontent.com/48006419/103981046-f53bc000-51bb-11eb-962e-d586e61487ea.png)

**预期结果**

**实际结果**
页面可以运行成功，但是样式发生了改变，底部tabbar导航栏不显示了 ，每个页面标题没有了

![image](https://user-images.githubusercontent.com/48006419/103979299-7b560780-51b8-11eb-815e-abef60aaaf4a.png)

头部无标题：
![image](https://user-images.githubusercontent.com/48006419/103980547-06d09800-51bb-11eb-8bf7-719e8dfde633.png)

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [无]
 - HBuilderX版本 [HBuilderX3.0.5.20210107]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [无]
 - uni-simple-router版本 [v1.5.5]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
pages.json style配置没有读取成功或者其他的配置问题

**Comment by SilurianYang** [comment]
不是 完全使用vue-router 开发模式不要去配置 。 其次 1.x 的版本首页只能通过/访问 解决办法：你可以使用重定向或者2.x来避免这个问题
``js
<router-view></router-view> 
```

**Comment by act2009** [comment]
> 不是 完全使用vue-router 开发模式不要去配置 。 其次 1.x 的版本首页只能通过/访问 解决办法：你可以使用重定向或者2.x来避免这个问题
> 
> ```js
> <router-view></router-view> 
> ```

使用2.x版本的会报错，提示找不到ROUTES,
![image](https://user-images.githubusercontent.com/48006419/103995872-02fd3f80-51d4-11eb-92a6-c09386407dc3.png)

![image](https://user-images.githubusercontent.com/48006419/103995913-11e3f200-51d4-11eb-8d6f-52d2341d4621.png)

我的项目使用HBuilderX创建的一个新的uniapp项目，我是按文档一步一步操作的，是还需要安装什么吗？

**Comment by SilurianYang** [comment]
`2.x` 快速上手就三步  细心的你应该再对比下 文档

**Comment by act2009** [comment]
> `2.x` 快速上手就三步 细心的你应该再对比下 文档

非常抱歉=。=，我自己检查了一下，之前没有装webpack，报错了也是这个原因，npm install webpack 就正常运行了

安装2.x版本后tabbar样式和标题都正常了，非常感谢作者的回复，快速的解决了问题

**Comment by SilurianYang** [comment]
👍
