### ISSUE TITLE
App端点击tabbar页面不跳转

### ISSUE THREAD

**Issue by wgbx** [SilurianYang/uni-simple-router#216]
**问题描述**
问题描述：配置uni-simple-router，在H5端一切正常，在App端真机调试时，其他页面都可正常拦截跳转但点击tabbar时触发条件应跳转时不跳转，比如我在钩子前置判断登录信息，登录即触发next()，未登录跳转，使用uni.navigateTo跳转到登录页面时，App端报错 {"type":2,"msg":"当前页面正在处于跳转状态，请稍后再进行跳转...."}，但实际页面未跳转

**预期结果**
希望跳转到登录页面

**实际结果**
 {"type":2,"msg":"当前页面正在处于跳转状态，请稍后再进行跳转...."}
页面未跳转

**系统信息:**
 - 发行平台: H5平台、App
 - 操作系统 Android 10.0
 - HBuilderX版本HBuilderX 3.0.5.20210107
 - 项目创建方法 HBuilderX
 - 设备信息 xaiomi9
 - uni-simple-router版本 2.0.0-beta.8

**补充信息**
[可选]
next()正常，在App端使用uni-simple-router，是否不支持uni.navigateTo跳转页面？

**Comment by SilurianYang** [comment]
跳转类型对不？ tab 应该使用  `uni.switchTab(OBJECT)` 是否重复跳转？

**Comment by wgbx** [comment]
@SilurianYang 对的，H5端是一切正常的，只是在App端不太正常，不太可能存在方法错误的问题，所以这个错误提示是表明这个页面处在跳转中的状态，但还未跳转完成是吗？

**Comment by SilurianYang** [comment]
路由守卫下 重定向请使用 next 不要用实例

**Comment by wgbx** [comment]
@SilurianYang 在添加NAVTYPE成功得到预期结果，为我的不严谨抱歉，最后感谢你提供这个库
