### ISSUE TITLE
微信小程序在点击事件中调用this.$Router.replace()后页面未跳转【2.0.0-beta.8】

### ISSUE THREAD

**Issue by WangEn** [SilurianYang/uni-simple-router#217]
**问题描述**
微信小程序开发者工具，通过自定义编译模式直接启动打开内部页面【正常】
通过点击事件触发，调用this.$Router.replace({name: 'home'})页面未跳转（打印日志中路由拦截函数正常执行执行）

**复现步骤**
[复现问题的步骤]
1. 启动微信开发者工具
2. 自定义编译模式，打开内部页面
3. 点击页面按钮，触发返回事件goBack()
4. 路由事件正常触发，但是页面未跳转

[或者可以直接贴源代码]
```
goBack() {
  // test 01
  // this.$Router.replace({name: 'channel'})
  // test 02
  // try{
  // 	this.$Router.back()
  // }catch(e){
  // 	//TODO handle the exception
  // 	this.$Router.replace({name: 'channel'})
  // }
  return;
  if (!this.isOnShelf) {
  uni.showModal({
	  title: '提示',
	  content: '是否加入书架？',
	  success: res => {
		  if (res.confirm) {
			  console.log('用户点击确定');
			  this.addBookShelf();
			  setTimeout(() => {
				  uni.navigateBack();
			  }, 500);
		  } else if (res.cancel) {
			  console.log('用户点击取消');
			  // test 03
			  // this.$Router.replace({name: 'channel'})
			  // test 04
			  try{
				  this.$Router.back()
			  }catch(e){
				  //TODO handle the exception
				  this.$Router.replace({name: 'channel'})
			  }
			  // uni.navigateBack();
		  }
	  }
  });
  return false;
  }
  uni.navigateBack();
}
```

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/12842804/104153131-84dfa980-541c-11eb-9aa1-22b23a0686f2.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 微信开发者工具
 - HBuilderX版本 3.0.5.20210107
 - 项目创建方法 HBuilderX
 - 设备信息 macOS 10.15.7 
 - uni-simple-router版本 2.0.0-beta.8

**Comment by SilurianYang** [comment]
像这种情况很简答定位问题在哪里，首先小程序、app都有强制的规定那就是 [NAVTYPE](https://hhyang.cn/v2/api/routerInsatll.html#navtype-v-1-1-0) 。看截图所有的守卫都正常，多半是跳转类型不对  你可以检测下守卫下是否有使用重定向等相关的 [NAVTYPE](https://hhyang.cn/v2/api/routerInsatll.html#navtype-v-1-1-0)

**Comment by WangEn** [comment]
> 像这种情况很简答定位问题在哪里，首先小程序、app都有强制的规定那就是 [NAVTYPE](https://hhyang.cn/v2/api/routerInsatll.html#navtype-v-1-1-0) 。看截图所有的守卫都正常，多半是跳转类型不对 你可以检测下守卫下是否有使用重定向等相关的 [NAVTYPE](https://hhyang.cn/v2/api/routerInsatll.html#navtype-v-1-1-0)

感谢，确实是NAVTYPE类型错误的问题，尴尬了  replace修改为pushTab就可以
