### ISSUE TITLE
正式版什么时候上线

### ISSUE THREAD

**Issue by Corgis** [SilurianYang/uni-simple-router#220]
目前安装的是beta版 能用于生产么？ 正式版合适上线

**Comment by SilurianYang** [comment]
很抱歉 因为这个项目由我一个人开发，测试和开发多端需要大量的时间。 最近在忙其他项目，我尽量抽出时间完善已知问题和需要改进的地方就上线正式版。对于生产环境，我建议你在开发环境下测试通过后如果没问题再上线生产环境，有问题也可以及时在github上给我留言

**Comment by Corgis** [comment]
好的 感谢开源贡献，谢谢
