### ISSUE TITLE
页面的onLoad钩子中跳转其他页面报错

### ISSUE THREAD

**Issue by Corgis** [SilurianYang/uni-simple-router#221]
首先十分感谢作者开源贡献

**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
pages.json第一项是个 类型引导的页面，页面代码如下，在onLoad中跳转到首页
onLoad() {
			// uni.switchTab({
			//     url: '/pages/home/index'
			// });
			this.$Router.pushTab({
				name:'home',
				params:{userId:123}
			})
		}
**预期结果**
希望能正常跳转到home页

**实际结果**
停留在了导航页，未能跳转并报错
msg: "当前页面正在处于跳转状态，请稍后再进行跳转...."
type: 2
![image](https://user-images.githubusercontent.com/13865529/104672460-cae98580-571a-11eb-87ee-dc73cc4c56a9.png)

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本：3.0.5.20210107
 - 项目创建方法：HBuilderX
 - uni-simple-router：2.0.0-beta.8

**补充信息**
是否做个类似setTimeout的延时再跳转，还是有其他方法 谢谢

**Comment by SilurianYang** [comment]
2.x 在小程序端会重写启动页所有的生命周期，当执行到onload 、onShow、等等 生命周期的时候`$lockStatus` 状态是为 `true`。所有你再跳转的时候会提示正在跳转中，你应该放在 `beforeEach`、`routerBeforeEach` 等守卫下跳转就不会有这样的提示啦。或者你也可以[暴力解锁](https://hhyang.cn/v2/start/cross/navLock.html)

**Comment by Corgis** [comment]
好的了解了 谢谢
