### ISSUE TITLE
微信浏览器ios从第三方网页返回白屏

### ISSUE THREAD

**Issue by strivefighting** [SilurianYang/uni-simple-router#222]
**问题描述**
微信浏览器ios从第三方网页返回白屏

**复现步骤**
[复现问题的步骤]
1. h5某页面
2. 点击 跳转到第三方页面
3. ios返回键返回到项目中

[或者可以直接贴源代码]

**预期结果**
项目页面正常显示

**实际结果**
白屏，查看元素已经渲染

**系统信息:**
 - 发行平台: H5平台]
 - 操作系统 [如 iOS 14.3]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [Vue-cli创建]
 - 设备信息 [如 iPhone6，8等]
 - uni-simple-router版本 [v1.5.5]

**Comment by SilurianYang** [comment]
1.x 的版本看这个[解决方法](https://github.com/SilurianYang/uni-simple-router/issues/109)。2.x 请直接升级到最新版解决
