### ISSUE TITLE
全局前置守卫 next跳转带参数 到目标页面的onLoad拿不到数据

### ISSUE THREAD

**Issue by Corgis** [SilurianYang/uni-simple-router#223]
**问题描述**
全局前置守卫 next跳转带参数 到目标页面的onLoad拿不到数据

**复现步骤**
 ------------router.js-------------
router.beforeEach((to, from, next) => {
	if(to.name === 'index'){
		next({name:'home',params:{userId:123},NAVTYPE: 'pushTab'})
	}else{
		next()
	}
});
------------home.vue---------------
onLoad(...options){
	console.log(options)
	console.log(this.$Route)
},

**预期结果**
能拿到 params参数中的userId

**实际结果**
目前为空
提示：VM806 WAService.js:2 wx.switchTab: url 不支持 queryString

**系统信息:**
-发行平台: 微信小程序
-HBuilderX版本：3.0.5.20210107
-项目创建方法：HBuilderX
-uni-simple-router：2.0.0-beta.8

**Comment by SilurianYang** [comment]
`pushTab` 在各个小程序端都有明确的规定，不支持传递参数。具体你可以在编译到端后看对应端的官方文档。其次你可以换个方式传参 本地储存获取 vuex 等等 很多方式

**Comment by Corgis** [comment]
好的好的 了解了
