### ISSUE TITLE
微信工具新增一个编译模式，模拟分享某个tabbar页面 用户点击进入的场景，onLoad onShow 顺序错乱问题

### ISSUE THREAD

**Issue by Corgis** [SilurianYang/uni-simple-router#224]
**问题描述**
模拟分享某个tabbar页面 用户点击进入的场景，从代码的debugger看 是先进入onShow再进入了onLoad，本以为是uni的问题，测试了不使用您的该路由库 表现是正常的

**复现步骤**
onLoad(){
	debugger
	console.log(this.$Route)
	console.log(this.name,'我是onLoad')
},
onShow(){
	debugger
	console.log(vm.name,'我是onShow')
},

**预期结果**
先进入onLoad的代码块 再进入 onShow的代码块

**实际结果**
与以上期望刚好相反

**系统信息:**
 -发行平台: 微信小程序
-HBuilderX版本：3.0.5.20210107
-项目创建方法：HBuilderX
-uni-simple-router：2.0.0-beta.8

**Comment by SilurianYang** [comment]
看这个 https://github.com/SilurianYang/uni-simple-router/issues/206

**Comment by Corgis** [comment]
> 看这个 #206
首先感谢大佬利用空余时间，做开源库，方便了使用uniapp的小伙伴，
关于206的回复我大致看了 也了解了，那我有个以下的疑问
关于this.$Route 我调试发现  不止于在onLoad周期里拿，在onShow的周期里也能拿到是吧

**Comment by SilurianYang** [comment]
除去uni-app非标准页面生命周期意外所有都能拿到
