### ISSUE TITLE
原生tabbar 配置list 后 登录成功  显示 跳转完成 但页面没有跳转

### ISSUE THREAD

**Issue by wz-hub** [SilurianYang/uni-simple-router#226]
**问题描述**
原生tabbar 配置list 后 登录成功  显示 跳转完成 但页面没有跳转

**复现步骤**
1. 启动 'npm  install'
2. 点击  '登录 —— 登录成功 获取到 token 但是 不跳转到 首页当获取到token 存到 本地后 进入项目有 可以直接进入首页'
3. 查看

**系统信息:**
 - 发行平台: [ 微信小程序       Android App]
 - 操作系统 [win10 微信开发者程序、Android 10.0]
 - HBuilderX版本 [3.0.5.20210107]
 - 项目创建方法 [HBuilderX]

 - uni-simple-router版本 [2.0.8]

**补充信息**
[可选]
[next() 跳转到 tabar有问题？]
demo : [demo](https://github.com/wz-hub/uniapp_framework)

**Comment by SilurianYang** [comment]
![Snipaste_2021-01-20_15-28-14](https://user-images.githubusercontent.com/31280665/105141673-76884080-5b34-11eb-8fa2-5b7b49e3291b.png)
原生tab 请使用 `pushTab` 跳转，另外

![Snipaste_2021-01-20_15-28-04](https://user-images.githubusercontent.com/31280665/105141666-72f4b980-5b34-11eb-8280-250aaf87fcef.png)
