### ISSUE TITLE
组件式导航 解析参数时出错

### ISSUE THREAD

**Issue by k99k5** [SilurianYang/uni-simple-router#227]
组件式导航 解析参数时出错

**复现步骤**
`{name:'商品列表页',params:{tags:'1599,1624',on_sale:true,orderby:'rand'}}`
会解析成 `{"name":"商品列表页","params":{"tags":"1599",1624,"on_sale":"true","orderby":"rand"}}`

**预期结果**

**实际结果**
Error: {"name":"商品列表页","params":{"tags":"1599",1624,"on_sale":"true","orderby":"rand"}} 路径无法在路由表中找到！检查跳转路径及路由表

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
等我验证

**Comment by SilurianYang** [comment]
你可以先暂时使用编程式路由过渡下，简单正则是已英文逗号分隔 可以不包含引号。宽松模式下 多个逗号无法分隔所以不能转成json   最后把他当前一个路径处理了。

**Comment by SilurianYang** [comment]
这个短时间不会修复   请使用编程式传递

**Comment by SilurianYang** [comment]
### 请尝试 [2.0.8-beta.2](https://www.npmjs.com/package/uni-simple-router/v/2.0.8-beta.2)
