### ISSUE TITLE
微信小程序设置next(false)，未中断当前导航

### ISSUE THREAD

**Issue by maoyuxuan** [SilurianYang/uni-simple-router#228]
**问题描述**
[问题描述：微信小程序新版2.0 next(false)，没有中断当前导航

**复现步骤**
[复现问题的步骤]
设置next(false)后，第一次点击提示导航终止，第二次点击提示还在跳转中。

**预期结果**
设置next(false)后，导航终止

**实际结果**
设置next(false)后，导航未终止，提示还在跳转中。

**系统信息:**
 - 发行平台: [微信小程序]
 - HBuilderX版本 [3.0.7.20210123]
 - uni-simple-router版本 [如 v2.0.0-beta.8]

**Comment by SilurianYang** [comment]
针对 `type：0`  的情况进行解锁    [相关文档地址](https://hhyang.cn/v2/start/cross/navLock.html)

**Comment by SilurianYang** [comment]
有问题再打开issue  我暂时先关闭了
