### ISSUE TITLE
报错：当前页面正在处于跳转状态,请稍后再进行跳转....

### ISSUE THREAD

**Issue by lijun4639** [SilurianYang/uni-simple-router#230]
**问题描述**
偶尔出现报错 msg：当前页面正在处于跳转状态,请稍后再进行跳转....

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 3.0.7.20210123
 - 项目创建方法 HBuilderX
 - 设备信息 微信小程序调试工具、华为mate40 Pro
 - uni-simple-router版本 2.0.0-beta.8

**Comment by SilurianYang** [comment]
跳转锁 问题 ，在短时间内重复跳转就会出现这个提示 。  你也可以通过 [文档了解更多](https://hhyang.cn/v2/start/cross/navLock.html) `routerErrorEach` 记得在这个函数中进行错误打印。

* 路由守卫下是使用 `next` 重定向
* 避免多次重复跳转
