### ISSUE TITLE
在使用uni-read-pages的情况下，如何修改router对象

### ISSUE THREAD

**Issue by NoraGithub** [SilurianYang/uni-simple-router#231]
**问题描述**
使用uni-read-pages自动构建路由表。这种情况下，h5平台下希望修改每个路由的beforeEnter钩子会失效。

```javascript
import Vue from 'vue'
import Router, {RouterMount} from 'uni-simple-router'
import store from '../store'

Vue.use(Router)



//初始化
for (let route of ROUTES) {
  route.beforeEnter = requireAuth(store)
}
const router = new Router({
  routes: ROUTES
  //routes: [...modules]//路由表
})

export function requireAuth(store) {
 ...
}



//全局路由前置守卫
router.beforeEach((to, from, next) => {
  next()
})
// 全局路由后置守卫
router.afterEach((to, from) => {
})
export default router
```

**复现步骤**

 console.log 可见。

[或者可以直接贴源代码]

**预期结果**
发生调用

**实际结果**
不执行，所以没有结果。

**系统信息:**

h5平台，vue-cli创建，uni-simple-router 1.5.5版本

**补充信息**

分析不到，我在正常的vue项目是这样子写的，感觉和uni-read-page可能有关。我不知道router是什么时候注入vue了，目前。

**Comment by SilurianYang** [comment]
```js
const mapEnters=ROUTES.map(it=>{
	it.beforeEnter=function(){
		console.log('beforeEnter')
	}
	return it;
})

console.log(ROUTES)
console.log(mapEnters)
```

**Comment by NoraGithub** [comment]
> ```js
> const mapEnters=ROUTES.map(it=>{
> 	it.beforeEnter=function(){
> 		console.log('beforeEnter')
> 	}
> 	return it;
> })
> 
> console.log(ROUTES)
> console.log(mapEnters)
> ```

相当于不能直接修改默认生成ROUTES数组，只能新建是么。
