### ISSUE TITLE
当页面栈到四级时，无法正常跳转

### ISSUE THREAD

**Issue by lazy-bum** [SilurianYang/uni-simple-router#233]
**问题描述**
安卓APP运行到设备当页面栈到四级时，无法正常跳转

**复现步骤**
页面栈到四级时调用$Router.push 或者 back()

**预期结果**
可以正常跳转

**实际结果**
无法正常跳转，提示{"type":2,"msg":"当前页面正在处于跳转状态，请稍后再进行跳转...."} 

**系统信息:**
 - 发行平台: Android APP
 - 操作系统 Android 9
 - HBuilderX版本 3.0.7
 - 项目创建方法 HBuilderX创建 yarn 安装
 - 设备信息 HONOR 9X PRO
 - uni-simple-router版本 2.x

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
[uni-simple-router2.0.zip](https://github.com/SilurianYang/uni-simple-router/files/5904802/uni-simple-router2.0.zip)

tab页点去page2  然后再点去link组件 然后随便点  你试试

**Comment by SilurianYang** [comment]
是不是 小程序端 页面层级限制   你排除下

**Comment by SilurianYang** [comment]
有任何情况请重新打开，先关闭了
