### ISSUE TITLE
首屏启动为 nvue时不能使用uni-simple-router的原因是什么

### ISSUE THREAD

**Issue by wgbx** [SilurianYang/uni-simple-router#234]
我有注意到 “首屏启动为 nvue 插件无效，会报错！必须使用 vue 作为启动页。”这个提示

但由于项目的首页的确是需要采用nvue来做性能优化，所以想请教下首屏启动为 nvue时不能使用uni-simple-router的原因是什么

因为并没有读源码，可能答案会有点过于简单？

**Comment by SilurianYang** [comment]
主要是在启动页做了生命周期劫持   nvue 无法劫持生命周期  所有无法保证执行运行   你其他页面用nvue 就好了呀。再说你可以在不改动结构的情况下解决此问题，你在`pages.json` 下编译一个针对app的vue空白过渡页面  然后再路由守卫下重定向到nvue首页就好。

**Comment by wgbx** [comment]
当时预想的方案差不多就是这种，只是比较好奇原因，感谢解答
