### ISSUE TITLE
uni.createCanvasContext 无法使用

### ISSUE THREAD

**Issue by ForeverZhong** [SilurianYang/uni-simple-router#235]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
h5端，完全H5模式，uni.createCanvasContext 无法使用。会报错。看社区没看到别人有这个情况，是只有我遇到嘛？

**Comment by SilurianYang** [comment]
完全使用h5模式  大部分的 uni-app  api都不能使用  因为是完全自定义的组件页面  不包含任何uni-app注入的事件或者组件
