### ISSUE TITLE
命名式导航，URL并未预期加上query参数

### ISSUE THREAD

**Issue by buqiyuan** [SilurianYang/uni-simple-router#236]
**问题描述**
编程式导航时，传递过去的参数并未预期在地址栏显示，刷新页面后就拿不到query参数了

[或者可以直接贴源代码]
![image](https://user-images.githubusercontent.com/39730999/108050271-5ccf1000-7084-11eb-8556-111b42f5a48b.png)

**预期结果**
![image](https://user-images.githubusercontent.com/39730999/108050304-66f10e80-7084-11eb-989b-88615f153ac8.png)

希望query能在地址栏显示，刷新页面后依然存在。

**实际结果**
![image](https://user-images.githubusercontent.com/39730999/108049786-acf9a280-7083-11eb-9127-4575c5e18742.png)

**系统信息:**
 - 发行平台: [H5平台]
 - HBuilderX版本 [3.1.2]
 - 项目创建方法 [Vue-cli创建]
 - uni-simple-router版本 [2.0.0-beta.11]

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/108051850-56da2e80-7086-11eb-81b2-9f290de5071f.png)


使用动态路由参数倒是可以正常加上，使用query不可以

**Comment by SilurianYang** [comment]
1. 这里是帮你百度的为啥 `params` 参数会消失的文章
  * https://zhuanlan.zhihu.com/p/139114628
  * https://segmentfault.com/a/1190000012735168

2. 如果你想在使用 `name+params` 的跳转方式下让参数显示，插件为你提供了一个配置参数  [看文档这里](https://hhyang.cn/v2/api/routerInsatll.html#h5) 

``` js
// 2.x 版本的配置方法，具体看文档
const router = createRouter({
	// .....
	h5:{
              paramsToQuery:true
        }
});
```

**Comment by buqiyuan** [comment]
噢噢，可以了，感谢大佬，原来还要在配置里开启这个参数啊
