### ISSUE TITLE
在page.json中设置animation无效

### ISSUE THREAD

**Issue by Tron1234** [SilurianYang/uni-simple-router#238]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
在page.json中设置animation无效，在路由表中也设置无效，但在路由配置文件中设置有效，使用uni.navigateTo携带animationType也有效

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看
无效截图
![image](https://user-images.githubusercontent.com/47961959/109275538-d8347c80-784f-11eb-99c8-110befc11590.png)
![image](https://user-images.githubusercontent.com/47961959/109275696-0c0fa200-7850-11eb-960a-d387b807a542.png)
有效截图
![image](https://user-images.githubusercontent.com/47961959/109275888-51cc6a80-7850-11eb-9dba-53cdcec1f77d.png)

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
动画有效

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
待验证

**Comment by Tron1234** [comment]
下方是我上传的一个demo

**Comment by Tron1234** [comment]
https://cowtransfer.com/s/7c294fda1c0249

**Comment by SilurianYang** [comment]
### dev 分支已修复
