### ISSUE TITLE
求新增【H5路由跳转进度条】样式配置的方法

### ISSUE THREAD

**Issue by tanranran** [SilurianYang/uni-simple-router#24]
1、首先在这里感谢作者，这个真的是用过的最好用的uni路由

PS：看了下源码 进度条的配置是写死在h5-dom.js中的，迫于为了以后的更新（不想改源码，不想用!important 强改 ），希望作者能新增这方面的配置方法。

**Comment by SilurianYang** [comment]
这是一个非常不出的建议  后续版本会添加上
