### ISSUE TITLE
events在h5中不生效，在小程序中是可以的

### ISSUE THREAD

**Issue by lazyyou** [SilurianYang/uni-simple-router#240]
**问题描述**
events在h5中不生效，在小程序中是可以的

**复现步骤**
`
// page0.vue
  this.$Router.push({
      name: 'page1',
      events: {
          acceptDataFromOpenedPage: function (data) {
              console.log(data)
          },
      },
  });

// page1.vue
onLoad(options){			
          const eventChannel = this.getOpenerEventChannel()
          eventChannel.emit('acceptDataFromOpenedPage', {data: 'test'});
},
`

**系统信息:**
 - uni-simple-router版本 [v2.0.0-beta.8]

**Comment by SilurianYang** [comment]
h5使用了非uni的跳转导致了`events`丢失

**Comment by SilurianYang** [comment]
### dev 分支已修复 

### [测试页面](https://github.com/SilurianYang/uni-simple-router/blob/dev/examples/uni-simple-router2.0/pages/events/events.vue)

https://github.com/SilurianYang/uni-simple-router/blob/42a67dfde064836d7009cf3f599651cfd583bd6d/src/public/methods.ts#L88-L97
