### ISSUE TITLE
beforeRouteLeave的bug

### ISSUE THREAD

**Issue by Tron1234** [SilurianYang/uni-simple-router#241]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
依旧是页面跳转的导致beforeRouteLeave失效的bug

**复现步骤**
[复现问题的步骤]

当A页面跳转到B页面，B页面跳转到C页面，B页面中有beforeRouteLeave方法限制B页面不能跳回A页面，当从C页面返回B页面，B页面返回A页面只会触发一次beforeRouteLeave，再次点击返回则不会触发beforeRouteLeave，直接返回A页面了

1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
[test.zip](https://github.com/SilurianYang/uni-simple-router/files/6087742/test.zip)
npm install一下

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

每次从B返回A都会触发beforeRouteLeave，并且受到限制B不能返回A
![6296d918-ac3e-48fb-90c5-3d24c9cfc378](https://user-images.githubusercontent.com/47961959/110057300-571f3d00-7d9b-11eb-95e4-023c037e866f.gif)
![8ec8a93d-4119-4355-aa61-5eed520777d5](https://user-images.githubusercontent.com/47961959/110057505-ad8c7b80-7d9b-11eb-9341-7bc3e834d519.gif)

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
### h5端bug

#### 出现原因
* next(false)  后导致 getCurrentPages 或者的栈丢失，无法找到当前页面。导致二次无法执行  beforeRouteLeave

**Comment by Tron1234** [comment]
app端经测试正常

**Comment by SilurianYang** [comment]
### dev 分支已修复 

https://github.com/SilurianYang/uni-simple-router/blob/a118614b82c52c6d4bc0d5c410f3eb316780914e/src/H5/proxyHook.ts#L22-L31

**Comment by Tron1234** [comment]
大佬准备 什么时候发beta12?

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/240 修复完成后，再加个功能就发布。如果你比较着急，可以把dev分支拉下来，然后自行build一个新的版本就好了

**Comment by Tron1234** [comment]
好的谢谢大佬
