### ISSUE TITLE
h5 项目页面刷新后的执行方法

### ISSUE THREAD

**Issue by huchenghua** [SilurianYang/uni-simple-router#244]
**问题描述**
h5项目进入的时候 三个方法没有正常执行

**复现步骤**
[复现问题的步骤]

![image](https://user-images.githubusercontent.com/6287527/110413207-6e766700-80c8-11eb-8d5a-25d7c9d5ba1b.png)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
想三个函数都执行的

**实际结果**
[这里请贴上你的报错截图或文字]
第一次进入就执行了2个
![image](https://user-images.githubusercontent.com/6287527/110413697-4b988280-80c9-11eb-8d79-38bb04748a63.png)

刷新一下,一个都没有输出,都没有执行

**系统信息:**
 - 发行平台:  钉钉H5平台
 - 操作系统 win10
 - HBuilderX版本   3.1.4.20210305
 - 项目创建方法 使用Vue-cli创建/HBuilderX 
 - 设备信息  mate20
 - uni-simple-router版本  v1.5.5

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
能否提供一个demo

**Comment by huchenghua** [comment]
升级2.0  没有出现了
