### ISSUE TITLE
vueRouterDev: true 导致打包不会分割代码

### ISSUE THREAD

**Issue by CChiaki** [SilurianYang/uni-simple-router#246]
`
const router = new Router({
	h5: {
		vueRouterDev: true
	},
	routes: rolesRouters.concat(defaultRouter),
});
`

设置了 vueRouterDev 后打包不会分割

**Comment by SilurianYang** [comment]
类似这样的配置？最终打包没切割吗？
```js
import('./Foo.vue')
```

**Comment by CChiaki** [comment]
是的 ：我贴下代码：
`
export const defaultRouter = [{
	path: '/login',
	component: () => import('@/pages/login.vue'),
	name: 'login',
	meta: {
		title: '用户登录'
	}
}]

const router = new Router({
	h5: {
		vueRouterDev: true
	},
	routes: rolesRouters.concat(defaultRouter),
});
`


`
import Home from '@/pages/home.vue'
const router = [{
	path: '/',
	component: Home,
	name: 'index',
	meta: {
		title: '',
		icon: ''
	},
	children: [{
		path: '/',
		meta: {
			title: '首页',
			icon: "el-icon-monitor"
		},
		component: () => import("@/pages/index/index.vue"),
	}]
}];
`

**Comment by CChiaki** [comment]
但是我的pages.json 里面 没有配置pages 

```
{
	"pages": [ //pages数组中第一项表示应用启动页，参考：https://uniapp.dcloud.io/collocation/pages
		{
			"path": "pages/index/index",
			"style": {
				"navigationBarTitleText": "uni-app"
			}
		}
    ],
	"globalStyle": {
		"navigationBarTextStyle": "black",
		"navigationBarTitleText": "uni-app",
		"navigationBarBackgroundColor": "#F8F8F8",
		"backgroundColor": "#F8F8F8"
	}
}

```

**Comment by SilurianYang** [comment]
看起来`pages` 下的和es6写法有点冲突，换个写法效果一样。

```js
const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,
	h5: {
		vueRouterDev: true
	},
	routes: [{
		"path": "/",
		component: resolve => require(['@/pages/layout/layout.vue'], resolve),
		redirect: '/index',
		children: [{
				"path": "/index",
				component: resolve => require(['@/pages/index/index.vue'], resolve)
			},
			{
				"path": "/pages/basics/layout",
				component: resolve => require(['@/pages/basics/layout.vue'], resolve)
			}
		]
	}, ]
});
```
[vueRouterDevDemo.zip](https://github.com/SilurianYang/uni-simple-router/files/6146861/vueRouterDevDemo.zip)

**Comment by TeaGardenia** [comment]
那种方式懒加载 是正确的？
`
import index1 from "@/pages/index/index1.vue"
const index2 = () => import('@/pages/index/index2.vue');

const modules = [{
	path: "/",
	component: resolve => require(['@/pages/index/index.vue'], resolve),
	redirect: '/pages/index/index1',
	children: [{
			path: "/pages/index/index1",
			component: index1
		},
		{
			path: "/pages/index/index2",
			component: index2
		},
		{
			path: "/pages/index/index3",
			component: () => import('@/pages/index/index3.vue')
		},
		{
			path: "/pages/index/index4",
			component: () => import( /* webpackChunkName: "index" */ '@/pages/index/index4.vue').then(m => m
				.default),
		},
		{
			path: "/pages/index/index5",
			component: resolve => require(['@/pages/index/index5.vue'], resolve),
			meta: {
				need_login: true
			}
		}
	]
}]
`
[Uploading test.zip…]()

**Comment by TeaGardenia** [comment]
`import index1 from "@/pages/index/index1.vue"
const index2 = () => import('@/pages/index/index2.vue');

const modules = [{
	path: "/",
	component: resolve => require(['@/pages/index/index.vue'], resolve),
	redirect: '/pages/index/index1',
	children: [{
			path: "/pages/index/index1",
			component: index1
		},
		{
			path: "/pages/index/index2",
			component: index2
		},
		{
			path: "/pages/index/index3",
			component: () => import('@/pages/index/index3.vue')
		},
		{
			path: "/pages/index/index4",
			component: () => import( /* webpackChunkName: "index" */ '@/pages/index/index4.vue').then(m => m
				.default),
		},
		{
			path: "/pages/index/index5",
			component: resolve => require(['@/pages/index/index5.vue'], resolve),
			meta: {
				need_login: true
			}
		}
	]
}]`
那种方式懒加载 是正确的？
[test.zip](https://github.com/SilurianYang/uni-simple-router/files/6324204/test.zip)

**Comment by TeaGardenia** [comment]
```
import index1 from "@/pages/index/index1.vue"
const index2 = () => import('@/pages/index/index2.vue');

const modules = [{
	path: "/",
	component: resolve => require(['@/pages/index/index.vue'], resolve),
	redirect: '/pages/index/index1',
	children: [{
			path: "/pages/index/index1",
			component: index1
		},
		{
			path: "/pages/index/index2",
			component: index2
		},
		{
			path: "/pages/index/index3",
			component: () => import('@/pages/index/index3.vue')
		},
		{
			path: "/pages/index/index4",
			component: () => import( /* webpackChunkName: "index" */ '@/pages/index/index4.vue').then(m => m
				.default),
		},
		{
			path: "/pages/index/index5",
			component: resolve => require(['@/pages/index/index5.vue'], resolve),
			meta: {
				need_login: true
			}
		}
	]
}]
```
那种赖加载方式 是正确的？ 我这里出现严格模式提示 跳转不到对应的路由
[test.zip](https://github.com/SilurianYang/uni-simple-router/files/6324214/test.zip)
