### ISSUE TITLE
数据解析类型错误

### ISSUE THREAD

**Issue by weiminghaoo** [SilurianYang/uni-simple-router#247]
this.$Router.push({
              name: 'test',
              params: {
                test: 121212
              }
            })

预期
this.$Route.query.test = 121212

实际上
this.$Route.query.test = "121212"

**Comment by SilurianYang** [comment]
单一的字符串不做json处理，你可以把它包成一个深度json，即可还原。例如
```js
this.$Router.push({
    name: 'test',
    params: {
        test:{
            value:111
        }
    }
})
```

**Comment by weiminghaoo** [comment]
> 单一的字符串不做json处理，你可以把它包成一个深度json，即可还原。例如
> 
> ```js
> this.$Router.push({
>     name: 'test',
>     params: {
>         test:{
>             value:111
>         }
>     }
> })
> ```

额 之前用1.x很多处地方都这么用的，这样的话都要改一遍😂

**Comment by SilurianYang** [comment]
1.x 同样也有这样的问题   既然1.x 你没问题 升级到2.x 也一样的   而且 2.x 提供了parseQuery 你可以在这里面实现数据类型转换
