### ISSUE TITLE
集成完成后，点击跳转提示 “已存在待跳转页面”

### ISSUE THREAD

**Issue by silentzone** [SilurianYang/uni-simple-router#248]
**问题描述**
  使用 hello uni-app 的模板工程集成了，uni-simple-router 
 使用基座在手机上测试，点击一个导航，第一次没有反应 第二次提示 
 已存在待跳转页面/pages/component/view/view,请不要连续多次跳转页面/pages/component/scroll-view/scroll-view

 跳转使用的 uni api 的方法 
  uni.navigateTo({  url: url  })

**预期结果**
 成功跳转

**实际结果**
 没反应

**系统信息:**
android 基座

**补充信息**
 nvue路由栈中以及存在一个完成跳转的页面，始终无法被清理

**Comment by SilurianYang** [comment]
路由跳转是否完完？如果没完成，下次再执行任务就会提示请不要重复跳转的警告。请检查路由守卫是否有正确放行

**Comment by silentzone** [comment]
git@github.com:silentzone/test-uni-route.git

**Comment by silentzone** [comment]
路由守卫都没有触发，我全部用的next()

**Comment by SilurianYang** [comment]
我看了下你的配置，首先你选用的是2.0 的插件。却照着1.x的文档配置。这个根本就启动不了，更别说跳转了

**Comment by SilurianYang** [comment]
[test-uni-route.zip](https://github.com/SilurianYang/uni-simple-router/files/6180592/test-uni-route.zip)
这是通过你提交的项目修改的，直接运行即可

**Comment by silentzone** [comment]
对不起我是盲人程序员, 谢谢你大佬

**Comment by silentzone** [comment]
@SilurianYang  首屏启动为 nvue 插件无效，会报错！必须使用 vue 作为启动页,是这个原因对吧
