### ISSUE TITLE
在计算属性中拿$Route.query报错

### ISSUE THREAD

**Issue by WormGirl** [SilurianYang/uni-simple-router#249]
**问题描述**
在计算属性里面返回路由参数为啥报错

```js
computed: {
    query () {
	return this.$Route.query;
    }
}
```
![image](https://user-images.githubusercontent.com/16078260/111989641-00f91a80-8b4d-11eb-90e4-f2834c862ae2.png)

为啥在onLoad生命周期里拿不到options的值

**Comment by SilurianYang** [comment]
是的 ，router 插件和vue内置属性有区别，在编译和挂载时 vue 内置属性都会在相应的位置或者生命周期进行构建。说白了自己家的东西在自己家有位置。我是第三方的没有位置！所以在没有创建组件之前是不能被访问的。你应该在标准的 uni-app 生命周期下获取就行了

**Comment by WormGirl** [comment]
> 是的 ，router 插件和vue内置属性有区别，在编译和挂载时 vue 内置属性都会在相应的位置或者生命周期进行构建。说白了自己家的东西在自己家有位置。我是第三方的没有位置！所以在没有创建组件之前是不能被访问的。你应该在标准的 uni-app 生命周期下获取就行了
我是在onShow里面调用的计算属性的query, 为啥会报错

**Comment by SilurianYang** [comment]
计算属性在onshow 之前执行，而且计算属性它是有缓存的。所以你直接在onshow中执行 ` this.$Route.query` 就好了

**Comment by WormGirl** [comment]
好的，谢谢

**Comment by WormGirl** [comment]
好的，谢谢
