### ISSUE TITLE
百度小程序高基础库版本，初始化获取不到enterPath

### ISSUE THREAD

**Issue by arleyGuoLei** [SilurianYang/uni-simple-router#251]
**问题描述**

百度小程序高基础库版本(如图红色版本)，获取不到enterPath

![image](https://user-images.githubusercontent.com/40717741/112743406-996a2180-8fc9-11eb-8e37-afc5ec442cbf.png)

**复现步骤**

使用2.0.1的包，切换基础库版本至最新
![image](https://user-images.githubusercontent.com/40717741/112743391-78093580-8fc9-11eb-8722-b3b5a7c1708a.png)

**系统信息:**

 - 发行平台: 百度小程序
 - uni-simple-router版本：2.0.1

**补充信息**

新基础库：
![image](https://user-images.githubusercontent.com/40717741/112743426-d504eb80-8fc9-11eb-8980-0451014f4f80.png)

老基础库：
![image](https://user-images.githubusercontent.com/40717741/112743435-e2ba7100-8fc9-11eb-90e5-3b609fbeac6d.png)

~ 辛苦大佬解决一下

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/blob/1628a7530c6134d61ea0eae40be6dc85c5c40c49/src/applets/appletPatch.ts#L13-L16
