### ISSUE TITLE
H5 带参数访问 Tabbar 报告 找不到相关路由表

### ISSUE THREAD

**Issue by haoxf** [SilurianYang/uni-simple-router#252]
**问题描述**
uni-app 原生方法跳转路径为：/pages/tabBar/index/index?query=xxxxx。在路由表中找不到相关路由表！当然你可以通过通配符*解决！

**复现步骤**
[复现问题的步骤]
从其他页面带参数访问Tabbar, 跳转失败

**系统信息:**
 - 发行平台: H5平台
 - 项目创建方法 Vue-cli创建
 - uni-simple-router版本 v2.0.1

**Comment by SilurianYang** [comment]
能打印下你的路由表吗？

**Comment by haoxf** [comment]
> 能打印下你的路由表吗？

路由打印：
  {path: "/pages/tabBar/index/index", name: "index", aliasPath: "/index"}

跳转错误：
  uni-simple-router.js:1 uni-app 原生方法跳转路径为：/index?query=%7B%22a%22%3A%22hello%22%7D。在路由表中找不到相关路由表！当然你可以通过通配符*解决！

特别说明：
* 使用的原生 uni.switchTab 切换, uni-simple-router 只用于实现 aliasPath 功能

**Comment by SilurianYang** [comment]
你可以上传一个demo吗？

**Comment by haoxf** [comment]
重现步骤：
1. 点击中间Tabbar【添加】，进入新页面
2. 从新页面返回，报错



[router-test.zip](https://github.com/SilurianYang/uni-simple-router/files/6270894/router-test.zip)

**Comment by SilurianYang** [comment]
你可以使用 `this.$Router.pushTab('/pages/tabBar/index/index?a=hello')` 代替它

**Comment by haoxf** [comment]
这个暂时无法修复吗？

**Comment by SilurianYang** [comment]
这个需要时间，我这段时间比较忙。如果你急着使用，可以拉取代码，然后自己改改打包成一个新的版本

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/blob/1628a7530c6134d61ea0eae40be6dc85c5c40c49/src/helpers/utils.ts#L123-L130
