### ISSUE TITLE
请问使用了该插件后会影响 微信小程序 onLoad 生命周期的使用吗？

### ISSUE THREAD

**Issue by lwjJoe** [SilurianYang/uni-simple-router#256]
**问题描述**
[问题描述：在编译成微信小程序后，某个页面是从小程序码扫码进入的并且携带参数，这时在 页面onLoad里却接收不到参数了

![image](https://user-images.githubusercontent.com/29138640/115213112-caa2c100-a133-11eb-9de2-75aff38d7d87.png)

**Comment by SilurianYang** [comment]
你试试去掉插件呢？我记得这是官方的bug  你可以用 `this.$Route.query` 获取

**Comment by lwjJoe** [comment]
uniApp 官方BUG？ 还是微信小程序 ？
我使用uniApp提供的demo里是能正常获取的。
this.$Route.query 这个能获取到 小程序码 跳转进来的参数？

**Comment by SilurianYang** [comment]
所有的参数获取都使用 `this.$Route.query` 获取

**Comment by lwjJoe** [comment]
反正目前我这边是没有获取到

**Comment by SilurianYang** [comment]
`this.$Route.query` 也无法获取？ 什么版本的插件？

**Comment by lwjJoe** [comment]
![image](https://user-images.githubusercontent.com/29138640/115216988-9d581200-a137-11eb-834f-d772f3335d1e.png)
这个版本的

**Comment by SilurianYang** [comment]
那你需要设置 `encodeURI:false`

**Comment by lwjJoe** [comment]
这样设置可以拿到了。

**Comment by SilurianYang** [comment]
升级到2.0 自动模式，无须关系这些。
