### ISSUE TITLE
引入插件后，uni-forms表单验证无法在小程序中正常工作

### ISSUE THREAD

**Issue by longyinczy** [SilurianYang/uni-simple-router#258]
**问题描述**
[问题描述：引入插件后，uni-forms表单验证无法在微信小程序中正常工作（h5不受影响）

**复现步骤**
[复现问题的步骤]
Vue.use(router);
注释掉后微信小程序uni-forms表单验证恢复正常

**预期结果**
![image](https://user-images.githubusercontent.com/28260139/115517552-d3250400-a2b9-11eb-942d-8a44d2a1a863.png)

**实际结果**
![image](https://user-images.githubusercontent.com/28260139/115517850-2bf49c80-a2ba-11eb-92b3-cd1cace645ed.png)

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - 操作系统 [windows 10]
 - HBuilderX版本 [3.0.7]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [微信开发者工具]
 - uni-simple-router版本 [如 v2.0.2]

**补充信息**
[可选]
根据代码分析，引入插件后微信小程序VueComponent的childrens数组为空

**Comment by SilurianYang** [comment]
可以附上一个demo吗？

**Comment by DusuWen** [comment]
相同问题
