### ISSUE TITLE
版本2.0.2  自动化构建路由 无法通过path进入

### ISSUE THREAD

**Issue by ChenBin12138** [SilurianYang/uni-simple-router#259]
![image](https://user-images.githubusercontent.com/33656314/116038926-ab101900-a69c-11eb-8f8d-80cd3c68cd87.png)
![image](https://user-images.githubusercontent.com/33656314/116038955-b2cfbd80-a69c-11eb-9f97-5b3e5a0e6808.png)
![image](https://user-images.githubusercontent.com/33656314/116038997-c0854300-a69c-11eb-8e08-9283eb054f63.png)
![image](https://user-images.githubusercontent.com/33656314/116039047-cf6bf580-a69c-11eb-8280-6b0538d8c4d0.png)

**Comment by ChenBin12138** [comment]
可以通过别名进入，但是无法通过path进入

**Comment by SilurianYang** [comment]
`aliasPath` 其实是我的**取名**问题、它的作用是重写并覆盖 `path` 。一开始想的是用 `aliasPath` 制作一个别名，但是开发到后面直接就搞成了重写和覆盖的效果。。。但是名称依然保留为 `aliasPath`。这其实是一种歧义吧，因为历史原因所以一直被保留到了现在。

**Comment by ChenBin12138** [comment]
aliasPath 去掉之后是可以通过正常的进入了~

**Comment by ChenBin12138** [comment]
![image](https://user-images.githubusercontent.com/33656314/116044792-ebbf6080-a6a3-11eb-8727-c0516304bdfe.png)
![image](https://user-images.githubusercontent.com/33656314/116044816-f11cab00-a6a3-11eb-9ddb-9f2221e309f9.png)
![image](https://user-images.githubusercontent.com/33656314/116044871-0396e480-a6a4-11eb-8f3e-23ed4a8e5981.png)
动态路由好像也无法使用

**Comment by SilurianYang** [comment]
升级就好了 

https://github.com/SilurianYang/uni-simple-router/blob/a1168aec3d862cdd75eb479607a8e2ea4580ee39/test/path-to-regexp.spec.ts#L1-L61

**Comment by ChenBin12138** [comment]
这边升级到2.0.4 可以了

**Comment by ChenBin12138** [comment]
谢谢大佬~
