### ISSUE TITLE
使用HBuilderX创建uni-ui项目，使用uni-simple-router会导致onLaunch不执行

### ISSUE THREAD

**Issue by ClangLee** [SilurianYang/uni-simple-router#261]
**问题描述**
使用HBuilderX创建uni-ui项目，使用uni-simple-router会导致onLaunch不执行，首次跳转的时候才会触发App.vue内的onLaunch，onShow方法。
但是创建默认的uni-app项目，手动安装uni_modules组件库，再使用uni-simple-router，onLaunch会在项目启动的时候正常执行。

**复现步骤**

1. 使用HBuilderX创建uni-ui项目
2. 按照uni-simple-router文档步骤，安装uni-simple-router和uni-read-pages，并配置vue.config.js，router.js，main.js
3. 运行到微信开发者工具
4. 项目启动时，onLaunch没有执行
5. 在index.vue增加跳转按钮，使用this.$Router.push()跳转。
6. 会触发onLaunch

**预期结果**
启动项目的时候，onLaunch和onShow可以正常执行

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
小程序端需要在启动页配置 `onLoad` 选项，这样才会按预期执行

```js
<script>
	export default {
		data() {
			return {
				href: 'https://uniapp.dcloud.io/component/README?id=uniui'
			}
		},
		onLoad(){
			
		},
		methods: {

		}
	}
</script>

```

**Comment by ClangLee** [comment]
好的，谢谢大佬
