### ISSUE TITLE
原生TabBar不触发页面事件 onTabItemTap

### ISSUE THREAD

**Issue by k99k5** [SilurianYang/uni-simple-router#262]
**问题描述**

原生TabBar不触发页面事件 onTabItemTap

**复现步骤**

**预期结果**
![image](https://user-images.githubusercontent.com/18001536/116383292-4a720f00-a849-11eb-95e0-7bd122e30bb9.png)

**实际结果**
不执行

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**

**Comment by k99k5** [comment]
补充一些信息：APP上是正常的，H5上不正常

**Comment by SilurianYang** [comment]
明天将开始修复

**Comment by SilurianYang** [comment]
可以提交一个demo吗？ 我用 examples 下的示例添加 `onTabItemTap` 事件 在所有端都是可以正常触发的~

**Comment by k99k5** [comment]
测试了一下 是设置了aliasPath的原因；
设置了aliasPath之后就不能除了第一个tab能触发onTabItemTap  别的tab都不能触发.去掉aliasPath之后就可以了。。。

**Comment by SilurianYang** [comment]
已修复
