### ISSUE TITLE
在nvue页面监听onBackPress事件

### ISSUE THREAD

**Issue by awsdlz** [SilurianYang/uni-simple-router#263]
**问题描述**
[问题描述：在引入了插件之后监听onBackPress事件，物理返回与api返回均为navigateBack，在未引入插件之前是物理返回为backbutton]

**复现步骤**
[复现问题的步骤]
1. 引入插件
2. 在nvue页面监听onBackPress(options)打印options
3. 物理返回与api返回，打印后值均为navigateBack

**预期结果**
[监听onBackPress的物理返回为backbutton]

**实际结果**
[物理返回与api返回均为navigateBack]

**系统信息:**
 - 发行平台: [App]
 - 操作系统 [红米5plus、小米8]
 - HBuilderX版本 [3.1.12.20210428]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [红米5plus、小米8]
 - uni-simple-router版本 [如 v2.0.4]

**Comment by SilurianYang** [comment]
明天将开始修复

**Comment by SilurianYang** [comment]
## v2.0.5 修复
