### ISSUE TITLE
H5 下 返回按钮 无效

### ISSUE THREAD

**Issue by haoxf** [SilurianYang/uni-simple-router#264]
**问题描述**
H5在非首页打开页面，无法点击导航栏 返回按钮 回到首页
报错：
uni-app 原生方法：reLaunch({url:'/'}) 默认被重写啦！你可以使用 this.$Router.replaceAll() 或者 uni.reLaunch({url:'/?xxx=xxx'})

**Comment by SilurianYang** [comment]
1.x 的话

```js
const router = new Router({
    routes: [...modules],
   h5:{
  rewriteFun:false
}
});
```

**Comment by haoxf** [comment]
2.x 版本，大部分页面报错后仍可返回首页。但有个别页面无法返回

**Comment by SilurianYang** [comment]
> 2.x 版本，大部分页面报错后仍可返回首页。但有个别页面无法返回

个别页面是只，刚打开浏览器扫码进入非首页？ 然后还显示返回按钮的问题吗？

**Comment by haoxf** [comment]
> > 2.x 版本，大部分页面报错后仍可返回首页。但有个别页面无法返回
> 
> 个别页面是只，刚打开浏览器扫码进入非首页？ 然后还显示返回按钮的问题吗？

浏览器打开非首页，无法通过返回按钮回到首页。

**Comment by SilurianYang** [comment]
目前的h5上的返回都将给浏览器去处理。也就是说调用的是 `history.back()`  

Q: **浏览器打开非首页，无法通过返回按钮回到首页。**
A: 是的，目前只能返回上一层，而非定向到首页
