### ISSUE TITLE
对uniapp原生路由跳转方法的success回调的兼容

### ISSUE THREAD

**Issue by applefish-yu** [SilurianYang/uni-simple-router#266]
**新功能描述**
对uniapp原生路由跳转方法的success回调的兼容

**现状及问题**
navigateBack的success回调中使用上一个页面的方法和navigateTo的success 传值的无效了

**Comment by SilurianYang** [comment]
* `npm install ` 
*  运行到指定端

[testaaa.zip](https://github.com/SilurianYang/uni-simple-router/files/6456995/testaaa.zip)

**Comment by applefish-yu** [comment]
app端是可以的，h5端不行，1.5版本我看文档H5是有个rewriteFun属性的，它被替换成了什么？

**Comment by applefish-yu** [comment]
navigateBack的success回调app端与h5端都不行

**Comment by applefish-yu** [comment]
原生uniapp的navigateBack 是可以使用 success 回调，关闭插件你运行下就知道了

**Comment by applefish-yu** [comment]
good job 发自 网易邮箱大师 ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2021年06月08日 15:27 收件人 ***@***.***> 抄送至 ***@***.***>、State ***@***.***> 主题 Re: [SilurianYang/uni-simple-router] 对uniapp原生路由跳转方法的success回调的兼容 (#266) v2.0.6修复 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
