### ISSUE TITLE
H5端完全使用vue-router时，uni.createSelectorQuery()方法报错

### ISSUE THREAD

**Issue by AtLastDopamine** [SilurianYang/uni-simple-router#269]
**问题描述**
使用您提供的示例代码修改；
H5端完全使用vue-router；
vueRouterDev: true；
页面中使用uni.createSelectorQuery()方法报错
报错信息：chunk-vendors.js:234 [system] createSelectorQuery:fail
注释 vueRouterDev: true，uni.createSelectorQuery()方法可以使用

**复现步骤**
在 createRouter 中配置
`createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	h5: {
			// 完全使用vue-router开发 默认 false
			vueRouterDev: true
		},
	routes: [
		{
			path: '/pages/login/login',
			alias: '/',
			name: 'login',
			component: () => import('@/pages/login/login.vue')
		}
	]
});`

在页面 login 
`async mounted() {
			await this.$nextTick()
			console.log('开始：');
			console.log(uni.createSelectorQuery());
			console.log('# 结束 #');
		}`

报错图片：
![image](https://user-images.githubusercontent.com/33427467/117912731-9b3a3b00-b312-11eb-8edc-f0e948b537d5.png)

注释 vueRouterDev: true 后控制台打印结果：
![image](https://user-images.githubusercontent.com/33427467/117912920-f53b0080-b312-11eb-85c3-763d81e1cd2d.png)

**预期结果**
预期希望能正确调用uni.createSelectorQuery()方法
图片见复现步骤中

**实际结果**
无法调用uni.createSelectorQuery()方法
图片见复现步骤中

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [macOS 11.3.1 Chrome 90.0.4430.212（正式版本） (x86_64)]
 - HBuilderX版本 [HBuilderX 3.1.12.20210428]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [MacBook Pro]
 - uni-simple-router版本 [您提供的示例代码，没有走npm包，调用的是dist/uni-simple-router.js，猜测为最新版]

**补充信息**
猜测是替换掉了uni的内置组件，造成无法正确提供uni.createSelectorQuery()方法
![image](https://user-images.githubusercontent.com/33427467/117913888-cc1b6f80-b314-11eb-99d4-ca4f28ce113a.png)
![image](https://user-images.githubusercontent.com/33427467/117913967-f79e5a00-b314-11eb-9cd8-25c0c054f5ba.png)

**Comment by SilurianYang** [comment]
`vueRouterDev: true` 会导致部分uni-app的api无法使用，因为是替换了模板的渲染。  `vueRouterDev: true` 选项设计出来原本是给 h5 项目转 uni-app 直接使用的。如果你想在 `vueRouterDev:true` 情况下使用跨端的 `api` 请注意可用性。以上你可以使用条件编译解决这个问题

**Comment by AtLastDopamine** [comment]
@SilurianYang 
感谢您的回复。
这个会引发一个比较明显的问题，就是在使用第三方插件时，插件内部调用了uni.createSelectorQuery()方法，就会报错。例如 uni 插件中图表插件 uCharts，当插件多时，或者运行到uni.createSelectorQuery()方法时才会报错。隐藏性略高，不知您有没有较好的解决方案

**Comment by SilurianYang** [comment]
关闭 `vueRouterDev` 模式，或者移除跨端api

**Comment by AtLastDopamine** [comment]
@SilurianYang 
好的，谢谢啦。
如果您后期有时间的话，可以在文档上更新一个小tips。因为我阅读文档后认为只有影响uni的生命周期。

文档地址：https://hhyang.cn/v2/start/h5/match.html#h5%E7%AB%AF%E5%AE%8C%E5%85%A8%E4%BD%BF%E7%94%A8vue-router%E5%BC%80%E5%8F%91-v-1-3-5
![image](https://user-images.githubusercontent.com/33427467/117915593-2833c300-b318-11eb-92cb-92457e37724b.png)

**Comment by SilurianYang** [comment]
好的，谢谢支持

**Comment by Mr-duan** [comment]
我也遇到了 切换路由到时候 报的同样的问题 现在将切换路由的方式改成了uniapp自带的就没出现了
