### ISSUE TITLE
uniapp页面跳转失败

### ISSUE THREAD

**Issue by beitesting-lb** [SilurianYang/uni-simple-router#270]
使用push方式进行页面页面跳转提示VM400 WAService.js:2 TypeError: Cannot convert undefined or null to object
有些页面是可以跳转成功的，但是层级超过3层好像就不能继续跳转页面了，出现错误，如何解决，请提示谢谢
this.$Router.push({
		name: 'videoView'
	});
![image](https://user-images.githubusercontent.com/84167314/118219581-5ea24700-b4ac-11eb-8f38-e44c95af54ec.png)

**Comment by SilurianYang** [comment]
是否传递了包含 null  的参数？检查下

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/292
