### ISSUE TITLE
路由跳转问题

### ISSUE THREAD

**Issue by BenXi630** [SilurianYang/uni-simple-router#273]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 点击登录后，成功回调后，会强制执行路由守卫

[或者可以直接贴源代码]
1.登录成功的代码
![image](https://user-images.githubusercontent.com/38492283/119084883-2fa04e00-ba35-11eb-90f2-a5f9de98f78c.png)
2.路由守卫代码
![image](https://user-images.githubusercontent.com/38492283/119084947-4b0b5900-ba35-11eb-9a7f-54c1271eda04.png)

**预期结果**
登录成功后跳转首页

**实际结果**
![image](https://user-images.githubusercontent.com/38492283/119084985-64140a00-ba35-11eb-89cd-d4f5cf2f6de3.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 mac
 - HBuilderX版本 3.1.13
 - 项目创建方法 HBuilderX
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 v2.0.5

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
为什么会用到强制执行路由？ 第一张图是 `getToken` 方法吗？

**Comment by BenXi630** [comment]
> 为什么会用到强制执行路由？ 第一张图是 `getToken` 方法吗？

把`forceGuardEach`改成`pushTab("/pages/index/index")`也会报这个错。

第一张图是登录成功后的逻辑，登录成功后会跳转到首页。
第二张图就是路由跳转守卫，然后有没有token，有就继续，没有就跳转回登录页

**Comment by SilurianYang** [comment]
报错是因为你前一次执行了路由跳转，未正常结束。中间又执行了 实例 跳转。所以会给出错误提示！ 如果你想守卫下执行拦截之类的请使用 `next`。如果你想去除这个限制，你可以在 `detectBeforeLock` 下强制解锁。[文档](https://hhyang.cn/v2/start/cross/navLock.html)

**Comment by SilurianYang** [comment]
[login-auth-demo.zip](https://github.com/SilurianYang/uni-simple-router/files/6520858/login-auth-demo.zip)
这里有个 `demo` 你可以看看

**Comment by BenXi630** [comment]
> [login-auth-demo.zip](https://github.com/SilurianYang/uni-simple-router/files/6520858/login-auth-demo.zip)
> 这里有个 `demo` 你可以看看

谢谢，我看下

**Comment by BenXi630** [comment]
最后少写了个else
