### ISSUE TITLE
插件集成uni统计后，打开app出现白屏

### ISSUE THREAD

**Issue by lvminjie5201314** [SilurianYang/uni-simple-router#276]
**问题描述**
项目正常，集成插件后（未勾选uni统计），也可正常运行。勾选uni统计后，真机运行打开hbuilder基座-正常，打正式包-运行-白屏

**复现步骤**
[复现问题的步骤]
1. 使用魅族node6，安卓7.1.2版本。
2. 级成uni统计-打正式包
3. 打开app，白屏

**预期结果**
真机hubuilder正常运行
正式包可正常运行

**实际结果**
真机hbuilder正常运行
正式包白屏

**系统信息:**
 - 发行平台: APP
 - 操作系统: Android 7.1.2
 - HBuilderX版本: 3.1.13.20210514
 - 项目创建方法: HBuilderX
 - 设备信息: 魅族note6
 - uni-simple-router版本：2.0.5

**补充信息**
可能uni-simple-router内有函数跟uni统计函数冲突，云打包覆盖问题

**Comment by SilurianYang** [comment]
#### 是这个吗? 我没使用过 uni-app 的统计模块，我尝试将 `Statistic` 勾选，然后 `启用App平台统计`，最终打包 APK 在小米手机上可用
![QQ截图20210530164422](https://user-images.githubusercontent.com/31280665/120098158-e9e73200-c166-11eb-9caa-ddce77c97aaf.jpg)
![QQ截图20210530164857](https://user-images.githubusercontent.com/31280665/120098162-f10e4000-c166-11eb-97a1-63e224adc397.jpg)

### [打包的项目代码](https://github.com/SilurianYang/uni-simple-router/tree/master/examples/uni-simple-router2.0)，你可以尝试~~
