### ISSUE TITLE
在beforeEach中query参数为空

### ISSUE THREAD

**Issue by 2601940602** [SilurianYang/uni-simple-router#28]
![image](https://user-images.githubusercontent.com/31914597/66814200-ca3ad000-ef68-11e9-8b5c-a5eee24706c0.png)

**Comment by SilurianYang** [comment]
是的 这是你自己手动添加的参数 所以在此版本及之前都会是空  需用编码后传递加载query={xxxx} 下版本自动识别这种类型的

**Comment by 2601940602** [comment]
希望下个版本能解决这个问题，另外在这里能不能把这个参数也加上，有些业务比较需要知道完整的路径及参数
![image](https://user-images.githubusercontent.com/31914597/66892467-5e1aa380-f01e-11e9-895c-b4f0935bce09.png)
