### ISSUE TITLE
这个错误找不到原因，不知道哪里出了问题

### ISSUE THREAD

**Issue by KidAndroid** [SilurianYang/uni-simple-router#280]
我用 npm install uni-simple-router后，在项目成功安装，但是配置好后运行始终出现如图的错误，不知道少了哪步
![1](https://user-images.githubusercontent.com/24877705/120600197-122ea380-c47b-11eb-84d3-67d5ecc51c96.jpg)
![2](https://user-images.githubusercontent.com/24877705/120600204-135fd080-c47b-11eb-8e98-172f712a2f71.jpg)
![3](https://user-images.githubusercontent.com/24877705/120600209-1490fd80-c47b-11eb-8e21-45df5a81fa0d.jpg)
![4](https://user-images.githubusercontent.com/24877705/120600215-15299400-c47b-11eb-8a14-90acd08e08a2.jpg)
![5](https://user-images.githubusercontent.com/24877705/120600219-15c22a80-c47b-11eb-8cd1-9c9a2df933e7.jpg)
![6](https://user-images.githubusercontent.com/24877705/120600221-165ac100-c47b-11eb-91d1-d18c89778e3b.jpg)

运行在谷歌浏览器上面的

**Comment by SilurianYang** [comment]
插件版本和你看的文档版本不一致的问题吧  检查一下

**Comment by KidAndroid** [comment]
> 插件版本和你看的文档版本不一致的问题吧 检查一下

是的，刚看，没找到正确的打开方式
