### ISSUE TITLE
自动构建路由表的字段结构修改

### ISSUE THREAD

**Issue by TinsFox** [SilurianYang/uni-simple-router#281]
**新功能描述**
在`pages.json`中定义的`name`建议移动到`meta `中，也就是
```JSON
 "pages": [
        {
            "path": "pages/index/index",
            "name":"index",
            "meta":{
                "title": "首页"
            },
            "style": {
                "navigationBarTitleText": "uni-app"
            }
        }
    ],
```
修改成
```JSON
 "pages": [
        {
            "path": "pages/index/index",
            "meta":{
                "title": "首页",
                "name":"index",
            },
            "style": {
                "navigationBarTitleText": "uni-app"
            }
        }
    ],
```
**现状及问题**
有时候在路由跳转的时候需要进行权限判断之类的操作，这时候这些信息（是否需要授权）等信息会写到`meta` 中，将`name`移动到`meta` 中，个人会觉得路由信息会更有层次感，并且不会过度修改`pages.json` 尽可能保留了原样

**尝试方案**
无

**补充信息**
无

**Comment by SilurianYang** [comment]
### 1、为什么会出现读取 pages.json 作为路由表
读取 `pages.json` 作为路由表是因为早期很多人反馈**重复配置路由表繁琐**的问题，后面才出了一个 [uni-read-pages](https://github.com/SilurianYang/uni-read-pages) 的插件解决**重复配置路由表**的问题

### 2、路由插件中 routes 的定义
```js
interface RouteConfig {
  path: string, //pages.json中的path 必须加上 '/' 开头
  component?: Component,    //H5端可用
  name?: string, // 命名路由    
  components?: { [name: string]: Component }, // 命名视图组件，H5端可用   
  redirect?: string | Location | Function,  //H5端可用
  props?: boolean | Object | Function,  //H5端可用
  aliasPath?:string,    //h5端 设置一个别名路径来替换 uni-app的默认路径
  alias?: string | Array<string>,   //H5端可用
  children?: Array<RouteConfig>, // 嵌套路由，H5端可用
  beforeEnter?: (to: Route, from: Route, next: Function) => void,   //路由元守卫
  meta?: any,   //其他格外参数
  [propName: string]: any;
}
```

### 3、混淆问题
[uni-read-pages](https://github.com/SilurianYang/uni-read-pages) 只是实现了读取 `pages.json`  下的字段内容，最终你怎么去作组合字段是你的事情。至于`name` 在 `pages.json`下是顶级那是因为在`routes`下它的位置也是顶级，所以刚好读取出来就不需要重新组合啦。如果你想定义在`meta`也是没有问题的，这样的话就需要你去重新组合成行的路由表。为什么不一步到位呢？

### 4、再说name

`name` 在路由表中是虽然是非必要字段，但是在兼容h5中作为动态路由传递尤为重要。这就是为什么它会在顶级的原因，而并非是被你误解为用户自定义字段。

### 5、综合结果
不会因为 [uni-read-pages](https://github.com/SilurianYang/uni-read-pages) 的原因把 `name` 移动到 `meta` 下。如果你必须这种做是可以的，在运行时将`webpack.DefinePlugin` 注入的变量重新组合成路由插件需要的路由表格式即可
