### ISSUE TITLE
uniapp原生的EventChannel事件通信H5端报错

### ISSUE THREAD

**Issue by applefish-yu** [SilurianYang/uni-simple-router#283]
uni.navigateTo的success回调中使用eventChannel通讯传值，在h5端报错，其他端正常。经过调试发现原生回调的参数可以获取eventChannel，而使用插件后为undefined。

**Comment by SilurianYang** [comment]
请问你使用的是什么版本的插件？这边 `v2.0.8` 无法重现

**Comment by harlanjun** [comment]
2.0.8-beta.4 
2.0.8-beta.1 
这两个版本依然出现这个问题
![image](https://user-images.githubusercontent.com/26119115/167058983-7b641209-85d2-40c0-b3c6-cd6846b376f7.png)
![image](https://user-images.githubusercontent.com/26119115/167059014-f79156a0-36e7-4e68-ac84-a876bb21c356.png)

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/guide/advanced/parser-instance.html) 版本，该特性在 [组件之间的通信](https://v3.hhyang.cn/guide/advanced/parser-instance.html)  中可用
