### ISSUE TITLE
小程序路由拦截器失效

### ISSUE THREAD

**Issue by Mr-Joker-h** [SilurianYang/uni-simple-router#284]
"uni-simple-router": "^2.0.6",  HBuilderX 3.1.18  
在注册页面（register_for_gift） mounted中加入了自动获取用户unionid并跳转至产品页面的路由设定。
![image](https://user-images.githubusercontent.com/29029217/121627333-bcc14a80-caa9-11eb-9a54-b3ac3aa38209.png)

在路由拦截器中设定如果已登录用户访问注册页，则直接跳转至用户中心，但是用户跳转至用户中心后还会继续执行 register_for_gift的mouted ，代码如下
![image](https://user-images.githubusercontent.com/29029217/121627509-0b6ee480-caaa-11eb-8c02-85b0f26f937b.png)
打印结果如下
![image](https://user-images.githubusercontent.com/29029217/121627531-1cb7f100-caaa-11eb-9dec-1b23d230d254.png)

**Comment by Mr-Joker-h** [comment]
微信小程序，微信开发工具，Stable 1.05.2105170

**Comment by Mr-Joker-h** [comment]
虽然页面被拦截了，但是被拦截页面中的mounted和onLoad中的代码依然会继续执行。

**Comment by SilurianYang** [comment]
小程序已经为启动页代理了生命周期，只要没有 `next` 就不会执行启动页的生命周期  
https://github.com/SilurianYang/uni-simple-router/blob/90dee76aafdb331d9784b914da0a4d4fc2358378/src/helpers/config.ts#L91-L102

**Comment by Mr-Joker-h** [comment]
哦 哦 抱歉，是我的写法逻辑有问题。
