### ISSUE TITLE
使用2.0.6版本出现uniapp的onBackPress生命周期中无法返回上一页

### ISSUE THREAD

**Issue by applefish-yu** [SilurianYang/uni-simple-router#287]
**问题描述**
使用2.0.6版本出现uniapp的onBackPress生命周期中无法返回上一页

**复现步骤**
```
onBackPress(e) {
			if (e.from == 'backbutton') {
				uni.showModal({
					title: '温馨提示',
					content: '当前未完成支付，确认离开？',
					success: (res)=> {					
						if (res.confirm) {
							uni.navigateBack({
								delta: 1
							})
						}
					}
				});
				return true; //阻止默认返回行为
			}
		}
```

**预计效果:**
离开页面需要用户确定，点击确定后返回上一级

**实际效果:**
无法跳转

**系统信息:**
 - 发行平台: [App端]
 - 操作系统 [Android 10，11]
 - HBuilderX版本 [v3.1.18.20210609]
 - 项目创建方法 [HBuilderX]
 - uni-simple-router版本 [v2.0.6]

**补充信息**
经过调试2.0.5版本没有此bug，目前在使用2.0.6版本时，通过守卫拦截完成了类似的效果，不过Ｈ5端与app端需要做区别
```
// #ifdef H5
router.replace({ //H5端
path: to.fullPath
})
// #endif
// #ifndef H5
next() //App端
// #endif
```

**Comment by SilurianYang** [comment]
#### 在 `v2.0+` 的版本中 你可以完全放弃掉 `onBackPress`  用 `beforeRouteLeave` 代替
### [示例1](https://github.com/SilurianYang/uni-simple-router/blob/master/examples/uni-simple-router2.0/pages/beforeRouteLeave/beforeRouteLeave.vue)
### [示例2](https://github.com/SilurianYang/uni-simple-router/blob/master/examples/uni-simple-router2.0/pages/guard/guard.vue)

## 记得在路由守卫下添加 [NAVTYPE](https://hhyang.cn/v2/api/routerInsatll.html#navtype-v-1-1-0)

**Comment by applefish-yu** [comment]
但当调起第三方app时也会触发这个方法
