### ISSUE TITLE
在nvue页面无法使用

### ISSUE THREAD

**Issue by 2601940602** [SilurianYang/uni-simple-router#29]
![image](https://user-images.githubusercontent.com/31914597/67137401-44b86800-f267-11e9-9aa5-c3601eef3adc.png)

**Comment by SilurianYang** [comment]
目前nvue没有做处理   截止现在所有的版本都无法使用   后续会向这方面发展

**Comment by bbzhengcheng** [comment]
太牛了，膜拜，马上试用看看！

**Comment by SilurianYang** [comment]
## [v2.0.0-alpha.1](https://github.com/SilurianYang/uni-simple-router/releases/tag/v2.0.0-alpha.1) 可用

**Comment by thinkive** [comment]
v2.0.0-alpha.1 首页是nvue 启动还是白屏，这块能在后续版本解决吗？

**Comment by SilurianYang** [comment]
v2 目前的缺陷是 首屏启动不能为nvue   后续会支持

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
