### ISSUE TITLE
小程序路由拦截后再次点击跳转按钮提示页面正在跳转。

### ISSUE THREAD

**Issue by bettermonster** [SilurianYang/uni-simple-router#290]
通过uniapp编译启动的小程序

1.页面有一个按钮可以跳转，通过router.beforeEach进行登录拦截
2.第一次点击出现正常拦截，第二次点击报错提示页面正在跳转，第三次点击正常，随后报错。

![image](https://user-images.githubusercontent.com/37259454/123022211-0abe4280-d408-11eb-9398-4dd22b73f7e7.png)

 - 发行平台: 微信小程序
 - HBuilderX版本 HBuilderX 3.1.18.20210609
 - 项目创建方法 HBuilderX构建
 - uni-simple-router版本 2.0.5

**补充信息**
可能是路由拦截不彻底。因为并没有走其它方法，只是通过 store来控制提示登录的弹出框是否显示。

**Comment by SilurianYang** [comment]
请升级到 `v2.0.6` 此版本为小程序切页面加了控制时间。也就是说会完全捕捉页面切换完成后才会解锁路由， **You try！**

**Comment by bettermonster** [comment]
谢谢是路由锁没有配置好，没有好好看文档。

**Comment by SilurianYang** [comment]
👍
