### ISSUE TITLE
路由传参包含null就跳转失败

### ISSUE THREAD

**Issue by shilianmalaxiangguo** [SilurianYang/uni-simple-router#292]
**问题描述**
路由传参参数为对象，只要对象某个字段值为null，那么就会跳转失败
则之后的任意点击路由跳转都会在【type2：当前路由正在跳转】

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]

**预期结果**
参数有null可以正常使用

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**

 - uni-simple-router版本 [如 v2.0.0]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
传递参数 `null`  本身就没有太大的意义。在小程序上 `null` 可以被传递，但是会被解析为字符串`undefined` 。所以会和预期有所不同，你可以在传递参数之前自我排除下，因为这些参数都是开发者可控的。

`v2.0.7` 已经对此不足做了调整，你可以采用分支上的代码自己`build`一个新版本。或者在传递参数前先进行过滤
https://github.com/SilurianYang/uni-simple-router/blob/fba62975a8fad24e1e3cb9ffc63cd70d6b10ce0f/src/helpers/utils.ts#L304-L329

**Comment by shilianmalaxiangguo** [comment]
谢谢大佬说明
