### ISSUE TITLE
官网基础配置教程有问题，配出以后小程序端白屏

### ISSUE THREAD

**Issue by AK47-dadada** [SilurianYang/uni-simple-router#293]
**问题描述**
https://hhyang.cn/v2/start/quickstart.html

**复现步骤**
1. 安装对应的插件
2. 配置router.js
![image](https://user-images.githubusercontent.com/30396595/123887607-65b1e580-d984-11eb-87a3-d2e9de85991d.png)

3. 配置main.js
![image](https://user-images.githubusercontent.com/30396595/123887683-88dc9500-d984-11eb-9cb8-f3b934ea9b9f.png)

[或者可以直接贴源代码]

**预期结果**
路由内的页面正常显示如下图
![image](https://user-images.githubusercontent.com/30396595/123887793-ae699e80-d984-11eb-9471-757a8a4fada6.png)

**实际结果**
![image](https://user-images.githubusercontent.com/30396595/123887726-998d0b00-d984-11eb-8ec2-9ee8063215fb.png)

**系统信息:**
 - 发行平台: [MP-ALIPAY]
 - 操作系统 [win10 PC-开发者工具]
 - HBuilderX版本 [HBuilderX，3.1.18.20210609]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [iPhone6]
 - uni-simple-router版本 [v2.0.6]
 - uni-read-pages版本 [v1.0.5]

**补充信息**
h5端展示没问题，支付宝小程序一直白屏 不知道为什么，希望给个解决方案，蟹蟹

**Comment by SilurianYang** [comment]
首先排除下 没引入插件时编译到支付宝小程序是否正常。如果正常，请在集成完成插件时将项目重新编译并在开发者工具中重新打开。在小程序系列中插件不会影响页面白屏！我刚初始化了一个项目，请编译到小程序端测试看看

#### 操作步骤
1. `npm install`
2. 运行到支付宝小程序

[issues293.zip](https://github.com/SilurianYang/uni-simple-router/files/6737965/issues293.zip)

**Comment by AK47-dadada** [comment]
大神你好，引入前是没有问题的，所以现在这个很尴尬，我抄的你的代码还是不行.... 一直是白屏状态，也没报错，令我很费解。。。

**Comment by SilurianYang** [comment]
如果你排除不出什么原因，可以将你的项目上传到这里我可以帮你排除下。不方便所有人看的话，发我邮箱也行

**Comment by AK47-dadada** [comment]
大神你好，那就麻烦你了，本来也没啥，发过来了麻烦过目

[scan.zip](https://github.com/SilurianYang/uni-simple-router/files/6738553/scan.zip)

**Comment by SilurianYang** [comment]
你提供的项目不完整，我帮你补全了。 具体原因是因为页面生命周期你使用了`created`、在 `uni-simple-router` 集成后小程序端必须声明一个onLoad页面生命周期才能运行，这个问题会在下个版本中得到优化

**Comment by AK47-dadada** [comment]
给力！多谢大神，那我关闭issues了
