### ISSUE TITLE
命名路由，在 APP 端无论是组件式导航还是编程式导航都无法跳转

### ISSUE THREAD

**Issue by studyinhub** [SilurianYang/uni-simple-router#296]
**问题描述**
命名路由，在 APP 端无论是组件式导航还是编程式导航都无法跳转，但在 H5 端都是可以的

<my-link to="{name:'test'}">
	<slot></slot>
</my-link>

this.$Router.push({
	name:'test',
})

**系统信息:**
 - 发行平台:APP
 - 操作系统: IOS 12
 - HBuilderX版本 :3.1.18
 - 项目创建方法 :Vue-cli创建
 - 设备信息  iPhone8 Plus
 - uni-simple-router版本 v2.0.6

**Comment by SilurianYang** [comment]
`app` 和 `小程序` 都有强制的规定必须使用对应的 [NAVTYPE](https://hhyang.cn/v2/api/routerInsatll.html#navtype-v-1-1-0)。请选择对应的类型进行跳转
