### ISSUE TITLE
Vue 3.0路由支持

### ISSUE THREAD

**Issue by Fnxxxxo** [SilurianYang/uni-simple-router#298]
**新功能描述**
对Vue 3.0对应的Vue router 4提供支持

**现状及问题**
通过Vue3.0能为系统提供更好的TS支持，同理Vue router4也是

**Comment by SilurianYang** [comment]
当 `HBuilderX` 全面普及 vue3 时，我会开始进行这方面的工作

**Comment by Fnxxxxo** [comment]
对CLI项目没有这块的支持计划吗？

**Comment by AK47-dadada** [comment]
> 当 `HBuilderX` 全面普及 vue3 时，我会开始进行这方面的工作

2022年了大佬，虎年行大运，天天发大财，vue3啥时候上（手动狗头）

**Comment by aimeiyijia** [comment]
源码里面router.ts 中install部分中的Object.defineProperty(Vue.prototype 改为Object.defineProperty(app.config.globalProperties 就基本上可以运行了

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/451
