### ISSUE TITLE
uniapp h5非首页打开，navigateTo 到第二个页面路由丢失

### ISSUE THREAD

**Issue by haoxf** [SilurianYang/uni-simple-router#299]
**问题描述**
uniapp非首页打开，navigateTo 到第二个页面之后，路由丢失，再navigateBack无法回到上一页。
通过在第二个页面 getCurrentPages() 查看，只有第二个页面，第一个不见了。

请问这是uni-simple-router的问题，还是uniapp的？如何解决？

**Comment by haoxf** [comment]
实测禁用 uni-simple-router 之后没有问题。 uni-simple-router 启用了 alias

**Comment by SilurianYang** [comment]
这几天比较忙，没时间写demo测试。你可以上传一个demo并写下详细的操作步骤吗？ 这样我排除起来会比较精准及快

**Comment by haoxf** [comment]
[router-test.zip](https://github.com/SilurianYang/uni-simple-router/files/6781314/router-test.zip)

1. 在 /post 页面刷新
2. 点击 “跳转到 Input”，进入 input 页面
3. 在 input 页面点击 返回按钮
4. 虽然回到 /post 页面，但日志中出现：  uni-app 原生方法：reLaunch({url:'/'}) 默认被重写啦！你可以使用 this.$Router.replaceAll() 或者 uni.reLaunch({url:'/?xxx=xxx'})

通过
> `onLoad() {
    console.warn(getCurrentPages())
  }`
查看路由不正确

**Comment by haoxf** [comment]
实测禁用 aliasPath 之后可以返回

**Comment by SilurianYang** [comment]
你有什么需求？为什么要在tab post 页面再跳到 post 页面？

**Comment by haoxf** [comment]
> 你有什么需求？为什么要在tab post 页面再跳到 post 页面？

这个不是这个Demo的重点。重点是 在post页（非Tabbar）打开，然后跳转Input时路由丢失。

即浏览器打开： http://localhost:8080/post, 然后跳转 http://localhost:8080/input
