### ISSUE TITLE
IE 浏览器下：Unhandled promise rejection TypeError: 对象不支持“assign”属性或方法

### ISSUE THREAD

**Issue by appbest** [SilurianYang/uni-simple-router#30]
IE 浏览器下
仿真 IE 11 的报错：
Unhandled promise rejection TypeError: 对象不支持“assign”属性或方法

**Comment by SilurianYang** [comment]
老哥啊 我有点懵逼 为啥你手机还能装ie的浏览器 表示一脸懵逼

**Comment by xingyue234** [comment]
是否支持路由嵌套

**Comment by SilurianYang** [comment]
> 是否支持路由嵌套

目前全端不支持 1.3.5起h5端可以支持并有3种模式 qq群即将开始内测
