### ISSUE TITLE
fix: :bug: 组件内部周期钩子混乱

### ISSUE THREAD

**Issue by LOUSANPANG** [SilurianYang/uni-simple-router#300]
**问题描述**
1. 只有`onShow`钩子，打印信息失败。
```js
<script>
	export default {
		name: 'Index',

		data() {
			return {}
		},

		onShow() {
			console.log('onShow') // 未打印信息
		}
	}
</script>
```
```js
<script>
	export default {
		name: 'Index',

		data() {
			return {}
		},

 		onLoad() {
			console.log('onLoad') // 打印成功
		},

		onShow() {
			console.log('onShow') // 打印成功
		}
	}
</script>
```

2. 钩子内打印 `getCurrentPages()` 失败
```js
<script>
	export default {
		name: 'Index',

		data() {
			return {}
		},
		
		onLoad() {
	              getCurrentPages() // 失败

                      setTimeout(() => {
				getCurrentPages() // 成功
			})
		}
	}
</script>
```

**复现步骤**
1. 完全按照文档安装使用
2. 其他功能使用正常未出现问题

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统: [mac OS Big Sur 11.4]
 - HBuilderX版本 [HBuilderX 3.1.18.20210609]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [iPhoneX]
 - uni-simple-router版本 [^2.0.6]
 - uni-read-pages版本 [^1.0.5]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
### 第一种情况
已知问题它已经在v2.0.7中修复，你可以在dev分支下查看。**这个问题只会在小程序中重现**
https://github.com/SilurianYang/uni-simple-router/blob/fba62975a8fad24e1e3cb9ffc63cd70d6b10ce0f/src/helpers/mixins.ts#L80-L90

**解决：** 如果在使用`v2.0.7`之前的版本，运行到小程序端时必须使用uni-app的标准生命周期。并保证页面级组件必须拥有一个 `onLoad`

### 第二种情况
我尝试按照你提供的系统信息创建了一个demo，未发现上述问题。不管是在页面级 `onLoad`、还是子组件级 `created`、`mounted` 都能正常访问 `getCurrentPages()`
[issues300.zip](https://github.com/SilurianYang/uni-simple-router/files/6774239/issues300.zip)
