### ISSUE TITLE
小程序分享路径参数带json字符串报错

### ISSUE THREAD

**Issue by kudzu2019** [SilurianYang/uni-simple-router#301]
**问题描述**
微信小程序分享后，点击分享的链接进入对应页面，然后页面的跳转会json序列化报错
如果是tabbar页面的分享，执行navigateTo会报错，反之非tabbar页面执行switchTab会报错

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  分享到微信好友
3. 再点击分享的页面进入

[test.zip](https://github.com/SilurianYang/uni-simple-router/files/6798455/test.zip)

**实际结果**
![image](https://user-images.githubusercontent.com/56812785/125227392-698b2380-e305-11eb-800a-ba72f5aa3cbd.png)

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 3.1.22
 - uni-simple-router版本 最新master分支

**补充信息**
src/public/methods.ts 应该是这里出现的问题

**Comment by SilurianYang** [comment]
### 这么玩
```js
		onShareAppMessage(res) {
			return {
				title: '111',
				path: `/pages/index/index?query=${encodeURIComponent(JSON.stringify(this.item))}`
			}
		},
		onLoad(e) {
            console.log(this.$Route.query)
			console.log(e)
			if (e.item) {
				this.item = JSON.parse(decodeURIComponent(decodeURIComponent(e.item)))
			}
			console.log(this.item)
		},
```

### 文档说明

![QQ截图20210712180046](https://user-images.githubusercontent.com/31280665/125269267-1d5ad600-e33b-11eb-90c5-c8b4590dc855.jpg)

**Comment by kudzu2019** [comment]
还有一种是encodeURIComponent 两次

**Comment by SilurianYang** [comment]
### v2.0.7已修复
