### ISSUE TITLE
aliasPath 在微信小程序不生效

### ISSUE THREAD

**Issue by ccksfh** [SilurianYang/uni-simple-router#302]
**问题描述**
uni-simple-router ^2.0.6
```
"pages": [
		{
			"path": "pages/index/index",
			"aliasPath": "/",
		},
		{
			"path" : "pages/test/test",
			"aliasPath": "/test",
		}
	]
```
通过 `this.$Router.push({ path: '/test' })` 进行路由跳转时，h5中正常，微信小程序开发工具中报错：Error: /test 路径无法在路由表中找到！检查跳转路径及路由表。而如果 通过 `this.$Router.push({ path: '/pages/test/test' })`  跳转，又变成了小程序生效，h5报错（因为已经配置了 aliasPath）。尝试配置 "alias" 也不行

**Comment by SilurianYang** [comment]
目前只能通过 `name` 来处理，后续会更改为 `/pages/test/test` 兼容全端

```js
"pages": [
		{
			"path": "pages/index/index",
			"aliasPath": "/",
		},
		{
			"path" : "pages/test/test",
                        "name":"test",
			"aliasPath": "/test",
		}
	]

// 跳转
this.$Router.push({
   name:'test'
})
```

**Comment by ccksfh** [comment]
但是用 name 又不能用 query，所以跳转只能区分着跳

**Comment by SilurianYang** [comment]
### v2.0.7已修复
