### ISSUE TITLE
关于参数值中 出现 "&" 符号,   this.$Route.query 不能正确的获取数据

### ISSUE THREAD

**Issue by Evejunjie** [SilurianYang/uni-simple-router#303]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
我在使用 
 this.$Router.push({
	path: banner.path,
	query: {
			title:"公众号文章",
			url:"https://mp.weixin.qq.com/2&"
	},
});
进行页面跳转时,
发现 在  query 中的参数 出现 & 符号,那么在目标页面中 就不能正确的 获取 query 的值

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

this.$Router.push({
  path: banner.path,
  query: {
	  title:"公众号文章",
	  eee:"https://mp.weixin.qq.com/2&cc=2"
  },
  });

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
this.$Route.query = {
	  title:"公众号文章",
	  eee:"https://mp.weixin.qq.com/2&cc=2"
  },
**实际结果**
[这里请贴上你的报错截图或文字]
this.$Route.query = {}

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
尝试进行编码传输，因为有特殊字符，或者让插件检测为深度传参自动编码。

#### 检测为自动编码
```js
this.$Router.push({
    path:banner.path,
    query:{
        info:{
             title:"公众号文章",
             eee:"https://mp.weixin.qq.com/2&cc=2"
         }
    }
})

// 获取
this.$Route.query
```

**Comment by zxhyc131** [comment]
> 尝试进行编码传输，因为有特殊字符，或者让插件检测为深度传参自动编码。
> 
> #### 检测为自动编码
> ```js
> this.$Router.push({
>     path:banner.path,
>     query:{
>         info:{
>              title:"公众号文章",
>              eee:"https://mp.weixin.qq.com/2&cc=2"
>          }
>     }
> })
> 
> // 获取
> this.$Route.query
> ```

怎么才能关闭自动编码

**Comment by SilurianYang** [comment]
自行重置`resolveQuery`、`parseQuery` 来替换掉内置的处理函数
