### ISSUE TITLE
是否可以加上子路由？

### ISSUE THREAD

**Issue by gardenzjd** [SilurianYang/uni-simple-router#31]
在普通的H5页面开发中，经常使用到子路由。子路由的作用是很大的，一些弹出选项类组件需要返回值，由于操作空间的需要，会被作为一个子路由页面来处理（即获得了路由的返回，又可以通过事件给父页面传递值）。
如果将列表选项类组件直接作为弹出框，则没有路由返回功能，体验不佳。（降低原有H5体验）
当然也许可以直接将组件作为新页面路由，通过vuex修改父页面的值，但是既然是组件，如果通过vuex修改值，那么返回数据项就被约定了，所以还是子路由更合适，可以加子路由吗？对小程序有何影响？

**Comment by SilurianYang** [comment]
1.3.5已结可以设置子路由啦 请加群内测 或者去分支上拉取

**Comment by sophia1024** [comment]
请问是加了children这个属性吗？路由端口<router-view>还是以前的用法吗？

**Comment by SilurianYang** [comment]
@sophia1024  children的属性 相关可查看这里 [https://ask.dcloud.net.cn/article/36530](https://ask.dcloud.net.cn/article/36530)

**Comment by sophia1024** [comment]
大佬，这个方案可以用在APP端和小程序端吗还是说只能在H5端呢？

**Comment by SilurianYang** [comment]
@sophia1024  1.3.5版本仅支持H5端 这是对H5的加强 后续会对app 小程序进行同步化

**Comment by gardenzjd** [comment]
> 1.3.5已结可以设置子路由啦 请加群内测 或者去分支上拉取

请问如何加群内测。

**Comment by SilurianYang** [comment]
> > 1.3.5已结可以设置子路由啦 请加群内测 或者去分支上拉取
> 
> 请问如何加群内测。


群号 769241495
