### ISSUE TITLE
微信小程序在有混入的情况，生命周期紊乱

### ISSUE THREAD

**Issue by zuoyanart** [SilurianYang/uni-simple-router#312]
**问题描述**
小程序端，有混入的情况， 在小程序首次启动的时候，混入的onload，onshow方法执行慢于页面的onload，onshow， 
经测试， 不使用simple-router，生命周期正常

**复现步骤**

**预期结果**
执行顺序
mixin的load->page的load->mixin的show->page的show

**系统信息:**
 - 发行平台:  微信小程序
 - HBuilderX版本 3.1.22
 - 项目创建方法  vue-cli
 - uni-simple-router版本  v2.0.6/2.0.7

**Comment by SilurianYang** [comment]
正在修复，进度看这里 https://github.com/SilurianYang/test-wx-proxy-hooks

**Comment by SilurianYang** [comment]
### V2.0.7 已修复
