### ISSUE TITLE
文档解决API部分，没有列出函数所有的参数，比如pushTab函数

### ISSUE THREAD

**Issue by tyonly** [SilurianYang/uni-simple-router#314]
**新功能描述**
pushTab函数其实支持success fail方法，但是API描述里面根本没有提到，需要自己看代码分析，无形中浪费了大量时间

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by SilurianYang** [comment]
无须看代码分析，文档上有很明白的写着 `router.pushTab()` 等同于 `uni.switchTab()`，或者你可以尝试在 `pushTab` 中加入 `success`、`complete`、`fail` 就只知道是否支持了
