### ISSUE TITLE
钉钉小程序  在beforeEach里面使用next，控制台报Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RalapChen** [SilurianYang/uni-simple-router#315]
**问题描述**
![image](https://user-images.githubusercontent.com/23256312/129476382-7eb48a80-a15e-4734-9eb0-971e1e51ff2f.png)

**复现步骤**
[复现问题的步骤]
1. h5端 beforeEach next方法没问题，钉钉小程序会报Maximum call stack size exceeded

router.beforeEach( (to, from, next) => {
    next()
});

**预期结果**
可以使用next()控制页面跳转

**实际结果**
![image](https://user-images.githubusercontent.com/23256312/129476429-6232a81f-5aaa-4039-9210-8b48449956ef.png)

**系统信息:**
 - 发行平台: 钉钉小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
我打印了下日志，beforeEach无限调用，我做了判断，只有第一次执行next()，但还是不停的进来

**Comment by SilurianYang** [comment]
![Snipaste_2021-08-16_12-53-38](https://user-images.githubusercontent.com/31280665/129513005-28fe249a-a44a-41b2-beee-4ccbff238d7c.png)
我尝试使用该分支上的测试demo运行，并没有出现你所说的情况。请检查是否有死循环跳转
