### ISSUE TITLE
页面回退刷新问题

### ISSUE THREAD

**Issue by ccksfh** [SilurianYang/uni-simple-router#316]
**问题描述**
直接进入非首页页面 a，第一次从 a 进入页面 b，再从 b 返回到 a，此时 a 重新执行了生命周期。后续继续 a ->b -> a 的操作，a不会重新重新执行生命周期，与 问题 https://github.com/SilurianYang/uni-simple-router/issues/177 一致，v2.0.7 版本仍有此问题

**系统信息:**
 - 发行平台: H5平台
 - uni-simple-router版本 [如 v2.0.7]

**Comment by SilurianYang** [comment]
[h5-reload-page-test.zip](https://github.com/SilurianYang/uni-simple-router/files/6998333/h5-reload-page-test.zip)
你试试

**Comment by ccksfh** [comment]
你这个例子本身没问题，但我发现加了aliasPath就会有问题，你试试

**Comment by ccksfh** [comment]
> [h5-reload-page-test.zip](https://github.com/SilurianYang/uni-simple-router/files/6998333/h5-reload-page-test.zip)
> 你试试

这个有啥结论不？安排修改吗大佬

**Comment by SilurianYang** [comment]
添加 `aliasPath` 是bug

**Comment by ccksfh** [comment]
请问这个问题的修复有时间预期吗

**Comment by SilurianYang** [comment]
暂时没有时间、你可以先避免使用aliasPath

**Comment by elf9237** [comment]
问题还在啊，大佬！能不能争取下个迭代解下，项目里面aliasPath一定要用啊

**Comment by HelloJasonZhang** [comment]
也同样遇到一样问题，用aliasPath才能用/pages/a/:id 动态传参。 能否告诉下如何修复，等不及啊。

**Comment by SilurianYang** [comment]
### 请尝试 [2.0.8-beta.1](https://www.npmjs.com/package/uni-simple-router/v/2.0.8-beta.1)
