### ISSUE TITLE
Error: / 路径无法在路由表中找到！检查跳转路径及路由表

### ISSUE THREAD

**Issue by jiatiejun** [SilurianYang/uni-simple-router#317]
**问题描述**
按照官网文档的“开始”一步一步完成的，但是运行时根路径报错，其他正常

报错信息：
chunk-vendors.js:2145 Error: / 路径无法在路由表中找到！检查跳转路径及路由表
    at Object.e [as routesForMapRoute] (chunk-vendors.js:32639)
    at Object.v [as createRoute] (chunk-vendors.js:32639)
    at Object.t.forMatNextToFrom (chunk-vendors.js:32639)
    at c (chunk-vendors.js:32639)
    at Object.t.onTriggerEachHook (chunk-vendors.js:32639)
    at Array.myEachHook (chunk-vendors.js:32639)
    at <computed> (chunk-vendors.js:32639)
    at iterator (chunk-vendors.js:2184)
    at step (chunk-vendors.js:1951)
    at step (chunk-vendors.js:1955)

我的demo项目步骤：
1. 在 HBuilderX内部创建新的 uni-app
2. 在命令行加入 npm install uni-simple-router uni-read-pages
3. 添加 router/index.js 路由拦截代码
// uni-simple-router 的 router.js 内容
import {RouterMount,createRouter} from 'uni-simple-router';

const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	routes: [...ROUTES]
});
//全局路由前置守卫
router.beforeEach((to, from, next) => {
	console.log('拦截到的 to：', to)
	next();
});
// 全局路由后置守卫
router.afterEach((to, from) => {
})

export {
	router,
	RouterMount
}

4. 在 main.js中加入引用
import App from './App'
//引入uni-simple-router
import {router,RouterMount} from './router'
Vue.use(router)

// #ifndef VUE3
import Vue from 'vue'
Vue.config.productionTip = false
App.mpType = 'app'
const app = new Vue({
    ...App
})
//v1.3.5起 H5端 你应该去除原有的app.$mount();使用路由自带的渲染方式
// #ifdef H5
	RouterMount(app,router,'#app')
// #endif

// #ifndef H5
	app.$mount(); //为了兼容小程序及app端必须这样写才有效果
// #endif

// #endif

// #ifdef VUE3
import { createSSRApp } from 'vue'
export function createApp() {
  const app = createSSRApp(App)
  return {
    app
  }
}
// #endif

5. 启动运行后，就出现 / 根路径在路由表中没有找到的错误提示，但是直接打开 /pages/index/index 就是正常的

**Comment by SilurianYang** [comment]
## 标题
- 按照官网文档的“开始”一步一步完成的，但是运行时根路径报错，其他正常

## 解答
- 如果你需要 别名访问 请设置 `aliasPath`
- 如果你按文档一步一步走不可能有这样的问题
- 如果你按`快速上手`一路copy试试呢
- 如果是按文档一步一步完成的就不会有这个issue

## 最终解决
设置 `aliasPath`即可。如果有使用`uni-read-pages`，那么只需要在 `vue.config.js` 下设置读取 `aliasPath` 即可

```js
// vue.config.js
const tfPages = new TransformPages({
    includes: ['path', 'name', 'meta','aliasPath']
});
```
```js
// pages.json
{
    "pages": [
        {
            "path": "pages/index/index",
            "aliasPath":"/",
            "name":"index",
            "meta":{
                "title": "首页"
            },
            "style": {
                "navigationBarTitleText": "uni-app"
            }
        }
    ],
    "globalStyle": {
        "navigationBarTextStyle": "black",
        "navigationBarTitleText": "uni-app",
        "navigationBarBackgroundColor": "#F8F8F8",
        "backgroundColor": "#F8F8F8"
    }
}
```

**Comment by jiatiejun** [comment]
非常感谢，的确是我为了增加自己的 meta 属性，把默认自动生成的 aliasPath 去掉改成我自己想用的 auth 了，现在加上别名就一切正常了
