### ISSUE TITLE
组件内守卫beforeRouteLeave拦截不跳转 报错：Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 184177677** [SilurianYang/uni-simple-router#318]
组件内守卫beforeRouteLeave拦截 报错
VM2550 WAService.js:2 RangeError: Maximum call stack size exceeded

尝试了文档里的各种跳转方法   
next('/') 或者 next({ path: '/' }) 或者
next({
    name: 'index',
    NAVTYPE: 'pushTab'
});

beforeRouteLeave(to, from, next) {
	if (this.result) {
		console.log(123);
		next({
			path: '/pages/index/index',
			NAVTYPE: 'pushTab'
		});
	} else {
		next();
	}
},

**系统信息:**
 - 微信小程序、H5平台 
 - uni-simple-router版本 [v2.0.5]

**补充信息**
全局拦截是可以的

**Comment by 184177677** [comment]
好的 谢谢 我研究研究

**Comment by cxyun** [comment]
> 好的 谢谢 我研究研究

你好 ，你的全局是怎么拦截的？ 我全局拦截也是报同样的错误，栈爆满退出
