### ISSUE TITLE
beforeEnter 没有被调用

### ISSUE THREAD

**Issue by studyinhub** [SilurianYang/uni-simple-router#321]
最新版本，不知道为什么独享路由里的 beforeEnter 并没有被调用，只好先如下处理，在全局中自己判断一下 beforeEnter
```
router.beforeEach((to, from, next) => {
	console.log(`前置守卫  ${from.path} ==>${to.path}`)
	if(to.beforeEnter)
	{
		to.beforeEnter(to,from,next)
	}else
	{
		next();
	}
})
```

**Comment by studyinhub** [comment]
// 最后只好在这里加上这个，先解决问题
router.beforeEach((to, from, next) => {
	console.log(`前置守卫  ${from.path} ==>${to.path}`)
	if(to.beforeEnter)
	{
		to.beforeEnter(to,from,next)
	}else
	{
		next();
	}
});

**Comment by SilurianYang** [comment]
### 请对比下方demo

[issue_321.zip](https://github.com/SilurianYang/uni-simple-router/files/7113674/issue_321.zip)

**Comment by pursuit-YHP** [comment]
Is the Flying Book applet not supported? Why can't I trigger it on the Flying Book applet
