### ISSUE TITLE
edge浏览器手机模式下 使用浏览器的返回按键问题

### ISSUE THREAD

**Issue by tuohuang** [SilurianYang/uni-simple-router#326]
**问题描述**
edge浏览器手机模式下 使用浏览器的返回按键返回上一页后上一页的滚动位置没有保持，不用uni-simple-router的情况是正常或者使用uniapp自带的头部返回按钮正常。
**复现步骤**
[复现问题的步骤]
1. 使用edge浏览器手机模式打开某一个页面，页面滚动一下
2. 进入到另一个页面
3. 使用浏览器的返回按键返回上一页

[或者可以直接贴源代码]

**预期结果**
返回上一页可以保持页面滚动位置

**实际结果**
返回上一页没有保持页面滚动位置

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
自己实现以下这个方法，下面是示例

[h5-scrollTo-demo.zip](https://github.com/SilurianYang/uni-simple-router/files/7319981/h5-scrollTo-demo.zip)
