### ISSUE TITLE
"version": "2.0.7",  APP 端 需要点击两次 才能正常跳转 h5是正常的 

### ISSUE THREAD

**Issue by biaobaba** [SilurianYang/uni-simple-router#327]
"version": "2.0.7",  APP 端 需要点击两次 才能正常跳转 h5是正常的

**Comment by SilurianYang** [comment]
能看下你的`router.js`吗？

**Comment by biaobaba** [comment]
好奇怪 我重新弄了一个简单的DEMO 好像又是正常的，然后我把demo的搬到项目里也是正常的，&nbsp; 难道是我用yarn， 安装的插件包不行？
谢谢你的帮助，麻烦你了，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilurianYang/uni-simple-router"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 中午1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SilurianYang/uni-simple-router] "version": "2.0.7",  APP 端 需要点击两次 才能正常跳转 h5是正常的  (Issue #327)





 
在实际生产中并没有发现在app端跳转时需要点击两次，这个具体要看项目。所以我想让你上传你的router.js  或者上传一个可复现的测试demo，这样我好排除！
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SilurianYang** [comment]
方便上传你的所有配置截图吗？

**Comment by biaobaba** [comment]
这是我创建的demo,已经可以正常使用了,已经重现不了之前的问题了.....
也不知道之前是什么原因导致了 连续点击才能跳转的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilurianYang/uni-simple-router"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 中午12:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SilurianYang/uni-simple-router] "version": "2.0.7",  APP 端 需要点击两次 才能正常跳转 h5是正常的  (Issue #327)





 
方便上传你的所有配置截图吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
