### ISSUE TITLE
影响了原生navigateTo这个api ，传对象或数组的时候自动encode

### ISSUE THREAD

**Issue by 765918908** [SilurianYang/uni-simple-router#329]
装了插件之后，使用uni.navigateTo跳转页面传参是对象或者数组，会自动 encode转码，导致每次在页面取值的时候，都要decode一次。

**Comment by SilurianYang** [comment]
你可以使用内侧版本的功能  解决了这个问题， 你可以使用插件的获取方式，一样可以实现。
https://silurianyang.github.io/v2/start/cross/proxyHooks.html
