### ISSUE TITLE
基于typescript 构建的项目，引入该插件报错

### ISSUE THREAD

**Issue by smallsix99** [SilurianYang/uni-simple-router#33]
![image](https://user-images.githubusercontent.com/33114274/67929791-23f1fa00-fbf9-11e9-9ab6-69d1a1177758.png)

**Comment by SilurianYang** [comment]
设置 `sconfig.json`  `allowJs:true` 允许 编译js

**Comment by smallsix99** [comment]
@SilurianYang  还是不行呀，请指教一下，谢谢
