### ISSUE TITLE
如果跳转的页面不存在就会锁死，下次跳转的时候 只能暴力解锁。也就失去了锁的意义

### ISSUE THREAD

**Issue by mimicode** [SilurianYang/uni-simple-router#330]
**问题描述**
如果跳转的页面不存在就会锁死，下次跳转的时候 只能暴力解锁。也就失去了锁的意义。
建议如果页面不存在 报错的同时 进行解锁，这样不影响下次的跳转。

**复现步骤**
[复现问题的步骤]
1.引入插件
2.跳转到一个不存在的页面
3.点击其它页面 无反应。因为被锁了。会提示跳转中。。。

[或者可以直接贴源代码]

**预期结果**
 页面不存在 自动解锁

**实际结果**
[这里请贴上你的报错截图或文字]
页面不存在 抛出错误 而没有解锁

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
可以用通配符完成
```js
//router.js
const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	routes: [
		...ROUTES,
		{
		  path: '*',
		  redirect:(to)=>{
			  return {name:'404'}
		  }
		},
	]
});

```
