### ISSUE TITLE
在 `beforeRouteLeave` 钩子 next(false) 后，lockStatus 不会重置

### ISSUE THREAD

**Issue by jiangmaniu** [SilurianYang/uni-simple-router#333]
**问题描述**

![image](https://user-images.githubusercontent.com/50100681/141605096-3932bc2a-11f8-481e-bdd2-e191f85c8e50.png)

如图，第一次终止后，第二次会报正在跳转

需要手动重置，目前的做法是参考官网代码改进的

``` js
{
...
routerErrorEach: (error, router) => {
    if ([0, 3].includes(error.type)) {
      router.$lockStatus = false;
    }
  },
...
}
```

想问一下在中断跳转后为啥不会重置 lockStatus

**复现步骤**

[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
新版本已经默认添加解锁

https://github.com/SilurianYang/uni-simple-router/blob/5cfbc7a6d62c748ea13db4bc5494d24f4aa2299e/src/helpers/config.ts#L32-L35

**Comment by jiangmaniu** [comment]
> 新版本已经默认添加解锁
> 
> https://github.com/SilurianYang/uni-simple-router/blob/5cfbc7a6d62c748ea13db4bc5494d24f4aa2299e/src/helpers/config.ts#L32-L35

我明白了，我复制了官网的这段代码，把默认的给方法覆盖了

```js
routerErrorEach:(error, router)=>{
        if(error.type===3){       
            router.$lockStatus=false;
        }
    },
```

还有个问题就是，我需要在  `detectBeforeLock`  钩子判断路由  `path` 来决定要不要添加路由锁，我尝试通过一下这种形式获取

```js
detectBeforeLock: (router, to, navType) => {
      const curPath = router.currentRoute && router.currentRoute.path
      if (curPath === '/page/xxxxx/xxxxx') {
        //  在某个路由下的跳转不添加路由锁
        router.$lockStatus = false;
      }
  },
```

但这段代码在首页（也就是没有上一页的情况下）的路由访问 `router.currentRoute`  会直接报错，而不是返回 `undefined`

![image](https://user-images.githubusercontent.com/50100681/141607625-9f6f0103-f409-4b01-bdd8-e01b3871414d.png)

我的需求是只想获取当前的路由path，如果没有或是首页可以返回空值，我只需要判断条件即可，目前我的解决方案是在访问的时候添加 `try ... catch`

```js
detectBeforeLock: (router, to, navType) => {
     try {
         const curPath = router.currentRoute && router.currentRoute.path
         if (curPath === '/page/xxxxx/xxxxx') {
            //  在某个路由下的跳转不添加路由锁
             router.$lockStatus = false;
         }
     } catch (err) {
       console.log(err) // Error: 不存在的页面栈，请确保有足够的页面可用，当前 level:0
     }
     
  },
```

![image](https://user-images.githubusercontent.com/50100681/141607730-08408794-b6ba-4840-8928-7cbe9e900a89.png)

请问有更好的写法吗？

**Comment by SilurianYang** [comment]
确保至少有一个页面的情况下是可以获取 `router.currentRoute`  你可以用 getCurrentPages() 判断页面个数

**Comment by jiangmaniu** [comment]
感谢 ❤️
