### ISSUE TITLE
beforeEnter 中的 next 无法重定向到 nvue 的系统 tabbar 页面

### ISSUE THREAD

**Issue by jiangmaniu** [SilurianYang/uni-simple-router#334]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

根据 https://github.com/SilurianYang/uni-simple-router/issues/234#issuecomment-770946574 指示将空白过渡vue页 beforeEnter 钩子的 next 方法, 重定向到带有 nvue 的原生 tabbar 页面，nvue 页面的钩子能够正常触发，但是页面白屏无法渲染

[demo.zip](https://github.com/SilurianYang/uni-simple-router/files/7531797/demo.zip)

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
看起来好像是bug，一切正常 但是呈现白屏

**Comment by SilurianYang** [comment]
### 请尝试 [2.0.8-beta.2](https://www.npmjs.com/package/uni-simple-router/v/2.0.8-beta.2)

**Comment by AK47-dadada** [comment]
@jiangmaniu 问题解决了没，我也是从login跳转到tabbar界面直接白屏，但是生命周期可以打印出数据，甚至弹出$toast，求个解决方案
