### ISSUE TITLE
Uncaught SyntaxError: The requested module '/dist/uni-simple-router.js' does not provide an export named 'RouterMount'

### ISSUE THREAD

**Issue by 26327756** [SilurianYang/uni-simple-router#335]
[](url)**问题描述**
引入uni-simple-router 执行main.js 报错

**复现步骤**
uniapp 项目 引用vue-cli3.0 vite， uni-simple-router2.0
按照官网教程，打包启动正常，访问执行到引用RouterMount [即报错停止。能否有人支援一下，谢谢。
 
![Screenshot_20211115_161735](https://user-images.githubusercontent.com/18362430/141753131-a2a0ef14-44d5-4438-aa90-5e612076149d.png)

**Comment by 26327756** [comment]
![Uploading Screenshot_20211115_161735.png…]()

**Comment by SilurianYang** [comment]
目前不支持 vue3  及 vite  仅支持 vue2 加webpack

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/451
