### ISSUE TITLE
使用uni-simple-router后页面左上角的返回按钮返回  页面onBackPress 事件无效

### ISSUE THREAD

**Issue by krisHanJinBo** [SilurianYang/uni-simple-router#337]
![image](https://user-images.githubusercontent.com/31613253/142722547-f5b4720f-50b2-4e9d-883f-ec8772e86db8.png)
![image](https://user-images.githubusercontent.com/31613253/142722562-49db1d60-9415-4c54-8dc3-161b8e63b4f5.png)
![image](https://user-images.githubusercontent.com/31613253/142722606-b770997d-1946-4fb2-a42d-406a0c537723.png)

使用插件后 页面的onBackPress 无效了

**Comment by SilurianYang** [comment]
2.x 用这个 [查看详细](https://hhyang.cn/v2/migrate/migrate.html#app-vue-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E7%9A%84%E5%A4%84%E7%90%86)

**Comment by krisHanJinBo** [comment]
> 2.x 用这个 [查看详细](https://hhyang.cn/v2/migrate/migrate.html#app-vue-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E7%9A%84%E5%A4%84%E7%90%86)

**Comment by krisHanJinBo** [comment]
> 2.x 用这个 [查看详细](https://hhyang.cn/v2/migrate/migrate.html#app-vue-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E7%9A%84%E5%A4%84%E7%90%86)

老哥，好像跟我提的没啥关系，原生提供的onBackPress 无效了

**Comment by krisHanJinBo** [comment]
> 2.x 用这个 [查看详细](https://hhyang.cn/v2/migrate/migrate.html#app-vue-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E7%9A%84%E5%A4%84%E7%90%86)

老哥，我这个是原生的onBackPress 无效了

**Comment by SilurianYang** [comment]
改写了底层返回函数，此函数无效了，换成 `beforeRouteLeave` 即可，还可以处理异步操作

**Comment by LelKikyou** [comment]
我也遇到了同样的问题，onBackPress(){ return true } 之后 再返回就无效了。改用beforeRouteLeave也是这个问题 
beforeRouteLeave(to, from, next) {
      console.log(to)
      return
      next()
   }, 第一次返回beforeRouteLeave有效，第二次再返回就不起作用了

**Comment by SilurianYang** [comment]
可以上传一个可复现的demo吗？

**Comment by LelKikyou** [comment]
![1638341554(1)](https://user-images.githubusercontent.com/26542298/144186453-4ba0719c-3fb8-4ede-afbb-ab344a9f59da.jpg)
期望：虚拟按键返回被拦截，navigate返回不会被拦截
实际结果：点击虚拟按键返回之后，被拦截了，再使用navigate返回就没有效果了，console.log也不打印了。onBackPress和beforeRouteLeave都有这个问题。

**Comment by SilurianYang** [comment]
中断导航你需要传递 next(false)； 并且需要在 `detectBeforeLock` 中检测是否已经解锁(如果已有设置)  默认新版是会直接解锁的

**Comment by LelKikyou** [comment]
确实是中断导航之后被锁没有解锁的问题。我现在用的是^2.0.7版本，中断跳转没有自动解锁。
请问下是不是只要没有跳转成功都会自动上锁？然后需要人工去解锁

**Comment by SilurianYang** [comment]
新版本已经默认解锁，如果开发者添加了 `detectBeforeLock ` 函数，那么默认函数会被重置掉，需要开发者手动编码解锁
https://github.com/SilurianYang/uni-simple-router/blob/5cfbc7a6d62c748ea13db4bc5494d24f4aa2299e/src/helpers/config.ts#L32-L35

### [如何解锁](https://hhyang.cn/v2/start/cross/navLock.html)

**Comment by LelKikyou** [comment]
![image](https://user-images.githubusercontent.com/26542298/144215636-7731adf7-bf84-4bcb-ad6a-d5826cb64842.png)
你这里写的不是在routerErrorEach里面默认解锁的吗？而不是在detectBeforeLock
![image](https://user-images.githubusercontent.com/26542298/144215833-5d1765d4-4c38-40e2-b9bc-fd95515518c6.png)
我确实是重写了routerErrorEach，而默认函数会被重置掉了,所以没有解锁

**Comment by SilurianYang** [comment]
我人麻了，睡着了😂😂😂😂

**Comment by LelKikyou** [comment]
谢谢，已解决问题
