### ISSUE TITLE
文档说明 跟效果并不一致

### ISSUE THREAD

**Issue by w525718286** [SilurianYang/uni-simple-router#338]
![image](https://user-images.githubusercontent.com/9960461/142986021-5c0a566f-dcf1-4a75-80ae-3d755c59a065.png)

通过this.$Router.push({ name: 'router1', params: { userId: '123' }}) 跳转时，参数没有显示在url上，刷新浏览器参数会丢失，两种跳转方式并不等同

**Comment by SilurianYang** [comment]
文档Bug 稍后会修改

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
