### ISSUE TITLE
Page "pages/user/user" has not been registered yet.

### ISSUE THREAD

**Issue by wanglinyong** [SilurianYang/uni-simple-router#340]
Page "pages/user/user" has not been registered yet.

**Comment by wanglinyong** [comment]
![image](https://user-images.githubusercontent.com/32128499/144581583-10731307-037d-48c0-807b-f95c3b09b623.png)

**Comment by wanglinyong** [comment]
![image](https://user-images.githubusercontent.com/32128499/144581671-7bc688ed-e2fb-4b25-8ad3-32fbc1ccb16a.png)

**Comment by wanglinyong** [comment]
打印的日志“前置守卫”没出现

**Comment by SilurianYang** [comment]
![image](https://user-images.githubusercontent.com/31280665/144582684-80b67359-366b-4e95-8d75-9cc01775456e.png)
你应该这样写 `path:'/pages/xxxx/xxx'`   建议使用新版本  不推荐使用老版本插件

**Comment by wanglinyong** [comment]
![image](https://user-images.githubusercontent.com/32128499/144771911-257f3fa4-b112-4430-a246-cb1636dd4f5b.png)

**Comment by wanglinyong** [comment]
也不行呢

**Comment by wanglinyong** [comment]
![image](https://user-images.githubusercontent.com/32128499/144772134-08fb3691-0d76-40ec-a6d4-e9042eea7975.png)
有这些问题会影响吗？

**Comment by wanglinyong** [comment]
我的工程里没有package.json文件  不是vue-cli创建的项目
