### ISSUE TITLE
请问，h5路由跳转在本地调试正常，放在服务器上f5刷新白屏

### ISSUE THREAD

**Issue by jpgaus** [SilurianYang/uni-simple-router#342]
**问题描述**
本地localhost测试，无论从页面点击按钮跳转路由，还是直接在地址栏中输入URL，都可以正常显示。
上传到服务器（https）之后，页面点击按钮可以正常跳转，但地址位中输入URL，就是白屏。

**预期结果**
希望在服务器上，可以通过URL方式直接打开页面

**系统信息:**
 - 发行平台: H5
 - uni-simple-router版本: 1.5.5
 - 浏览器chrome

**Comment by jpgaus** [comment]
多谢关注！

1，我又试了一下，目前是部署在uniCloud提供的h5托管方式，会出现这个问题。
而且应该不是白屏，有一行提示：The requested file was not found on this server
2，如果按照传统方式，部署在服务器linux/nginx，可以完全正常使用，之前也是这么做的。
3，使用history模式

所以，问题似乎出在 simple-router 与uniCloud 配合时，对于h5托管/index.html解析路径有冲突?
我的主观感受是，直接输入url方式似乎压根没有正常解析传入的参数

**Comment by SilurianYang** [comment]
很抱歉，我没使用过 uniCloud。如果你可以提供访问地址，我可以帮助你排除一下
