### ISSUE TITLE
使用 next(false) 在APP上卡死问题

### ISSUE THREAD

**Issue by hdszy** [SilurianYang/uni-simple-router#343]
**问题描述**
在 全局路由前置守卫 中 ，使用 next(false) 后，APP 页面无法 后退、退出。 APP卡死，无法进行任何操作。

**复现步骤**
``` js
//全局路由前置守卫
router.beforeEach(async (to, from, next) => {
	
		const { vuex_vip } = store.state;
		const meta = to.meta;

			if (meta && meta.vip > vuex_vip) {
				next(false);
			} else {
				next();
			}
		
});

```

**预期结果**
可以正常 后退和退出应用。

**实际结果**

APP 无法进行任何操作，包括退出。只能通过进程关闭。

**系统信息:**
 - 发行平台: APP
 - 操作系统: Android 11
 - HBuilderX版本 : 3.2.16.20211122
 - 项目创建方法  HBuilderX
 - 设备信息：小米、魅族、华为
 - uni-simple-router版本： 2.0.7

**Comment by SilurianYang** [comment]
默认情况下，当你在 `next(false)` 时 插件会为你自动解锁。而当你在自定义 `routerErrorEach` 后 如果你未设置 ` type:0` 解锁，那么路由会永远被锁定。你可以通过 `routerErrorEach`  打印错误信息和解锁路由状态  

* [跳转路由锁](https://hhyang.cn/v2/start/cross/navLock.html)
* [退出应用](https://hhyang.cn/v2/start/app/runtimequit.html)
