### ISSUE TITLE
使用最新版本，跳转页面，第一次到B页面能够正常渲染数据，返回后，第二次再打开B页面，页面数据不会重新渲染

### ISSUE THREAD

**Issue by jikefenger** [SilurianYang/uni-simple-router#344]
**问题描述**
使用最新版本，跳转页面，第一次到A页面能够正常渲染数据，返回后，第二次再打开A页面，页面数据不会重新渲染

**复现步骤**
1. 在A页面，点击某个按钮跳转到B页面
2. B页面会调用接口获取数据，获取到数据后，会将数据绑定到B页面的列表组件中
3. 此时返回A页面，再次点击按钮，跳转到B页面
4. B页面不能将接口请求到的数据绑定到列表中，列表显示空白

**预期结果**
不管重复打开B页面，多少次，都应该像第一次一样，能够重新渲染

**实际结果**
第二次打开B页面，不能将数据渲染到列表中

**Comment by SilurianYang** [comment]
什么端？ B页面路径长什么样？ 接口请求写在那个生命周期下的 可以贴一些代码吗？

**Comment by jikefenger** [comment]
> 什么端？ B页面路径长什么样？ 接口请求写在那个生命周期下的 可以贴一些代码吗？![image](https://user-images.githubusercontent.com/13519412/145970024-fd060fc7-2084-45ab-aa99-28315954e828.png)
![image](https://user-images.githubusercontent.com/13519412/145970095-2f8bc6e7-608a-422c-b5d1-c251753a3782.png)

**Comment by SilurianYang** [comment]
第二次进入B页面生命周期触发都正常吗？

**Comment by jikefenger** [comment]
> 
是的，onLoad可以正常执行，在onLoad中调用接口，可以正常返回数据，但页面不能正常显示

**Comment by SilurianYang** [comment]
可以提交一个现有可复现的demo吗？

**Comment by jikefenger** [comment]
> 可以提交一个现有可复现的demo吗？

可以，明天我弄个demo发给你

**Comment by SilurianYang** [comment]
好的 谢谢你

**Comment by jikefenger** [comment]
> 好的 谢谢你
能提供一个邮箱吗？我把demo发你邮箱里

**Comment by jikefenger** [comment]
能提供一个邮箱吗？在这里上传demo文件太慢了

**Comment by SilurianYang** [comment]
将 `node_module` 去除 文件应该很小，可以在此上传

**Comment by jikefenger** [comment]
> 将 `node_module` 去除 文件应该很小，可以在此上传
[demo.zip](https://github.com/SilurianYang/uni-simple-router/files/7724962/demo.zip)

**Comment by jikefenger** [comment]
demo已上传。运行前执行npm install，安装依赖。
访问地址：http://localhost:8080/mobile
步骤：打开页面后，点击里边的“查看全部”按钮，会跳转到全部品牌页面。返回，再次点击“查看全部”按钮，跳转到全部品牌页面，接口正常返回数据，但没有在页面上展示出来

**Comment by SilurianYang** [comment]
好的，谢谢！我排除完成后会尽快回复你

**Comment by jikefenger** [comment]
> 好的，谢谢！我排除完成后会尽快回复你

好的，谢谢

**Comment by SilurianYang** [comment]
### 测试版bug，请回退到正式版 `v2.0.7` 另外出去重复挂载
![QQ截图20211216213444](https://user-images.githubusercontent.com/31280665/146381636-deb33f72-10af-458a-8228-610bfe0fea4a.jpg)
![QQ截图20211216213507](https://user-images.githubusercontent.com/31280665/146381680-4dc32847-90b2-4bfe-9e25-28e6b3bdf8cd.jpg)

**Comment by jikefenger** [comment]
好的，明天我试下。谢谢

**Comment by SilurianYang** [comment]
谢谢你 `demo` 👍👍👍👍

**Comment by jikefenger** [comment]
回退到2.0.7版本后，第一次跳转到B页面，返回A页面，A页面没被缓存，A页面会重新把生命周期都走一遍，和第一次打开一样。第二次打开B页面，再返回A页面就正常了，这个能解决吗？

**Comment by SilurianYang** [comment]
v2.8.0 版本中修复的bug就有其中一个 https://github.com/SilurianYang/uni-simple-router/issues/316 , 你可以先使用正式版。内测版bug我会尽快处理 到时候你直接升级到 v2.8.0 即可

**Comment by SilurianYang** [comment]
### 试试这个版本 [2.0.8-beta.3](https://www.npmjs.com/package/uni-simple-router?activeTab=versions)

**Comment by jikefenger** [comment]
目前看是没什么问题了，谢谢。
