### ISSUE TITLE
使用VUE-CLI方式创建的typescript项目使用uni-simple-router运行报错

### ISSUE THREAD

**Issue by qinxiaoxian** [SilurianYang/uni-simple-router#346]
![image](https://user-images.githubusercontent.com/20558478/146668326-963e55cb-af64-489d-813b-4a0bc89cdc9a.png)
![image](https://user-images.githubusercontent.com/20558478/146668365-4cb2ad0c-9f88-42c0-978c-b3c360634cd5.png)

**Comment by qinxiaoxian** [comment]
作者大哥可以看下是什么原因吗

**Comment by SilurianYang** [comment]
### 这里有文档 [ts 使用](https://hhyang.cn/v2/start/tsUse.html)

**Comment by qinxiaoxian** [comment]
大哥，我就是完全按照这个流程走的，还是报了错，使用VUE-CLI初始化的uni-app项目

**Comment by SilurianYang** [comment]
上传一些可复现的demo

**Comment by qinxiaoxian** [comment]
我刚才重新创建了一个纯净的项目，行了，应该是包的问题
抱歉，耽搁您时间了，不好意思哈
