### ISSUE TITLE
在vue3版uniapp中使用该插件功能时报错

### ISSUE THREAD

**Issue by EvinqWang** [SilurianYang/uni-simple-router#347]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
- 在vue3版uniapp中使用该插件功能时报错
> ![image](https://user-images.githubusercontent.com/19623957/146688672-be01b5cf-501f-4949-b78a-dcad26d43ad1.png)

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```
let install = (app:any) => { 
    // 这是由于该插件没有兼容vue3出现的问题
    app.use(router)
}
```
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [微信小程序、H5平台]
 - 项目创建方法 [如使用vite-cli创建]
 - 微信开发者工具，chrome浏览器
 - uni-simple-router版本 [如 v2.0.8-beta.3]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
可能是没有正确使用？

**Comment by SilurianYang** [comment]
目前还不支持vue3，请使用vue2

**Comment by aimeiyijia** [comment]
源码里面router.ts 中install部分中的Object.defineProperty(Vue.prototype 改为Object.defineProperty(app.config.globalProperties 就基本上可以运行了

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
