### ISSUE TITLE
最新版本，uni-cli 创建的模板项目。页面A跳转到页面B，页面B在跳转页面C。然后返回B重新进入页面C。onLoad和onShow周期不会进

### ISSUE THREAD

**Issue by goodFu** [SilurianYang/uni-simple-router#348]
**问题描述**
最新版本，uni-cli 创建的模板项目。页面A跳转到页面B，页面B在跳转页面C。然后返回B重新进入页面C。onLoad和onShow周期不会进

**复现步骤**
[复现问题的步骤]
1. 启动 '先执行yarn 然后执行 yarn dev:h5 启动项目'
2. 点击  '点击跳转测试->点击跳转demo->点击返回测试->再次点击跳转demo'
3. 查看控制台 第一次（测试页面打印123 demo页面打印456 ）第二次进入demo页面（456不打印）

**预期结果**
无论怎么进入demo页面（onShow生命周期都会进入（打印5））

**示例**
[demo](https://frontend-store.oss-cn-chengdu.aliyuncs.com/test/uni-project.zip)

**Comment by goodFu** [comment]
跳转使用的是$router.push

**Comment by SilurianYang** [comment]
请按照模板提交问题，否则无法排除

**Comment by SilurianYang** [comment]
这并不是插件的bug，这是uni-app本身的bug。uni-app 在H5底层依旧使用 vue-router，所谓的 `uni.navigateTo` 等跳转方法都是包装了 `vue-router` 实例方法，只是在中间做了一些列操作，包括 keepAlive 。这就是为什么你使用 `$router.push` 会出现生命周期异常的问题，因为没有正确移除缓存页面。换成 uni-app 本身跳转方法或者插件跳转方法即可。
