### ISSUE TITLE
应用生命周期onLaunch 无法跳转

### ISSUE THREAD

**Issue by cxyun** [SilurianYang/uni-simple-router#349]
**问题描述**
应用生命周期onLaunch 无法用uni.navigateTo跳转，请问这是什么问题呢，谢谢

**复现步骤**
[复现问题的步骤]

// #ifdef APP-PLUS  
let token = uni.getStorageSync('token');
if(! token){
	uni.navigateTo({              // **无法执行**
		url:"/pages/login/login",
		success:()=>{
			plus.navigator.closeSplashscreen();
		}
	})
}else{				
	plus.navigator.closeSplashscreen();				
}
// #endif

**Comment by SilurianYang** [comment]
不要在 `onLaunch` 中跳转，你应该在路由守卫下跳转

**Comment by cxyun** [comment]
> 不要在 `onLaunch` 中跳转，你应该在路由守卫下跳转

APP 下不能跳转，但是 H5 `是正常跳转的

现在加到守卫里面，会报 **chunk-vendors.js:2224 RangeError: Maximum call stack size exceeded** 错误

//全局路由前置守卫
router.beforeEach((to, from, next) => {

	let token = uni.getStorageSync('token');
	if (from.path !== '/pages/login/login' && ! token) {
		uni.navigateTo({
			url:"/pages/login/login",
			success:()=>{
				//plus.navigator.closeSplashscreen()
			}
		})
	}else{				
		//plus.navigator.closeSplashscreen()			
	}
	
	next()

});

**Comment by SilurianYang** [comment]
### 这样写，其他交给路由插件自动处理
```js
let token = uni.getStorageSync('token');
if (from.path !== '/pages/login/login' && ! token) {
        return next({
               path:'/pages/login/login',
               NAVTYPE:'push'
        })
}else{				
	//plus.navigator.closeSplashscreen()			
}

next()

```

**Comment by cxyun** [comment]
> ### 这样写，其他交给路由插件自动处理
> ```js
> let token = uni.getStorageSync('token');
> if (from.path !== '/pages/login/login' && ! token) {
>         return next({
>                path:'/pages/login/login',
>                NAVTYPE:'push'
>         })
> }else{				
> 	//plus.navigator.closeSplashscreen()			
> }
> 
> next()
> ```

感谢回复，还是报同样的错误
```
chunk-vendors.js:2224 RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at l (chunk-vendors.js:34744)
    at f (chunk-vendors.js:34744)
    at chunk-vendors.js:34744
    at e (chunk-vendors.js:34744)
    at Object.t.routesForMapRoute (chunk-vendors.js:34744)
    at c (chunk-vendors.js:34744)
    at chunk-vendors.js:34744
    at Object.routerBeforeEach (chunk-vendors.js:34744)
    at chunk-vendors.js:34744
```

**Comment by cxyun** [comment]
请问如何加入QQ群？加群的答案是？

**Comment by SilurianYang** [comment]
## 二群 : 716097859
