### ISSUE TITLE
v2.0.8-beta.3版本 APP真机调试正常，打包出来直接就白屏了！！！

### ISSUE THREAD

**Issue by rachelcao277** [SilurianYang/uni-simple-router#351]
**问题描述**
v2.0.8-beta.3版本 APP真机调试正常，打包出来直接就白屏了！！！

**复现步骤**
只要引入这个包并挂载到vue上打包出来就是白屏， 真机调试没有问题 `Vue.use(router)`

**系统信息:**
 - iOS和Android都一样

希望作者可以尽快修复一下出个正式版的， 感恩！

因为是老项目引用，需要用到最新的2.0.8版本才支持的内容

**Comment by SilurianYang** [comment]
是上传一个视频吗？ 要求：

* 1、打包后的APK
* 2、从桌面启动到白屏，或者是白屏结束
* 3、本地调试也附带一个视频

**Comment by rachelcao277** [comment]
回答：
2、就是从桌面打开出现启动页，启动页加载完成之后就整个白屏了
3、本地调试就是一切正常的样子

这个应该不需要上传视频了吧， 我的验证方式就是将router挂载到vue上这段代码注释掉只有在重新打包就没问题了

**Comment by rachelcao277** [comment]
> 是上传一个视频吗？ 要求：
> 
> * 1、打包后的APK
> * 2、从桌面启动到白屏，或者是白屏结束
> * 3、本地调试也附带一个视频

https://user-images.githubusercontent.com/33114417/147342014-fb395077-1689-4658-9222-07c7e5a5d57b.mp4
补充打开白屏视频

**Comment by SilurianYang** [comment]
一直都会白屏吗？是不是路由守卫下某些条件没对所以没next。导致一直在等待页面 ，你检查一下
看下这个资料 
* [app配置](https://hhyang.cn/v2/start/app/explian.html#%E5%AE%8C%E7%BE%8E%E7%9A%84%E9%85%8D%E7%BD%AE)
* [启动页生命周期](https://hhyang.cn/v2/start/app/start.html#%E5%90%AF%E5%8A%A8%E5%AE%8C%E6%88%90%E5%90%8E%E7%9A%84%E9%92%A9%E5%AD%90)

**Comment by rachelcao277** [comment]
`import {RouterMount,createRouter} from 'uni-simple-router';
import Vue from 'vue';
const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	routes: [...ROUTES],
	beforeProxyHooks: {
		onLoad(options: any, next: any){
			// @ts-ignore
			next([router.currentRoute.query]);
		},
		onShow([options]: any, next: any){
			// @ts-ignore
			const args=options||router.currentRoute.query;
			next([args]);
		},
		onLaunch([options]: any, next: any){
			next([{
				...options
			}])
		},
	},
});`

这里是我对路由的配置

**Comment by rachelcao277** [comment]
> 一直都会白屏吗？是不是路由守卫下某些条件没对所以没next。导致一直在等待页面 ，你检查一下 看下这个资料
> 
> * [app配置](https://hhyang.cn/v2/start/app/explian.html#%E5%AE%8C%E7%BE%8E%E7%9A%84%E9%85%8D%E7%BD%AE)
> * [启动页生命周期](https://hhyang.cn/v2/start/app/start.html#%E5%90%AF%E5%8A%A8%E5%AE%8C%E6%88%90%E5%90%8E%E7%9A%84%E9%92%A9%E5%AD%90)

对的， 就怎么打开都是白屏

**Comment by SilurianYang** [comment]
将 守卫置空（什么都不写，只放一个next） 然后打正式包看看是否能正常进入页面

**Comment by rachelcao277** [comment]
> 将 守卫置空（什么都不写，只放一个next） 然后打正式包看看是否能正常进入页面

```
import {RouterMount,createRouter} from 'uni-simple-router';
import Vue from 'vue';
const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	routes: [...ROUTES],
	// beforeProxyHooks: {
	// 	onLoad(options: any, next: any){
	// 		// @ts-ignore
	// 		next([router.currentRoute.query]);
	// 	},
	// 	onShow([options]: any, next: any){
	// 		// @ts-ignore
	// 		const args=options||router.currentRoute.query;
	// 		next([args]);
	// 	},
	// 	onLaunch([options]: any, next: any){
	// 		next([{
	// 			...options
	// 		}])
	// 	},
	// },
});
```

将beforeProxyHooks注释后又可以正常进入了

**Comment by rachelcao277** [comment]
![image](https://user-images.githubusercontent.com/33114417/147344643-670c04fd-181c-4895-9873-bc47ef74f6a2.png)
会不会和这个参数有关系？

**Comment by SilurianYang** [comment]
除去  `onLaunch` 试试 ，  currentRoute 这个属性是运行时

**Comment by rachelcao277** [comment]
> 除去 `onLaunch` 试试 ， currentRoute 这个属性是运行时

你那边可以有测试测试看看嘛， 我这边没打包次数了

**Comment by rachelcao277** [comment]
> 除去 `onLaunch` 试试 ， currentRoute 这个属性是运行时

除去onlaunch 只留下onLoad是可以正常打开的

**Comment by SilurianYang** [comment]
### 你可以这样写试试，但是我用github上的测试demo打包未出现这个BUG
```js
onLaunch([options]: any, next: any){
	next([{
		...options||{}
	}])
}
```

### 这是打包后的demo
[__UNI__DB9F679_1224193430.zip](https://github.com/SilurianYang/uni-simple-router/files/7774187/__UNI__DB9F679_1224193430.zip)

**Comment by rachelcao277** [comment]
> ### 你可以这样写试试，但是我用github上的测试demo打包未出现这个BUG
> ```js
> onLaunch([options]: any, next: any){
> 	next([{
> 		...options||{}
> 	}])
> }
> ```
> 
> ### 这是打包后的demo
> [__UNI__DB9F679_1224193430.zip](https://github.com/SilurianYang/uni-simple-router/files/7774187/__UNI__DB9F679_1224193430.zip)

这一段我先暂时的注释了， 后面我在加上试试， 目前是没问题的

**Comment by SilurianYang** [comment]
请提供可复现打的demo

**Comment by rachelcao277** [comment]
> 请提供可复现的demo

抱歉，在已有项目中集成的，无法提供可复现的demo， 感谢作者的解答

**Comment by SugarTiger** [comment]
白屏我也遇到了，应该是这个问题，但是我不知道怎么处理，求助大佬
[Vue warn]: Error in event handler for "view.webviewReady": "Error: 不存在的页面栈，请确保有足够的页面可用，当前 level:0"
15:45:49.607 (found )
15:45:49.638 Error: 不存在的页面栈，请确保有足够的页面可用，当前 level:0

**Comment by SugarTiger** [comment]
按照文档的示例
uni-simple-router@2.0.7

`
//router/index
const router = createRouter({
  platform: process.env.VUE_APP_PLATFORM,
  encodeURI: false,
  routes, //路由表
});
import { router, RouterMount } from "@/router/index.js";
Vue.use(router);
const app = new Vue({
  ...App,
  store,
});

//v1.3.5起 H5端 你应该去除原有的app.$mount();使用路由自带的渲染方式
// #ifdef H5
RouterMount(app, router, "#app");
// #endif

// #ifndef H5
app.$mount(); //为了兼容小程序及app端必须这样写才有效果
// #endif
`

**Comment by SilurianYang** [comment]
> 白屏我也遇到了，应该是这个问题，但是我不知道怎么处理，求助大佬 [Vue warn]: Error in event handler for "view.webviewReady": "Error: 不存在的页面栈，请确保有足够的页面可用，当前 level:0" 15:45:49.607 (found ) 15:45:49.638 Error: 不存在的页面栈，请确保有足够的页面可用，当前 level:0


你这个是在app.vue 或者在应用未挂载成功页面时访问了  `$Route` 属性？

**Comment by SugarTiger** [comment]
> 

是的，刚刚this.$AppReady就可以了，感谢大佬
