### ISSUE TITLE
小程序端如何实现返回刷新

### ISSUE THREAD

**Issue by ren2436** [SilurianYang/uni-simple-router#352]
**新功能描述**
痛点：
1、小程序端有10层页面栈的个数限制
2、部分页面跳转比较容易出现无限循环的情况（AB或更多页面存在互跳）
特别是第2点，非常难以处理

**现状及问题**
返回刷新的功能需求：
1、使用$Route.back() 或者 navigateBack()
2、跳转已存在的页面使其自动执行返回（防止跳转死循环）

**尝试方案**
1、对于需求1，可以存储一个全局变量，返回后，在onShow中查询是否执行更新，虽然好用，但也有一定的局限性，比如无法修改页面参数（$Route.query），需求2倒是可以解决
2、对于需求2，在routerBeforeEach中查询要跳转的页面是否已存在，如果存在，则通过next()转为back，然后再手动执行页面的onLoad，对于页面没有参数的情况下，此方法可行，但对于有参数时，由于$Route是只读属性，并不能手动设置，临时解决办法可以通过先next(back)，再延迟100ms 执行 next(push)，虽然看起到勉强倒也能接受，但总觉得不妥，手机在运行不畅的时候，非常容易出现异常的BUG

**补充信息**
还有什么更为保险或者更好的办法么？还望能解答，非常感谢

**Comment by SilurianYang** [comment]
## 你可以先看看此写法，此包使用的是 [2.0.8-beta.4]() 的插件，我会在明天发布此插件
## [appletBackRefresh.zip](https://github.com/SilurianYang/uni-simple-router/files/7777330/appletBackRefresh.zip)

**Comment by ren2436** [comment]
@SilurianYang 非常感谢
此方法确实不错，也很好的解决了需求2的问题
对于需求1还有一点小小的需求，可以在 back中传递一个参数，用来控制是否返回刷新（自动调用onLoad），全局数据控制虽然可以解决问题，毕竟需要多做一些操作

**Comment by ren2436** [comment]
@SilurianYang 
2.0.8版本或者 2.0.8-beta.4 什么时候能发布

**Comment by ren2436** [comment]
@SilurianYang 
2.0.8版本或者 2.0.8-beta.4 什么时候能发布

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性可通过 [组件之间的通信](https://v3.hhyang.cn/guide/advanced/parser-instance.html)  解决
