### ISSUE TITLE
混合发行嵌入原生开发，提示路径无法在路由表中找到

### ISSUE THREAD

**Issue by jiangxin12** [SilurianYang/uni-simple-router#355]
**问题描述**
混合发行嵌入原生开发，提示路径无法在路由表中找到

**复现步骤**
1. 混合打包后，放入原生包中
2. 微信开发者工具运行
3. 提示 ‘提示路径无法在路由表中找到’

**实际结果**
![代码目录](https://user-images.githubusercontent.com/32059064/148524330-434cd098-bce7-42b4-b598-1321419ac699.png)
![提示错误文件](https://user-images.githubusercontent.com/32059064/147913820-ba94e8de-ec02-4316-b7e5-eea6ae129089.png)

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 [3.3.5]
 - 项目创建方法 [HBuilderX]
 - uni-simple-router版本 [v2.0.7]

**补充信息**
退回2.0.5版本正常运行

**Comment by SilurianYang** [comment]
一半是用uni-app开发？一半是原生开发？

**Comment by jiangxin12** [comment]
> 一半是用uni-app开发？一半是原生开发？
是的，uni-app开发后混合打包，放入到原生小程序包中

**Comment by SilurianYang** [comment]
是因为你合并的js的问题吧，导致uni-app对原生跳转api包装了一层，从而导致路由走了插件这边。当检测到跳转路径不符合时就会报这个错，你可以将你原生中的所有需要跳转的route都提前写入到插件实例化时。这样可以避免这个问题

**Comment by jiangxin12** [comment]
合并的js是指哪个

**Comment by jiangxin12** [comment]
图中‘community_support’是用uni-app打包出来的，打包出来后直接放到原生小程序包根目录中，没有做任何改动
从原生的其它页面跳转进来时，就提示路径错误。
是指将原生的其它页面的route都写到routes中吗

**Comment by SilurianYang** [comment]
是的，你尝试下

**Comment by jiangxin12** [comment]
但小程序是多人协作开发，可以随时增减页面的

**Comment by jiangxin12** [comment]
并且是服务多个客户，那这样很不方便，有其它办法吗

**Comment by SilurianYang** [comment]
目前没有办法，你可以用动态更改routes的方法，但是这个比较麻烦。我会在下个版本中更新你所需要的功能

**Comment by jiangxin12** [comment]
用2.0.7版本打包出来不行，退回2.0.5版本正常，但看了下版本发行记录，好像没看出哪里会影响这个

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
