### ISSUE TITLE
H5端完全使用vue-router开发时 首页空白

### ISSUE THREAD

**Issue by RedShameA** [SilurianYang/uni-simple-router#358]
**问题描述**
如题

**复现步骤**
1. 启动
2. 查看首页空白

[源码](https://reda.lanzoup.com/iITVLyrkzwd)

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [ios]
 - HBuilderX版本 [3.3.5.20211229]
 - 项目创建方法 [HBuilderX ]
 - 设备信息 [无]
 - uni-simple-router版本 [2.0.7]

希望指点一下

**Comment by SilurianYang** [comment]
路由表设置错误，请查看文档 https://hhyang.cn/v2/start/h5/match.html#h5%E7%AB%AF%E5%AE%8C%E5%85%A8%E4%BD%BF%E7%94%A8vue-router%E5%BC%80%E5%8F%91-v-1-3-5

**Comment by RedShameA** [comment]
> 路由表设置错误，请查看文档 [H5端完全使用vue-router开发](https://hhyang.cn/v2/start/h5/match.html#h5%E7%AB%AF%E5%AE%8C%E5%85%A8%E4%BD%BF%E7%94%A8vue-router%E5%BC%80%E5%8F%91-v-1-3-5)

看到了，解决了，忘记及时回复了
作者效率真高！点个赞🤺
