### ISSUE TITLE
挂载路由失败，router.app 应该为数组类型。当前类型：undefined

### ISSUE THREAD

**Issue by Loki0612** [SilurianYang/uni-simple-router#364]
**问题描述**
按照配置对应修改文件后，启动项目 
提示  挂载路由失败，router.app 应该为数组类型。当前类型：undefined

**复现步骤**
1. 按照官方文档配置 main.js/router.js/vue.config.js
2. 启动项目：  chrome、H5
3. 提示：挂载路由失败，router.app 应该为数组类型。当前类型：undefined
![image](https://user-images.githubusercontent.com/22511947/154878775-0ee818fd-d032-4a2a-94a1-47a1bd6db01a.png)

**预期结果**
希望能正常使用路由

**实际结果**
![image](https://user-images.githubusercontent.com/22511947/154878819-f072106e-4b8f-4ded-8a12-67d16bdc71af.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 chrome
 - HBuilderX版本 3.3.11
 - 项目创建方法 HBuilderX
 - 设备信息 windows 10
 - uni-simple-router版本 "^2.0.7"

**Comment by SilurianYang** [comment]
尝试重新编译一次？看起来没有任何问题

**Comment by x363090973** [comment]
解决了吗？我也出现一样的问题
