### ISSUE TITLE
官网的深度对象传递例子是不是写错了？

### ISSUE THREAD

**Issue by Rexexe** [SilurianYang/uni-simple-router#368]
**问题描述**
没看出来跟非深度对象传递有什么区别啊，是不是少了个JSON.stringify

**Comment by SilurianYang** [comment]
你是指那个位置错了？插件内部自动检测并实现

**Comment by Rexexe** [comment]
可能是我理解有问题
![image](https://user-images.githubusercontent.com/27289798/158376485-a1524753-f8f4-45a5-9972-1aa79850390d.png)

这上下两个不都是path+query传值吗？

**Comment by SilurianYang** [comment]
一个是字符串，一个是对象
