### ISSUE TITLE
在app端使用后，点击返回键 uniapp 默认提示的 再按一次返回 消失，按返回键也无法退出应用了

### ISSUE THREAD

**Issue by JF98** [SilurianYang/uni-simple-router#370]
**在app端使用出现的bug**

**复现步骤**
[复现问题的步骤]
1. 通过 cli 创建默认模板
2. 按照文档配置 uni-simple-router
3. 配置后，在 hbuilderX 编辑器中启动项目。
4. 启动结束后，点击手机返回按钮，此时 uniapp 默认提示的 “再按一次退出” ，不再出现；双击手机的返回按键 也无法退出应用；
（正常创建项目后，启动点击返回按键是可以退出应用的）

[或者可以直接贴源代码]

**预期结果**
点击手机返回按键 提示 “再按一次退出” ，双击退出应用

**实际结果**
点击手机返回按钮，无反应，双击、多击 无反应，也无法退出应用；

**系统信息:**
 - 发行平台: [App]
 - 项目创建方法 [Vue-cli创建]
 - 设备信息 [小米6，其他安卓手机应该一样]
 - uni-simple-router v2.0.7

**Comment by SilurianYang** [comment]
https://hhyang.cn/v2/start/app/runtimequit.html

**Comment by JF98** [comment]
> 退出应用已被拦截，可以自定义。[详细查看](https://hhyang.cn/v2/start/app/runtimequit.html)

好的，谢谢
