### ISSUE TITLE
微信小程序跳转动画导致提示“当前页面正在处于跳转状态”

### ISSUE THREAD

**Issue by 240521** [SilurianYang/uni-simple-router#371]
**问题描述**
小程序判断是否返回401，401的话就会$Router.replace新的页面，但是微信跳转的动画好像会认为正在跳转中，路由的replace会让其跳转到登录页，就会导致跳转失败，提示页面正处于跳转中。

**复现步骤**
[复现问题的步骤]
1.启动微信开发者工具
2.点击按钮进行跳转，其中有跳转动画
3.跳转的页面接口返401进行拦截，replace到登录页

[或者可以直接贴源代码]
```js
http.interceptors.response.use((response) => {
    if (response.data.status == 401) {
		console.log(response,'登录状态失效');
		tip.error('登录状态失效');
        Router.replace({name: 'auth'})
		store.dispatch('auth/clearAuth')
        return Promise.reject(response)
    }
    return response
}, (response) => {
    tip.error(JSON.stringify(response.data))
    return response
})

```

**预期结果**
留下动画，实现401后跳转到登录页

**实际结果**
提示跳转中，阻止再次跳转

**系统信息:**
 - 发行平台: [微信小程序]
 - HBuilderX版本 [3.3.5.20211229]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - uni-simple-router版本 [ v2.0.6]

**补充信息**
微信跳转的动画好像会认为正在跳转中

**Comment by SilurianYang** [comment]
跳转动画未完成之前视为跳转中，因为在跳转动画触发时点击速度过快依然可以再次触发跳转，从而打开多次同一个页面。这是原生的情况

1、路由锁解决开发者或者用户在同一时间多次触发跳转操作
2、你可以在 `detectBeforeLock`  或者 `routerErrorEach` 根据自身逻辑解锁

像你在拦截器里面跳转，你可以在 `detectBeforeLock` 中根据 to 判断是否放行
