### ISSUE TITLE
使用uni-simple-router路由前置路由next()无效无法跳转

### ISSUE THREAD

**Issue by wushunqing** [SilurianYang/uni-simple-router#372]
跟这个问题一模一样，进入调试模式后，next后没有效果。

看了一年多，依旧没有解决，请作者分析一下。

https://ask.dcloud.net.cn/question/101368

![image](https://user-images.githubusercontent.com/20431475/159103461-f2519b6f-9489-4f8d-b35a-9061e760552a.png)

**Comment by SilurianYang** [comment]
可以上传一个demo吗？

**Comment by littleboyck** [comment]
怎么处理分包问题？
