### ISSUE TITLE
扫别人分享的页面第一次进来报错

### ISSUE THREAD

**Issue by lengjunbin-trec** [SilurianYang/uni-simple-router#374]
**问题描述**
第一次扫别人的分享的码进入小程序会失败，但是紧接着扫第二次就没问题了。

**复现步骤**
[复现问题的步骤]
1.删掉小程序，
2.扫描别人提供的码进入小程序，报错
3.第二次扫描没问题了
[或者可以直接贴源代码]

**预期结果**
第一次扫描就可以进去

**实际结果**
![image](https://user-images.githubusercontent.com/61955063/160124816-2f842402-4b0d-4a13-bc8e-47e7e557218d.png)

**系统信息:**
 - 发行平台:  微信小程序
 - 操作系统  iOS 14.1.2
 - HBuilderX版本 3.3.11
 - 项目创建方法 /HBuilderX
 - 设备信息 iPhone12
 - uni-simple-router版本  v1.5.5

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by lengjunbin-trec** [comment]
@SilurianYang

**Comment by SilurianYang** [comment]
1.5.5版本？ 建议使用新版本 因为uni-app一直在升级 它可能去除了某些属性或者是冷启动和热启动属性注入的时机变更了，导致低版本插件不兼容
