### ISSUE TITLE
调用 uni.navigateBack 报错 无法返回上一层

### ISSUE THREAD

**Issue by ZzxStormrage** [SilurianYang/uni-simple-router#376]
**问题描述**
百度小程序  打开新的tab 调用 navigateBack时候报错  版本2.0.8-beta.3

报错信息
![image](https://user-images.githubusercontent.com/25241961/160367089-85220b67-c2c7-4fee-87fb-57bdad9b0b9a.png)

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```
select(item) {
  if (this.isSelect) {
			this.$u.vuex('receiving_address', item)
			uni.navigateBack({
				delta: 1
			})
		}
	},
```

**预期结果**
返回上一层

**实际结果**
报错 且无法返回 可以手动返回

**系统信息:**
 - 发行平台: 百度小程序
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhoneX]
 - uni-simple-router版本 2.0.8-beta.3

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by jrt324** [comment]
我也遇到同样的问题，如果返回的上级页面传递简单参数是没问题的，上级页面携带复杂的url编码参数时，就是报这个错误

**Comment by li1164267803** [comment]
同样的问题，我就是a页面传了一个数组对象，然后点击去了b页面，b页面返回a的时候，报错了 `Cannot convert undefined or null to object`，如果a页面是简单的参数，没有数组对象，就不会报错，现在的处理方法就是有负责参数时，直接使用replace

> 我也遇到同样的问题，如果返回的上级页面传递简单参数是没问题的，上级页面携带复杂的url编码参数时，就是报这个错误

**Comment by rmd1710714107** [comment]
有解决办法吗，我也遇到了
