### ISSUE TITLE
跳转多次页面回退到首页时，功能上能正常回退，但路由列表里还残留之前的记录

### ISSUE THREAD

**Issue by chensan33** [SilurianYang/uni-simple-router#379]
**问题描述**
从首页->页面A->页面B->页面C，回退到首页时，可以正常回退，但是getCurrentPages方法获取到的路由列表残留着页面B的记录

**复现步骤**
[复现问题的步骤]
1. 启动应用，从首页跳转到页面A
2. 点击按钮从页面A跳转到页面B
3. 点击按钮从页面B跳转到页面C
4. 调用navigateBack从页面C回退到首页
5. 首页onShow打印getCurrentPages(),发现路由列表残留着页面B的记录

[或者可以直接贴源代码]

**预期结果**
从页面C回退到首页后，getCurrentPages方法获取到的路由列表只留着首页的记录

**实际结果**
![image](https://user-images.githubusercontent.com/63626787/161257404-bd5ef900-1da1-4108-96a1-65aba4d50b1d.png)
![image](https://user-images.githubusercontent.com/63626787/161257499-6925d064-d5e8-4552-b95b-697b55ff433a.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: 浏览器，微信开发者工具
 - HBuilderX版本: 3.3.13
 - 项目创建方法: HBuilderX创建
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 2.0.7

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
你好，我希望你能提供一个可复现的demo，这样我能直接在最短时间内帮你定位问题

**Comment by chensan33** [comment]
不好意思回复晚了，demo已通过附件发送给你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilurianYang/uni-simple-router"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月3日(星期天) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SilurianYang/uni-simple-router] 跳转多次页面回退到首页时，功能上能正常回退，但路由列表里还残留之前的记录 (Issue #379)





 
你好，我希望你能提供一个可复现的demo，这样我能直接在最短时间内帮你定位问题
