### ISSUE TITLE
报错“TypeError: Cannot read property '__id__' of undefined”

### ISSUE THREAD

**Issue by PineSongCN** [SilurianYang/uni-simple-router#38]
**Describe the bug**
报错
TypeError: Cannot read property '__id__' of undefined

**To Reproduce**
1. 按照文档部署
2. 报错如图所述，页面直接报错不挂载。
4. 如果屏蔽掉 router/index.js 里的Vue.use(Router)，__id__报错消失

**Expected behavior**
正常使用

**Screenshots**
![image](https://user-images.githubusercontent.com/39976617/68734884-e341aa00-0616-11ea-84e3-fbf56aebf3c7.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser 内置浏览器
 - Version 最新

**Comment by SilurianYang** [comment]
修改了 `manifest.json` 中 `mode:history` 的问题 先占时改成  `hash`  问题已在修复中

**Comment by MrXieH** [comment]
![image](https://user-images.githubusercontent.com/28506210/69038488-dfea5c00-0a24-11ea-9221-7081ae6b4b81.png)
没有__id__错误后，h5访问白屏

**Comment by SilurianYang** [comment]
参考快速上手&nbsp;&nbsp;http://hhyang.cn/src/router/start/quickstart.html
第3步、配置main.js









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr.X"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 下午5:01
收件人: "SilurianYang/uni-simple-router"<uni-simple-router@noreply.github.com&gt;; 
抄送: "混世大魔王&amp;#x1F449;&amp;#x1F353;&amp;#x1F353;&amp;#x1F353;"<1606726660@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [SilurianYang/uni-simple-router] 报错“TypeError: Cannot read property &#39;__id__&#39; of undefined” (#38)





 没有__id__错误后，h5访问白屏

**Comment by MrXieH** [comment]
routes path 需要加'/'
