### ISSUE TITLE
Nvue 项目 beforeEnter 未触发

### ISSUE THREAD

**Issue by coolxiaohao** [SilurianYang/uni-simple-router#381]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```js
pages.json
{
"pages": [ //pages数组中第一项表示应用启动页，参考：https://uniapp.dcloud.io/collocation/pages
		// #ifdef APP-PLUS
		{
			"path": "pages/main/index"
		},
		// #endif
		{
			"name": "login",
			"path": "pages/login/index",
			"style": {
				"navigationBarTitleText": "登录",
				"app-plus": {
					"navigationStyle": "custom",
					"titleNView": false
				}
			}
		},
		{
			"name": "home",
			"path": "pages/index/index",
			"style": {	
				"navigationBarTitleText": "首页",
				"app-plus": {
					"navigationStyle": "custom",
					"titleNView": false
				}
			}
		}, {
			"name": "mine",
			"path": "pages/mine/index",
			"style": {
				"navigationBarTitleText": "我的",
				"app-plus": {
					"navigationStyle": "custom",
					"titleNView": false
				}
			}
		},
		// TODO 测试页
		{
			"name": "test",
			"path": "pages/test/index",
			"style": {
				"navigationBarTitleText": "测试"
				// "app-plus": {
				// 	"navigationStyle": "custom",
				// 	"titleNView": false
				// }
			}
		}
	]
}

router.js

import {
	RouterMount,
	createRouter
} from 'uni-simple-router';

const routeHooks = {
	'/pages/main/index': {
		beforeEnter: (to, from, next) => {
			next({
				name: 'home',
				NAVTYPE: 'replaceAll'
			})
		}
	}
}

const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,
	APP: {
		//设置等待页面背景色
		loadingPageStyle: () => JSON.parse('{"backgroundColor":"#96DBF3"}'),
		// 通过启动页生命钩子绘制加载gif
		loadingPageHook: (view) => {
			console.log('------------loadingPageHook--------------')
			view.hide();
		},
		launchedHook: () => {
			console.log('------------launchedHook--------------')
			plus.navigator.closeSplashscreen();
			view.show()
		},
	},
	routes: ROUTES.map(route => {
		if (routeHooks[route.path]) {
			return Object.assign({}, route, routeHooks[route.path])
		}
		return route
	})
});

//全局路由前置守卫
router.beforeEach((to, from, next) => {
	console.log('to=======>', to)
	next();
});

// 全局路由后置守卫
router.afterEach((to, from) => {
	console.log('跳转结束')
})

export {
	router,
	RouterMount
}
```

**预期结果**
跳转到首页

**实际结果**
![simulator_screenshot_781A6E6E-9C07-44BA-907C-EE1BB948CDD3](https://user-images.githubusercontent.com/46562305/161887420-af74733d-da1a-4ddc-8ed1-4fa47015a40d.png)

**系统信息:**
 - IPhone 13 Pro 模拟器
 - uni-simple-router 2.0.8-beta.4

**补充信息**
未开启fast启动模式和纯nvue
![image](https://user-images.githubusercontent.com/46562305/161887253-0dd49b8e-3453-4a50-a79c-e810fa24c689.png)

**Comment by SilurianYang** [comment]
`pages/main/index`  这个是vue文件还是Nvue 文件？

**Comment by coolxiaohao** [comment]
> 

vue 文件

**Comment by coolxiaohao** [comment]
> `pages/main/index` 这个是vue文件还是Nvue文件？

vue

**Comment by coolxiaohao** [comment]
> `pages/main/index` 这个是vue文件还是Nvue文件？

![image](https://user-images.githubusercontent.com/46562305/161916323-3c362ecc-781d-4f04-933d-644edfeea7c7.png)

**Comment by SilurianYang** [comment]
![image](https://user-images.githubusercontent.com/31280665/161917936-34ed3745-d689-4be5-85d6-a7b44de3fdb8.png)
是因为其他报错引起的吗？

**Comment by coolxiaohao** [comment]
> ```js
> 
> ```
不是的 我注释掉后重新编译运行 还是一样白屏，并且控制台无任何报错：
![image](https://user-images.githubusercontent.com/46562305/161919405-f7636169-2117-4f15-9890-ae11a4f97f90.png)
![image](https://user-images.githubusercontent.com/46562305/161919640-a2d80b13-026e-44c4-9577-e7afd16a1bf4.png)

**Comment by SilurianYang** [comment]
方便把DEMO发送给我吗？ 我现在方便调试

**Comment by SilurianYang** [comment]
1606726660@qq.com

**Comment by SilurianYang** [comment]
两处错误

1、不能定义app.vue  `<template></template>`  必须要用uni-app内置的挂载，否则uni-app本身就会白屏
2、必须为 app.vue 定义 `mpType = 'app'`  你可以在app.vue中导出，也可以在main.js中指定

![image](https://user-images.githubusercontent.com/31280665/161925601-599d6af9-a833-4916-984d-48058156430b.png)
![image](https://user-images.githubusercontent.com/31280665/161925730-e0d42098-e664-4685-ad6f-2dd87b268e0c.png)

**Comment by coolxiaohao** [comment]
> 两处错误
> 
> 1、不能定义app.vue `<template></template>` 必须要用uni-app内置的挂载，否则uni-app本身就会白屏 2、必须为 app.vue 定义 `mpType = 'app'` 你可以在app.vue中导出，也可以在main.js中指定
> 
> ![image](https://user-images.githubusercontent.com/31280665/161925601-599d6af9-a833-4916-984d-48058156430b.png) ![image](https://user-images.githubusercontent.com/31280665/161925730-e0d42098-e664-4685-ad6f-2dd87b268e0c.png)

好的，傻了，谢谢大佬
