### ISSUE TITLE
2.0.8-beta对比2.0.7的问题

### ISSUE THREAD

**Issue by guigui0326** [SilurianYang/uni-simple-router#384]
2.0.8模拟器/真机上运行，带原生tabbar的项目，首页会加载两次，h5端是正常加载一次。测试使用2.0.7真机和h5都没有出现这个问题，请问这是怎么回事呢？

**Comment by SilurianYang** [comment]
这个是为了修复带Tabbar在不同渲染引擎下都能正常展示的BUG。[你可以这样写来避免触发两次生命周期的问题](https://hhyang.cn/v2/start/app/explian.html#nvue%E5%90%AF%E5%8A%A8%E9%A1%B5)

https://github.com/SilurianYang/uni-simple-router/blob/a17013f32bf3d0519b13c7aef37783fa5e255db4/src/app/appPatch.ts#L43-L64

**Comment by guigui0326** [comment]
感觉这种方式不是很合理，通过页面去跳转，我现在切到2.0.7版本了

**Comment by SilurianYang** [comment]
首先不做这个处理，会面临的情况将是，页面正常打开并且生命周期正常执行，但是**无法渲染**。当你的项目中含有NVUE作为启动页或者是Tabbar页那么不得不制作一个vue的空白启动，由 `webview`  过渡到 `weex` 引擎。 这是我目前找到的唯一能解决这个问题的方案，如果你有更好的方案可以提交或者一起讨论

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
