### ISSUE TITLE
微信小程序无法正确传递腾讯位置插件的参数

### ISSUE THREAD

**Issue by ariwori** [SilurianYang/uni-simple-router#387]
**问题描述**

```js

const key = ''; //使用在腾讯位置服务申请的key
const referer = ''; //调用插件的app的名称
const location = JSON.stringify({
  latitude: 39.89631551,
  longitude: 116.323459711
});
const category = '生活服务,娱乐休闲';
 
wx.navigateTo({
  url: 'plugin://chooseLocation/index?key=' + key + '&referer=' + referer + '&location=' + location + '&category=' + category
});
```

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by ariwori** [comment]
经过路由始终会包多一个query，插件那边就无法正确读取参数

**Comment by SilurianYang** [comment]
#### 插件自身处理参数优先满足大多情况，你的情况可以使用自定义参数, 像这样：

```js
const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	resolveQuery:(options)=>options,
	parseQuery:({
		query={}
	})=>{
		for(let key in query){
			query[key]=decodeURIComponent(query[key])
		}
		return query;
	},
	routes: [...ROUTES],
});

```

**Comment by ariwori** [comment]
> #### 插件自身处理参数优先满足大多情况，你的情况可以使用自定义参数, 像这样：
> ```js
> const router = createRouter({
> 	platform: process.env.VUE_APP_PLATFORM,  
> 	resolveQuery:(options)=>options,
> 	parseQuery:({
> 		query={}
> 	})=>{
> 		for(let key in query){
> 			query[key]=decodeURIComponent(query[key])
> 		}
> 		return query;
> 	},
> 	routes: [...ROUTES],
> });
> ```

感谢！不过我发现`decodeURIComponent`并没有解码，因为腾讯位置插件接受的是未编码的中文，编码过的中文无法识别会变成下面的样子

[![LRy260.png](https://s1.ax1x.com/2022/04/22/LRy260.png)](https://imgtu.com/i/LRy260)

暂时是先舍弃了可选的中文参数
