### ISSUE TITLE
keepUniOriginNav: true时，APP端无法正常跳转

### ISSUE THREAD

**Issue by bmxy860815** [SilurianYang/uni-simple-router#388]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
已有项目中引入uni-simple-router, 为减少原来不需要路由守卫的模块修改，启用了keepUniOriginNav的选项，H5端表现正常，APP-PLUS环境无法正常跳转

**复现步骤**
[复现问题的步骤]
1. 按照文档步骤引入uni-simple-router
2. 运行项目，ios端白屏，andriod端可进入首页，但点击跳转无反应，控制台无报错信息
3. 再次点击时报跳转中错误

[或者可以直接贴源代码]

**预期结果**
uni.navigateTo走框架的路由跳转
this.$Router.push 会有路由守卫且正常完成跳转

**实际结果**
[这里请贴上你的报错截图或文字]
uni.navigateTo正常
this.$Router.push 时 会走到beforeEach ，但会卡主无法完成跳转
![image](https://user-images.githubusercontent.com/16871452/164366651-ed3260e5-2b9d-4195-a31c-1b21d5965273.png)

**系统信息:**
 - 发行平台: APP-PLUS
 - 操作系统 ：iOS 15.4 , HarmonyOS 2.0.0
 - HBuilderX版本 3.4.6.20220420, 3.3
 - 项目创建方法 HBuilderX
 - 设备信息 iPhone8 Plus , Mate40Pro
 - uni-simple-router版本 2.0.7 和2.0.8-beta4均有此问题

**补充信息**
keepUniOriginNav为false时表现正常，但由于无法支持相对路径，修改点较多，故期望保留原生跳转方式

**Comment by SilurianYang** [comment]
`keepUniOriginNav` 到目前为止 这个参数是内部使用的，并没有启到任何作用。所以目前关闭是一定会报错的。保留以下配置

```js
keepUniOriginNav:false
```

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
