### ISSUE TITLE
希望可以配置取消路由锁

### ISSUE THREAD

**Issue by xfstu** [SilurianYang/uni-simple-router#389]
**新功能描述**
希望可以选择取消路由锁的配置

**现状及问题**
路由锁导致onBackPress不能使用，虽然可以强制解锁，但是在我的代码中，会导致闪屏，非常影响体验。代码不方便贴，大概逻辑是
启动APP，判断是否登录，没有登录则跳转到登录页面，跳转完成后，突然会白屏闪了一下（太快了，看不清是否白屏）。如果关掉强制路由锁就不会触发闪屏了。如果使用优雅解锁，点击返回后，不会立马返回，console打印”当前页面正在跳转...”，再按一次才会退回去，也影响体验。**不过也应该不是路由锁的原因，但是可以的话还是建议可以配置是否启用路由锁**

**尝试方案**
找不到其他代替方案

**补充信息**
是否可以配置成：是否启用路由锁

**Comment by SilurianYang** [comment]
强制解锁就等于没有路由锁

app 端 你可以这样配置

```js
"splashscreen" : {
    "alwaysShowBeforeRender" : false,
    "waiting" : true,
    "autoclose" : false,
    "delay" : 0
}
```
[打包后可能出现闪屏](https://hhyang.cn/v2/start/app/start.html#%E6%89%93%E5%8C%85%E5%90%8E%E5%8F%AF%E8%83%BD%E5%87%BA%E7%8E%B0%E9%97%AA%E5%B1%8F)

**Comment by xfstu** [comment]
> 强制解锁就没有路径锁
> 
> app端你可以这样配置
> 
> ```js
> “启动画面”：{ 
>     “alwaysShowBeforeRender”：假，
>     “等待”：真，
>     “自动关闭”：假，
>     “延迟”：0 
> }
> ```
> 
> [打包后可能出现闪屏](https://hhyang.cn/v2/start/app/start.html#%E6%89%93%E5%8C%85%E5%90%8E%E5%8F%AF%E8%83%BD%E5%87%BA%E7%8E%B0%E9%97%AA%E5%B1%8F)

谢谢大哥，没有经验写的太伤脑经了，泪目
