### ISSUE TITLE
外部直接跳转进来的页面，比如： http://localhost:8080/#/pages/wechat/callback?code=1&state=2， url直接把参数丢掉了。获取不到code和state，导致微信跳转出现了问题，H5平台

### ISSUE THREAD

**Issue by 850817673** [SilurianYang/uni-simple-router#391]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hzh1990** [comment]
<img width="1781" alt="mmexport1652651111287" src="https://user-images.githubusercontent.com/4394948/168495170-1b9cb029-999c-401d-9e47-3a7484e44766.png">
<img width="1222" alt="mmexport1652651115309" src="https://user-images.githubusercontent.com/4394948/168495180-dd295804-8dbe-440d-964b-331945c46287.png">

难吗？

**Comment by SilurianYang** [comment]
什么版本的插件？

**Comment by 850817673** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilurianYang/uni-simple-router"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 凌晨5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SilurianYang/uni-simple-router] 外部直接跳转进来的页面，比如： http://localhost:8080/#/pages/wechat/callback?code=1&amp;state=2， url直接把参数丢掉了。获取不到code和state，导致微信跳转出现了问题，H5平台 (Issue #391)





 

 

 
难吗？
