### ISSUE TITLE
onBeforeBack中不能修改路由

### ISSUE THREAD

**Issue by ytg2097** [SilurianYang/uni-simple-router#396]
**问题描述**
安卓app中使用onBeforeBack钩子监听返回键，触发之后调用router.push()或router.replaceAll不生效
**复现步骤**
[复现问题的步骤]

onBeforeBack(){
     this.$Router.replaceAll({name:"index"})
}

**预期结果**
监听安卓返回键，预期不返回上一页，而是直接回到主页

**实际结果**
没有回到主页，依然返回上一页

**系统信息:**
 - 发行平台: 安卓App
 - 操作系统  Android 7.0
 - HBuilderX版本 HbuilderX 3.3.13.2022.314
 - 项目创建方法 vue-cli
 - 设备信息 优博讯i610
 - uni-simple-router版本 v1.5.5

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
使用路由离开守卫  beforeRouteLeave
