### ISSUE TITLE
前置路由拦截跳转时替换路由历史

### ISSUE THREAD

**Issue by jngxx** [SilurianYang/uni-simple-router#397]
**问题描述**
pages.json第一个页面是首页，前置路由拦截判断token，未登录则跳转到登录页，此时不登录，在手机上侧滑会返回到首页。

**复现步骤**
_router.beforeEach((to, from, next) => {
	let token=uni.getStorageSync(ACCESS_TOKEN);
	if(token){
		 next()
	}else{
		if (whiteList.indexOf(to.path) !== -1) {
		  next()
		}else{
		  next({ path: '/pages/login/login', replace: true})
		}
	} 
})_

**预期结果**
用户不登录不能进入到首页，我希望在跳转'/pages/login/login'时替换掉路由记录中的'/pages/index/index'，但是replace: true不起作用。

**系统信息:**
 - 发行平台: [uniapp]
 - 操作系统 [Android 11]
 - HBuilderX版本 [HBuilderX 3.4.7]
 - 项目创建方法 [HBuilderX]
 - 设备信息 [OPPO]
 - uni-simple-router版本 [v1.5.5]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
使用参数NAVTYPE代替replace
