### ISSUE TITLE
uni.previewImage点击遮罩返回以后 上个页面会滚动到顶部

### ISSUE THREAD

**Issue by xuyongweb** [SilurianYang/uni-simple-router#398]
**问题描述**
[我现在做朋友圈的功能，我朋友圈滑到底部然后用previewImage预览图片，到了这个preview-image页面，然后点击遮罩层自动返回，朋友圈就回到顶部了，我看原生uniapp是回到页面，页面不变化的]

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[回到朋友圈列表还在当前预览的位置，而不是回到顶部了]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
你可以在这里查看到详细的[默认配置](https://hhyang.cn/v2/start/cross/match.html#%E9%BB%98%E8%AE%A4%E7%9A%84%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE)
``` js
 scrollBehavior: (to:any, from:any, savedPostion:Function) => ({ x: 0, y: 0 }),
```
你可以这样定义你的滚动目标
```js
// router.js
import {RouterMount,createRouter} from 'uni-simple-router';

const scrollInfo={};

const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	routes: [...ROUTES],
	h5:{
		scrollBehavior:(to, from, savedPosition)=>{
			const XY=scrollInfo[to.path];
			if(XY){
				return XY;
			}
			return savedPosition;
		}
	}
});
//全局路由前置守卫
router.beforeEach((to, from, next) => {
	if(from.meta.keepScroll===true){
		scrollInfo[from.path]={
			x:window.scrollX,
			y:window.scrollY
		}
	}
	next();
});
// 全局路由后置守卫
router.afterEach((to, from) => {
    console.log('跳转结束')
})

export {
	router,
	RouterMount
}
```

[详细的demo地址在这里](https://github.com/SilurianYang/uni-simple-router/blob/master/examples/h5-scrollTo-demo.zip)
