### ISSUE TITLE
跳转传递参数与实际不一致

### ISSUE THREAD

**Issue by Luomigu** [SilurianYang/uni-simple-router#4]
测试环境 h5  传一个多层对象的话，会被合并成一个一层对象 结果与传递的不一致

**Comment by SilurianYang** [comment]
> 测试环境 h5 传一个多层对象的话，会被合并成一个一层对象 结果与传递的不一致

很抱歉！截止目前版本在传递深度对象时统一把他扁平成一个大对象。是这样设计的，貌似确实有很多的不妥[路由传参](http://hhyang.cn/doc7/#anchor3)。对于此问题将会再下一个版本改进
