### ISSUE TITLE
yarn build上线运行报错

### ISSUE THREAD

**Issue by hdtopku** [SilurianYang/uni-simple-router#404]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
开发环境使用正常，上线后，打开页面浏览器报如下错误
```
chunk-vendors.8c9100ba.js:39 Uncaught TypeError: Cannot set properties of undefined (setting 'default')
    at o (chunk-vendors.8c9100ba.js:39:10)
    at index.c75ab64a.js:1:32648
    at index.c75ab64a.js:1:33475
    at 3f72 (index.c75ab64a.js:1:33939)
    at d (index.c75ab64a.js:1:812)
    at 813e (index.c75ab64a.js:1:82230)
    at d (index.c75ab64a.js:1:812)
    at 56d7 (index.c75ab64a.js:1:38257)
    at d (index.c75ab64a.js:1:812)
    at 0 (index.c75ab64a.js:1:2531)
```

**复现步骤**
[复现问题的步骤]
yarn dev正常运行，yarn build上线后报如上错误

[或者可以直接贴源代码]
router.js
```
// router.js
import {
  RouterMount,
  createRouter
} from 'uni-simple-router';
const scrollInfo = {};

const router = createRouter({
  platform: process.env.VUE_APP_PLATFORM,
  routes: [...ROUTES,
    // {
    //   path: '*',
    //   redirect: (to) => {
    //     return {
    //       name: 'index'
    //     }
    //   }
    // },
  ],
  h5: {
    scrollBehavior: (to, from, savedPosition) => {
      const XY = scrollInfo[to.path];
      if (XY) {
        return XY;
      }
      return savedPosition;
    }
  }
});
//全局路由前置守卫
router.beforeEach((to, from, next) => {
  if (from.meta.keepScroll === true) {
    scrollInfo[from.path] = {
      x: window.scrollX,
      y: window.scrollY
    }
  }
  next();
});
// 全局路由后置守卫
router.afterEach((to, from) => {})

export {
  router,
  RouterMount
}

```

vue.config.js
```
//vue.config.js
const TransformPages = require('uni-read-pages')
const {
  webpack
} = new TransformPages()
module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.DefinePlugin({
        ROUTES: webpack.DefinePlugin.runtimeValue(() => {
          const tfPages = new TransformPages({
            includes: ['path', 'name', 'aliasPath', 'meta']
          });
          return JSON.stringify(tfPages.routes)
        }, true)
      })
    ],
    performance: {
      hints: 'warning',
      // 入口起点的最大体积
      maxEntrypointSize: 50000000,
      // 生成文件的最大体积
      maxAssetSize: 30000000,
      // 只给出 js 文件的性能提示
      assetFilter: function(assetFilename) {
        return assetFilename.endsWith('.js')
      }
    }
  },
  transpileDependencies: ['uni-simple-router']
}

```

main.js
```
import {router,RouterMount} from './router.js'  //路径换成自己的
Vue.use(router)

//v1.3.5起 H5端 你应该去除原有的app.$mount();使用路由自带的渲染方式
// #ifdef H5
RouterMount(app,router,'#app')
// #endif

// #ifndef H5
app.$mount(); //为了兼容小程序及app端必须这样写才有效果
// #endif
```

pages.json
```
"pages": [ //pages数组中第一项表示应用启动页，参考：https://uniapp.dcloud.io/collocation/pages
  {
    "path": "pages/index/index",
    "aliasPath": "/index",
    "name": "index",
    "meta": {
      "keepScroll": true
    },
    "style": {
      "navigationBarTitleText": "uni-app"
    }
  }, {
      "path": "pages/test/test",
      "aliasPath": "/test/:id",
      "name": "test",
      "meta": {
        "keepScroll": true
      },
      "style": {
        "navigationBarTitleText": "",
        "enablePullDownRefresh": false
      }
    }
  ]
```
test.vue
```
<template>
<view>
  <div class="item" v-for="(item,index) in 10" :key="index">{{item}}</div>
  </view>
</template>

<script>
  export default {
    data() {
      return {
        
      }
    },
    onLoad(...options) {
      //  自己打印来看看咯
      console.log(options)
      console.log(this.$Route)
    },
    methods: {
      
    }
  }
</script>

<style>
  .item {
    height: 200rpx;
    background-color: #F0AD4E;
    margin-bottom: 30rpx;
  }
</style>

```

**预期结果**
yarn build能正常运行

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/14859466/173007489-db268773-9a08-4c12-8905-56c4b888c434.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: mac10.15.7、及手机端均报错
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]：3.4.14.20220607
 - 项目创建方法 [使用Vue-cli创建]
 - 设备信息 [如iphone6s、华为手机、安卓手机均白屏]
 - uni-simple-router版本 [^2.0.5]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
yarn dev正常， yarn build也没报错，打开页面时报错，也没有错误提示，猜不到原因
```
chunk-vendors.8c9100ba.js:39 Uncaught TypeError: Cannot set properties of undefined (setting 'default')
    at o (chunk-vendors.8c9100ba.js:39:10)
    at index.c75ab64a.js:1:32648
    at index.c75ab64a.js:1:33475
    at 3f72 (index.c75ab64a.js:1:33939)
    at d (index.c75ab64a.js:1:812)
    at 813e (index.c75ab64a.js:1:82230)
    at d (index.c75ab64a.js:1:812)
    at 56d7 (index.c75ab64a.js:1:38257)
    at d (index.c75ab64a.js:1:812)
    at 0 (index.c75ab64a.js:1:2531)
```

**Comment by SilurianYang** [comment]
升级到新版本插件试试呢？或者给我一个可访问的地址 我排查下

**Comment by hdtopku** [comment]
> 升级到新版本插件试试呢？或者给我一个可访问的地址 我排查下

地址：https://am.taojingling.cn/pages/test/test?c=q2yra

**Comment by SilurianYang** [comment]
我可以正常访问
![Snipaste_2022-06-10_17-01-11](https://user-images.githubusercontent.com/31280665/173030909-53bcca73-a777-41c2-9635-1555f374cc7d.png)

**Comment by hdtopku** [comment]
> 我可以正常访问 ![Snipaste_2022-06-10_17-01-11](https://user-images.githubusercontent.com/31280665/173030909-53bcca73-a777-41c2-9635-1555f374cc7d.png)

我刚刚切换了，我现在切换过来，你再访问一下

**Comment by SilurianYang** [comment]
还是可以访问呀

**Comment by hdtopku** [comment]
我现在切换回去了，你现在访问一下，就报错了

**Comment by hdtopku** [comment]
> 还是可以访问呀

你再访问一下，现在就有报错了

**Comment by SilurianYang** [comment]
请把项目发我  我现在排查

**Comment by hdtopku** [comment]
> 请把项目发我 我现在排查

好的，稍等，马上

**Comment by hdtopku** [comment]
> 请把项目发我 我现在排查

代码已发

https://t.wss.ink/f/8izbbrk3rxp 复制链接到浏览器打开

**Comment by hdtopku** [comment]
nginx配置

```
server {
    listen 443 ssl;
    server_name am.taojingling.cn;
    location / {
        if ($request_filename ~* .*\.(?:htm|html)$) {
          add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
          access_log on;
        }
        root  /usr/share/nginx/html/uni-shop;
        index  index.html index.htm;
        try_files  $uri $uri/ /index.html;
    }
}
```

**Comment by SilurianYang** [comment]
你玩我呢？ 

```js
    {
      "path": "pages/test/test",
      "aliasPath": "/test/:id",
      "style": {
        "navigationBarTitleText": "",
        "enablePullDownRefresh": false
      }
    }
```


你的访问路径应该为  https://am.taojingling.cn/test/xxx?xxx=xxx

**Comment by hdtopku** [comment]
你好，不要生气。你说的问题是路径不存在
你再访问一下，线上：[https://am.taojingling.cn/test/xxx](https://am.taojingling.cn/test/xxx)
报错信息如下，并不是你说的我访问路径不对导致的报错：
```
chunk-vendors.8c9100ba.js:39 Uncaught TypeError: Cannot set properties of undefined (setting 'default')
    at o (chunk-vendors.8c9100ba.js:39:10)
    at index.20505a3e.js:1:32648
    at index.20505a3e.js:1:33475
    at 3f72 (index.20505a3e.js:1:33939)
    at d (index.20505a3e.js:1:812)
    at 813e (index.20505a3e.js:1:82230)
    at d (index.20505a3e.js:1:812)
    at 56d7 (index.20505a3e.js:1:38257)
    at d (index.20505a3e.js:1:812)
    at 0 (index.20505a3e.js:1:2531)
```

**Comment by hdtopku** [comment]
> nginx.conf

感谢，你这个确实没问题，应该是我的问题，今天我排查一下，找出原因我在这里反馈。

**Comment by hdtopku** [comment]
可能的原因：js文件超过500kb，已跳过压缩以及 ES6 转 ES5 的处理，导致es6语法存在兼容性问题，所以可能要先解决js文件过大的问题。并非uni-simple-router的bug

```
警告⚠] `../node_modules/@dcloudio/uni-h5/dist/index.umd.min.js` 文件体积超过 500KB，已跳过压缩以及 ES6 转 ES5 的处理，手机端使用过大的js库影响性能。
```

**Comment by SilurianYang** [comment]
不会因为这个东西导致了  可能是你nginx的问题   你先排查hash是否正常

**Comment by hdtopku** [comment]
> 不会因为这个东西导致了 可能是你nginx的问题 你先排查hash是否正常

不是nginx的问题，好像是和uview冲突了。
以下代码，本地也可以复现这个错误了。

https://t.wss.ink/f/8j31ia78a19 复制链接到浏览器打开

1、yarn
2、hbuilderx运行
然后打开：[http://localhost:8080/test/test](http://localhost:8080/test/test)


![复现图片](https://article.biliimg.com/bfs/article/82c97effdc603c4f4b032597d47fbbabfb72d7f2.png)

**Comment by hdtopku** [comment]
> 不会因为这个东西导致了 可能是你nginx的问题 你先排查hash是否正常

不是nginx的问题，好像是和uview冲突了。
以下代码，本地也可以复现这个错误了。

https://t.wss.ink/f/8j31ia78a19 复制链接到浏览器打开

1、yarn
2、hbuilderx运行
然后打开：[http://localhost:8080/test/test](http://localhost:8080/test/test)


![复现图片](https://article.biliimg.com/bfs/article/82c97effdc603c4f4b032597d47fbbabfb72d7f2.png)

**Comment by SilurianYang** [comment]
好的 明天我会查看  刚关电脑

**Comment by SilurianYang** [comment]
我测试了你的新包  没有任何问题，请你换个浏览器 或者清除缓存重新打开试试  再不行重启电脑

**Comment by hdtopku** [comment]
> 我测试了你的新包 没有任何问题，请你换个浏览器 或者清除缓存重新打开试试 再不行重启电脑

重启、换浏览器还是一样有问题
![图片](https://article.biliimg.com/bfs/article/e34617cdf757b166dbc2ac947b652b2aa68ac748.png)

**Comment by SilurianYang** [comment]
现在的问题看起来和插件没有任何关系  你应该排查 Babel  或者环境问题

**Comment by hdtopku** [comment]
> 现在的问题看起来和插件没有任何关系 你应该排查 Babel 或者环境问题

好的，我看看环境的问题，找到问题再回来反馈，感谢。

**Comment by hdtopku** [comment]
git打不开，用qq邮箱回复了。
[参考](https://www.wolai.com/mingyong-g/3A9s9kLepCn9r46kG8YW4z)
因为我是vue-cli创建的uniapp项目，babel存在兼容性问题
注释掉babel.config.js中的modules: 'commonjs'，错误消失，程序正常启动





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月11日(星期六) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [SilurianYang/uni-simple-router] yarn build上线运行报错 (Issue #404)





 
现在的问题看起来和插件没有任何关系  你应该排查 Babel  或者环境问题
 
&mdash;

**Comment by hdtopku** [comment]
好的，辛苦，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月11日(周六) 凌晨2:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [SilurianYang/uni-simple-router] yarn build上线运行报错 (Issue #404)




 
好的 明天我会查看  刚关电脑
