### ISSUE TITLE
请问如何在其他js中获取当前页面路径？

### ISSUE THREAD

**Issue by xlkit456852** [SilurianYang/uni-simple-router#405]
**问题描述**
我希望在我的请求接口公共逻辑中（request.js），保存当前的路径作后续用，之前写原生vue使用vue-router时，可以用router.$route.currentRoute.fullPath;获取，但使用uni-app时发现$route为null

**复现步骤**
[复现问题的步骤]
1.router.js中初始化
```
import modules from './modules'
import Vue from 'vue'
import {RouterMount,createRouter} from 'uni-simple-router'
const router = createRouter({
 platform: process.env.VUE_APP_PLATFORM,
 routes: [...modules]
})
router.beforeEach((to, from, next) => {
next()
})
router.afterEach((to, from) => {
})
Vue.use(router);
export {
router,
RouterMount
}
```

2、request.js中引入router
```
import {
	router
} from '../router/index.js'
```

3、在request.js中使用router
```
var current_path = router.$route.currentRoute.fullPath;
```

**预期结果**
可有获取到当前路径

**实际结果**
报错：
```
MiniProgramError
Cannot read property 'currentRoute' of null
```

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 ：3.3.13
 - 项目创建方法 [HBuilderX]
 - 设备信息 [HBuilderX内置微信小程序启动]
 - uni-simple-router版本 [2.0.0-alpha.1]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
可能是获取的router对象不对？是否有另外的对象存储了当前的页面路径？

**Comment by SilurianYang** [comment]
```js
router.currentRoute
```

**Comment by xlkit456852** [comment]
> ```js
> router.currentRoute
> ```

刚试了下，没有这个currentRoute属性

**Comment by SilurianYang** [comment]
麻烦升级到最新版

**Comment by xlkit456852** [comment]
> 麻烦升级到最新版

好的，可以了谢谢
