### ISSUE TITLE
typescript+vuecli报错TypeError: Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by xieyu376** [SilurianYang/uni-simple-router#406]
**问题描述**
![image](https://user-images.githubusercontent.com/49941248/176343149-0029bf8f-9be4-4d0c-bc0e-9cfb87dc20ff.png)
![image](https://user-images.githubusercontent.com/49941248/176343280-5f8f364f-91c8-4892-9b5f-22be22db42aa.png)

**复现步骤**
[复现问题的步骤]
1. router.ts如下
![image](https://user-images.githubusercontent.com/49941248/176344532-2ff968c5-2244-4afe-9b03-e7b76a463314.png)

2.pages.json如下
![image](https://user-images.githubusercontent.com/49941248/176344709-0602c961-76cc-4ce9-837f-5dff335621ef.png)

**系统信息:**
 - 发行平台: H5
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - VSCode
 - 项目创建方法: vue-cli
 - uni-simple-router版本: 2.0.7

**补充信息**
![image](https://user-images.githubusercontent.com/49941248/176344034-b368e69f-4d87-42e7-9384-830bae041d32.png)

**Comment by xieyu376** [comment]
解决了，main.ts里要这样
![image](https://user-images.githubusercontent.com/49941248/176363566-ade53116-ffe2-4292-9b41-fb093c100013.png)
，不能全按照文档说明的这种
`const app = new Vue({
    ...App
})`
写法来

**Comment by szq233** [comment]
好家伙，原来是这样解决的！

**Comment by 348800199** [comment]
good job

**Comment by heweicong** [comment]
> 解决了，main.ts里要这样 ![image](https://user-images.githubusercontent.com/49941248/176363566-ade53116-ffe2-4292-9b41-fb093c100013.png) ，不能全按照文档说明的这种 `const app = new Vue({ ...App })` 写法来

为啥我在router.ts ROURES未定义 编译不过

**Comment by imaxing** [comment]
我这么写不得行, 还是报错

![image](https://user-images.githubusercontent.com/26427785/195241764-0c19d1c2-bb1a-41bc-8f37-e228a3ddfc5c.png)

![image](https://user-images.githubusercontent.com/26427785/195241584-2cd86936-4baf-4430-98ca-606ea4b114f1.png)
