### ISSUE TITLE
u-view2不兼容

### ISSUE THREAD

**Issue by zccl** [SilurianYang/uni-simple-router#416]
![image](https://user-images.githubusercontent.com/22192098/181181951-3408750e-90ff-45a0-ac80-0525564f6d3a.png)

h5 vueRouterDev: true, //完全使用vue-router开发

打开两个不同的项目 都是报错这个 同时安装u-vuew2 和 uni-simple-router时就导致UI组件显示异常

**Comment by zccl** [comment]
@SilurianYang 这个能不能看看啥问题 就是我想在H5完全使用vue-router开发 但是只要安装了u-view2就会导致报错 不好使

**Comment by zccl** [comment]
vueRouterDev: true 时就会报错 @SilurianYang @472647301

**Comment by zccl** [comment]
因为有个需求需要嵌套路由的方式 我要确定这个插件可以使用 不然我得还一个方式开发了 然后之前两个星期的工作就白费了 实在不想放弃 但是我又不知道怎么改正 找了一天的办法诶 无果！ @SilurianYang @472647301

**Comment by zccl** [comment]
如果看到的话 麻烦回复下是否准备修复这个功能嘞 非常感谢~~ @SilurianYang @472647301

**Comment by zccl** [comment]
就是打开有使用 u-view2组件的时候就报错
![image](https://user-images.githubusercontent.com/22192098/181237348-f64325d9-0874-4d92-8adf-bf4a5ac22302.png)

**Comment by zccl** [comment]
![image](https://user-images.githubusercontent.com/22192098/181244970-39927ae2-d801-40d1-a87b-8dfc7e51ec88.png)
我又试了1.5.3版本也是不行 最新的也不行 都不兼容 u-view2

**Comment by SilurianYang** [comment]
vueRouterDev: true 模式下 uni-app的默认参数和布局会有所变更，开放此模式的初衷是可以快速让vue开发的项目在uni-app下运行

**Comment by zccl** [comment]
所以呢 这个问题可以解决不 我听不懂

**Comment by zccl** [comment]
@SilurianYang 别人用elementUI就可以诶 vueRouterDev: true 这个不打开的话可以使用路由嵌套不 不打开这个我定义的路由不生效 页面白屏

**Comment by zccl** [comment]
我已经选择了用u-view2开发了两周 不得已呀 我需要使用路由嵌套刷新时保持页面状态 @SilurianYang

**Comment by zccl** [comment]
> vueRouterDev: true 模式下 uni-app的默认参数和布局会有所变更，开放此模式的初衷是可以快速让vue开发的项目在uni-app下运行

所以这个你会不会修复它呢 @SilurianYang

**Comment by zccl** [comment]
@SilurianYang 我是真不晓得这个怎么解决 看了又看 各种尝试还是不行 你要是不准备解决的话和我说一呗 我好准备其他对策 谢谢谢谢~

**Comment by SilurianYang** [comment]
这个问题无法修复，因为所有的节点元素和组件都会更新，这将导致uni-app大部分API无法使用。如果选择这个模式，现在我也无能为力，你可以尝试选择非uni-app的UI库使用 [vant-ui](https://vant-ui.github.io/vant/v2/#/en-US/)

**Comment by zccl** [comment]
> 这个问题无法修复，因为所有的节点元素和组件都会更新，这将导致uni-app大部分API无法使用。如果选择这个模式，现在我也无能为力，你可以尝试选择非uni-app的UI库使用 [vant-ui](https://vant-ui.github.io/vant/v2/#/en-US/)

好的 谢谢~
