### ISSUE TITLE
tabbar页面，可以刷新页面，其他页面刷新页面后生命周期也没执行，空白页面

### ISSUE THREAD

**Issue by huimantou** [SilurianYang/uni-simple-router#417]
**问题描述**
tabbar页面，可以刷新页面，其他页面刷新页面后生命周期也没执行，空白页面

**复现步骤**
[复现问题的步骤]
1. 启动 '项目'
2. 点击  浏览器刷新
3. 查看

[或者可以直接贴源代码]

**预期结果**
可以刷新

**实际结果**

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，3.3.5]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v2.0.7]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by huimantou** [comment]
![image](https://user-images.githubusercontent.com/73589906/181412877-ab2bfdbd-8f9f-4143-bb69-762747f696fd.png)

**Comment by huimantou** [comment]
可以执行生命周期 但是页面没有渲染

**Comment by SilurianYang** [comment]
可以贴上你的router代码吗？

**Comment by fox-ghost** [comment]
遇到同样的问题, 如何解决的?

**Comment by fox-ghost** [comment]
> 可以执行生命周期 但是页面没有渲染

遇到同样的问题, 如何解决的?
