### ISSUE TITLE
有支持vue3的打算吗

### ISSUE THREAD

**Issue by yongqiang0621** [SilurianYang/uni-simple-router#418]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zasuNan** [comment]
很需要H5的router-view功能，不然uni开发H5好难受

**Comment by zasuNan** [comment]
很需要H5的router-view功能，不然用uni的vue3+vite开发H5好难受

**Comment by lable** [comment]
是啊，那么好用的东西，能支持vue3就完美了

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/451
