### ISSUE TITLE
官方大大，有计划支持vue3.0吗？ 

### ISSUE THREAD

**Issue by xiaojiangK** [SilurianYang/uni-simple-router#419]
**新功能描述**
官方大大，有计划支持vue3.0吗？

**现状及问题**
项目脚手架计划迁移vue3.0，但是咋们一如既往支持 uni-simple-router2.0 但是目前不支持vue3.0

**补充信息**
希望官方大大 uni-simple-router2.0 支持vue3.0提上日程

**Comment by aimeiyijia** [comment]
源码里面router.ts 中install部分中的Object.defineProperty(Vue.prototype 改为Object.defineProperty(app.config.globalProperties 就基本上可以运行了

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/451
