### ISSUE TITLE
uni-simple-router支持快手小程序吗

### ISSUE THREAD

**Issue by MrRiven** [SilurianYang/uni-simple-router#420]
uni-simple-router支持快手小程序吗

dcloud上平台兼容性显示还不兼容

请问现在是否已经支持快手小程序， 或者作者有意愿什么时候兼容

谢谢

**Comment by SilurianYang** [comment]
请关注 [V3.0](/guide/introduction.html#platform-compatible) 版本，该特性在 [V3.0](/guide/introduction.html#platform-compatible)  版本中可用
