### ISSUE TITLE
Cannot find name 'ROUTES'

### ISSUE THREAD

**Issue by weipo3** [SilurianYang/uni-simple-router#422]
const router = createRouter({
	platform: process.env.UNI_PLATFORM,
	routes: [...ROUTES]
});

sfc.d.ts文件已经加上了声明
import Vue from 'vue'
declare module "vue/types/options" {
  type Hooks = App.AppInstance & Page.PageInstance;
  interface ComponentOptions<V extends Vue> extends Hooks {
    /**
     * 组件类型
     */
    mpType?: string;
  }
}
declare var ROUTES = [];

**Comment by SilurianYang** [comment]
## uni-read-pages 有配置吗？

```js
//vue.config.js
const TransformPages = require('uni-read-pages')
const {webpack} = new TransformPages()
module.exports = {
	configureWebpack: {
		plugins: [
			new webpack.DefinePlugin({
				ROUTES: webpack.DefinePlugin.runtimeValue(() => {
					const tfPages = new TransformPages({
						includes: ['path', 'name', 'aliasPath']
					});
					return JSON.stringify(tfPages.routes)
				}, true )
			})
		]
	}
}
```

**Comment by heweicong** [comment]
> 

有

**Comment by SilurianYang** [comment]
上传一个demo过来我这边排查下

**Comment by whoooami** [comment]
解决了吗？同问
