### ISSUE TITLE
自动构建路由表+路由懒加载

### ISSUE THREAD

**Issue by CPenguo** [SilurianYang/uni-simple-router#426]
**问题描述**
自动构建路由表后,可以配置路由懒加载吗?

**Comment by SilurianYang** [comment]
自动构建路由表 只是方便开发者不用多次配置路由表 仅适用于跨平台的uni-app的
路由懒加载 在h5端可用 但是必须完全使用vue-router开发才可以这样配置 而且默认情况下uni-app官方已经配置成按需加载了的 所有你不用担心这个问题

**Comment by CPenguo** [comment]
> 自动构建路由表 只是方便开发者不用多次配置路由表 仅适用于跨平台的uni-app的 路由懒加载 在h5端可用 但是必须完全使用vue-router开发才可以这样配置 而且默认情况下uni-app官方已经配置成按需加载了的 所有你不用担心这个问题

学到了,非常感谢!!!
