### ISSUE TITLE
项目有半年没更新了，是不是以后不打算维护了

### ISSUE THREAD

**Issue by jrt324** [SilurianYang/uni-simple-router#428]
项目有半年没更新了，是不是以后不打算维护了？
2.0.8 正式版什么时候能出来呢

**Comment by SilurianYang** [comment]
还在更新中，只是这段时间没有时间投入到该项目中，如果有重大bug会很快更新的，年底之前肯定会继续更新的

**Comment by jrt324** [comment]
@SilurianYang  感谢你投入时间在这个项目上，这个项目对uni的使用帮助还是挺大的

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，目前正在全力维护 `V3.0 版本中`
