### ISSUE TITLE
在history模式下，刷新非tabbar页面，都会跳转到首页，并且首页刷新两次才出现

### ISSUE THREAD

**Issue by ly10121024** [SilurianYang/uni-simple-router#43]
**Describe the bug**
在history模式下，刷新非tabbar页面，都会跳转到首页，并且首页刷新两次才出现
用的this.Router.push()跳转路由
![路由](https://user-images.githubusercontent.com/38686302/69213928-8149ed00-0ba0-11ea-9ec1-944f893a92dc.gif)

**Comment by SilurianYang** [comment]
你这个是什么版本的 试试最新的1.3.6呢？ 我在本地没有出现这个bug  如果1.3.6依旧纯在这个问题  你可以上传一个demo给我 很快解决的

**Comment by ly10121024** [comment]
> 你这个是什么版本的 试试最新的1.3.6呢？ 我在本地没有出现这个bug 如果1.3.6依旧纯在这个问题 你可以上传一个demo给我 很快解决的

好的，已经解决了。谢谢
