### ISSUE TITLE
使用next({ path:'/pages/login/login', NAVTYPE:'replaceAll' }) 无法正常跳转。

### ISSUE THREAD

**Issue by jiangjin3323** [SilurianYang/uni-simple-router#433]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

// router.js
import {RouterMount,createRouter} from 'uni-simple-router';
import store from './store/index.js'
const router = createRouter({
	platform: process.env.VUE_APP_PLATFORM,  
	routes: [...ROUTES]
});
//全局路由前置守卫
router.beforeEach((to, from, next) => {
	if(!store.state.userToken){
		next({
			path:'/pages/login/login',
			NAVTYPE:'replaceAll'
		})
	}else{
		next();
	}
	
});
// 全局路由后置守卫
router.afterEach((to, from) => {
    console.log('跳转结束')
})

export {
	router,
	RouterMount
}

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
没有token，跳转登录页

**实际结果**
[这里请贴上你的报错截图或文字]
报错信息： RangeError: Maximum call stack size exceeded....
> 无法跳转，

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
![企业微信截图_16693475967193](https://user-images.githubusercontent.com/55471893/203896896-3365f148-3a14-40b3-b9e0-0b9470b24c1a.png)
![企业微信截图_16693476453451](https://user-images.githubusercontent.com/55471893/203896900-111bf0a2-271a-4d4b-a258-f2b2bf105b32.png)

**Comment by SilurianYang** [comment]
因为 beforeEach 中的逻辑问题  需要注意的是当next有值时 会重新走所有流程 所以你现在的写法会死循环  注意一下就可以了

**Comment by jiangjin3323** [comment]
> 因为 beforeEach 中的逻辑问题 需要注意的是当next有值时 会重新走所有流程 所以你现在的写法会死循环 注意一下就可以了

好的，已经解决了，感谢提点！！！

**Comment by liulu1998** [comment]
> > 因为 beforeEach 中的逻辑问题 需要注意的是当next有值时 会重新走所有流程 所以你现在的写法会死循环 注意一下就可以了
> 
> 好的，已经解决了，感谢提点！！！

你好，怎么解决 ？

**Comment by jiangjin3323** [comment]
> > > 因为之前每一个中的总题目需要注意的是当下一个有价值的时候会重新走所有流程所以你现在的写法会死循环注意一下就可以了
> > 
> > 
> > 好的，已经解决了，谢谢提示！！！
> 
> 你好，怎么解决？

跳转到登陆页，也会触发，需要将登陆页path处理一下，除了登陆path其余都走登陆逻辑判断。
