### ISSUE TITLE
一个小BUG，H5端 跳转页面 不会改变body 的样式变量

### ISSUE THREAD

**Issue by kingyu** [SilurianYang/uni-simple-router#44]
**Describe the bug**
H5端当跳转到新得页面时候，uni-app修改得body当前页面样式变量不会跟着变化，导致不能使用page来改变当前页面得样式

**Expected behavior**
希望能和官方跳转一样 body 会叠加一个当前页面样式，这样可以通过本页面page{} 修改样式

**Screenshots**
使用插件就不正常，使用官方得路由跳转就正常
不改变得情况
![image](https://user-images.githubusercontent.com/5800811/69213941-8c048200-0ba0-11ea-8621-e14bc0091f3e.png)
正常情况
![image](https://user-images.githubusercontent.com/5800811/69213980-a9395080-0ba0-11ea-8d0c-673c576282a0.png)

**Additional context**
感谢，作者提供本插件

**Comment by kingyu** [comment]
[qihuei_h5_client.zip](https://github.com/SilurianYang/uni-simple-router/files/3867600/qihuei_h5_client.zip)
BUG重现示例

**Comment by SilurianYang** [comment]
这是一个小问题  不过提的很nice  very good
