### ISSUE TITLE
完全使用vue-router开发模式下,组件内调用uni.createSelectorQuery()方法报错

### ISSUE THREAD

**Issue by xinsuisuixin** [SilurianYang/uni-simple-router#440]
**问题描述**
uniapp h5端,完全使用vue-router开发模式,在组件内调用了uni.createSelectorQuery()方法,会报错.

**复现步骤**
组件内直接调用该方法
![image](https://user-images.githubusercontent.com/86598971/211713087-e4e26435-2812-41cd-94fc-25f2143e1c2f.png)

**预期结果**
部分迁移插件内调用了该方法,期望该方法可以正常使用.

**实际结果**
报错
![image](https://user-images.githubusercontent.com/86598971/211713459-df98acd3-eaed-45d0-8f0f-4118117ede01.png)

**系统信息:**
 - 发行平台: [H5平台]
 - HBuilderX版本 [3.6.4]
 - 项目创建方法 [HBuilderX]
 - uni-simple-router版本 [2.0.8-beta.4]

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/269

解决方案
1. 为h5实现一个报错方法的polyfill，这样简单高效。
2. 去除依赖dom的方法，更换成别的
3. 再不行就换成跨平台模式

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，在 [V3.0](https://v3.hhyang.cn/)  版本中全平台支持 嵌套路由及动态增减路由
