### ISSUE TITLE
Vue3+Vite支持

### ISSUE THREAD

**Issue by coolxiaohao** [SilurianYang/uni-simple-router#441]
大佬啥时候支持Vue3啊

**Comment by SilurianYang** [comment]
很抱歉，目前没有计划

**Comment by aimeiyijia** [comment]
源码里面router.ts 中install部分中的Object.defineProperty(Vue.prototype 改为Object.defineProperty(app.config.globalProperties 就基本上可以运行了

**Comment by terranc** [comment]
> 源码里面router.ts 中install部分中的Object.defineProperty(Vue.prototype 改为Object.defineProperty(app.config.globalProperties 就基本上可以运行了

app 在哪里申明的？

**Comment by SilurianYang** [comment]
https://github.com/SilurianYang/uni-simple-router/issues/451
