### ISSUE TITLE
h5项目，路由模式为history，页面跳转正常，但地址栏不再有任何变化，并且控制台报了一个错误

### ISSUE THREAD

**Issue by yeyifen** [SilurianYang/uni-simple-router#442]
**问题描述**
新建uniapp vue2的项目，按文档引入uni-simple-router后，npm run dev:h5 启动项目后，路由模式为hash无问题，改为history模式后，页面跳转正常，但地址栏不再有任何变化，并且控制台报了一个错误

**复现步骤**
[复现问题的步骤]
1. 修改路由模式为history，启动 `npm run dev:h5`
2. 点击  '页面跳转的按扭，执行 
```js
this.$router.push("/pages/xxx")
```
3. 查看 浏览器地址栏一直显示为首页的链接，不会修改为 /pages/xxx, 并且控制台报了个错误： TypeError: Cannot read properties of undefined (reading '__id__')

[或者可以直接贴源代码]

**预期结果**
跳转后能正常修改浏览器的url地址

**实际结果**
无法正常修改浏览器url地址，报错指向的行数是下面代码第2行：
```js
this.transitionTo(location, function (route) {
      pushState(cleanPath(this$1.base + route.fullPath), location.params.__id__); // fixed by xxxxxx
      handleScroll(this$1.router, route, fromRoute, false);
      onComplete && onComplete(route);
    }, onAbort);
```

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 chrome
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 Vue-cli创建
 - 设备信息 pc
 - uni-simple-router版本 2.0.8-beta.4

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
你应该使用插件的API， 例如：
- 跳转
```js
this.$Router.push
```

- 获取路由
```js
this.$Route
```

**Comment by yeyifen** [comment]
好吧，犯了个低级错误。感谢~

**Comment by yeyifen** [comment]
还是习惯用 this.$router，我加了个 webpack-replace-loader 在编译时把 .vue 文件的 $route 全局替换成了 $Route，目前试了下貌似正常

**Comment by EggTronic** [comment]
> 你应该使用插件的API， 例如：
> 
> * 跳转
> 
> ```js
> this.$Router.push
> ```
> 
> * 获取路由
> 
> ```js
> this.$Route
> ```

这里是出于什么考虑做api的命名改变呀？目前现有项目迁移uniapp，需要做额外的命名修改。

**Comment by yeyifen** [comment]
> 

这个之前我问过，因为uniapp内部就是使用了vue-router处理的，this.$router 这些已经被占用了
