### ISSUE TITLE
url传参“/?a=value&b=value2”如果以“&”结尾，路由报错

### ISSUE THREAD

**Issue by Marsnose** [SilurianYang/uni-simple-router#446]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
url传参“/?a=value&b=value2”如果改成“/?a=value&b=value2&”页面就会报错：
![微信截图_20230209120350](https://user-images.githubusercontent.com/20599749/217715311-fb8ebb85-712f-4e61-9323-b4af4012d5ff.png)
**复现步骤**
[复现问题的步骤]
1. 启动 '...'
路由传参以“&”符号结尾
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
页面重定向后自动去除“&”符号自动刷新
或者判断“&”符号后面为空则忽略参数{“ ”：null}

**实际结果**
[这里请贴上你的报错截图或文字]
页面报错后未自动刷新
![微信截图_20230209120350](https://user-images.githubusercontent.com/20599749/217715311-fb8ebb85-712f-4e61-9323-b4af4012d5ff.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]H5
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - 项目创建方法 [如使用Vue-cli创建/HBuilderX]
 - 设备信息 [如 iPhone8 Plus]
 - uni-simple-router版本 [如 v1.5.4] 2.0.7

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
文件“/src/helpers/utils.ts”中426-429行将“&”符号后空值判断为“{'':null}”传入query，导致下方遍历key为空，query[key]取值报错。

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
