### ISSUE TITLE
web-view不能跳转

### ISSUE THREAD

**Issue by qpLucifer** [SilurianYang/uni-simple-router#447]
**问题描述**
原本web-view里面可以调整，加上uni-simple-router后不能跳转了，也没有报错

**复现步骤**
<img width="895" alt="image" src="https://user-images.githubusercontent.com/82043389/219264235-e76f5e17-790c-4578-a655-fe0cfd16b553.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/82043389/219264330-d3fc0597-53fe-41d4-82ad-d5f8f88b0b62.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/82043389/219264414-21595f64-c6a4-4761-8d80-15ae0ea520f1.png">
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/82043389/219264497-9c505590-c74d-4491-a5c0-d3a4d8711ba8.png">

**预期结果**
希望进入web-view能跳转里面的链接

**实际结果**
实际上没有跳转

**系统信息:**
 - 发行平台: 微信小程序
 - vscode开发
 - 项目创建方法 uniapp项目
 - 设备信息 所有都不行
 - uni-simple-router版本 [v2.0.7]

**Comment by SilurianYang** [comment]
你是指 
未使用插件的情况下 在web-view网页中使用uni-app的跳转方法可以跳转到其他uni-app页面?
使用插件后就无法跳转了？
