### ISSUE TITLE
能支持vue3 吗

### ISSUE THREAD

**Issue by biaobaba** [SilurianYang/uni-simple-router#449]
**新功能描述**
支持vue3

**现状及问题**
好像不支持vue3

**Comment by aimeiyijia** [comment]
源码里面**router.ts 中install**部分中的**Object.defineProperty(Vue.prototype**  改为**Object.defineProperty(app.config.globalProperties** 就基本上可以运行了

**Comment by DaDaDaBocai** [comment]
@aimeiyijia app压根没有定义过啊。

**Comment by SilurianYang** [comment]
支持 vue3 的版本已经发布，请在这里[查阅文档](https://v3.hhyang.cn/)
