### ISSUE TITLE
[1.3.6] H5 history模式下，encodeURI为true时会丢失请求参数

### ISSUE THREAD

**Issue by linshaowl** [SilurianYang/uni-simple-router#45]
**Describe the bug**
H5 history模式下，encodeURI为true时会丢失请求参数

**To Reproduce**
1. 路由文件配置 `encodeURI: true`
2. 多次刷新带参数页面

**Screenshots**
![深度录屏_选择区域_20191121100627](https://user-images.githubusercontent.com/19506950/69298172-1227d380-0c48-11ea-9bc9-3f2b7c7d29d5.gif)

**Comment by SilurianYang** [comment]
bug  已确认

**Comment by JustFine0519** [comment]
请问怎么修复的？
