### ISSUE TITLE
H5没有上级页面时，点击导航栏的返回，返回拦截不起作用

### ISSUE THREAD

**Issue by jrt324** [SilurianYang/uni-simple-router#453]
**问题描述**
因为我这个H5页面最终是要嵌入到其他APP的，所以需要拦截没有上级页面时点击返回，如果没有上级页面，就调用嵌入的APP提供的返回原生方法。
但是试了一下，这种情况下H5的返回拦截不起作用。
而且H5中，onBackPress也不生效。
 

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
返回拦截不起作用

**系统信息:**
 - 发行平台:  H5
 - 操作系统 ：Android
 - uni-simple-router版本  v2.0.8

**Comment by SilurianYang** [comment]
调用 `getCurrentPages()` 查看页面栈只有一个时 并且是返回操作时  调用安卓或ios方法即可
