### ISSUE TITLE
快手小程序无法正常跳转

### ISSUE THREAD

**Issue by zk320520** [SilurianYang/uni-simple-router#454]
版本：2.0.7
快手小程序中
路由已正常注册
![image](https://github.com/SilurianYang/uni-simple-router/assets/24220783/58860e85-3b65-4db3-91de-34dc9530a45e)
执行页面跳转抛异常
![image](https://github.com/SilurianYang/uni-simple-router/assets/24220783/5777d47a-d716-4abb-b35e-bf2534a1b104)

**Comment by SilurianYang** [comment]
多了一个/?  至于快手小程序 我记得没有具体测试过 文档上也没写支持

[小程序系列支持平台](https://www.hhyang.cn/v2/start/applets/explian.html)

**Comment by SilurianYang** [comment]
请关注 [V3.0](https://v3.hhyang.cn/) 版本，该特性在 [V3.0](https://v3.hhyang.cn/)  版本中可用
