### ISSUE TITLE
使用自定义custom-tab-bar 路由监听不到

### ISSUE THREAD

**Issue by xianyu21** [SilurianYang/uni-simple-router#456]
https://uniapp.dcloud.net.cn/component/custom-tab-bar.html#custom-tab-bar

**Comment by SilurianYang** [comment]
你可以在底层使用 uni-simple-router 的跳转api , 插件会自动拦截

**Comment by xianyu21** [comment]
> 你可以在底层使用 uni-simple-router 的跳转api , 插件会自动拦截

抱歉链接给错了 应该是这个
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html

**Comment by SilurianYang** [comment]
不是一样的吗？自定义都是用的跳转API，所以你直接用 `$Router.pushTab` 就可以了。 另外我们已经推出了 `v3.0` 版本，有兴趣你可以查阅 [v3.0](https://v3.hhyang.cn/) 文档
