### ISSUE TITLE
 微信H5中，安卓tabbar进入子页面返回重新刷新问题

### ISSUE THREAD

**Issue by MrXieH** [SilurianYang/uni-simple-router#46]
在安卓真机微信网页中，例子首页点击去路由页1，再按返回键后，会重新刷新一下。
小米6、三星（其他机型没试过）微信网页会
ios和第三方浏览器不会
用的官方例子如图：
![TIM截图20191123192518](https://user-images.githubusercontent.com/28506210/69479203-9b502d80-0e35-11ea-9214-731d7e12a0b7.png)

**Comment by SilurianYang** [comment]
你可以先换成 `hash` 模式来避免这个问题

**Comment by SilurianYang** [comment]
## 1.3.81 已修复
