### ISSUE TITLE
请问，最新版的1.3.6 不能进行路由出传参吗？ router.push({ name: name, params: params })  没有传参过去，url也没有带

### ISSUE THREAD

**Issue by panjinfa** [SilurianYang/uni-simple-router#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SilurianYang** [comment]
1.3.5起 H5端统一采用的vue-router的规则 params传递的参数不会显示在url 刷新会丢失。你可使用query传参或者使用 `paramsToQuery:true` 配置

**Comment by nongzhenli** [comment]
> 1.3.5起 H5端统一采用的vue-router的规则 params传递的参数不会显示在url 刷新会丢失。你可使用query传参或者使用 `paramsToQuery:true` 配置
> paramsToQuery

作者你好，我目前使用1.3.81版本（npm安装）！在h5模式下（谷歌手机预览）使用编程式push()方法进行路由跳转传参的时候（命名路由）通过params传递参数（且已开启paramsToQuery:true 配置）！在路由拦截打印 to 参数时，发现时携带又 
`query: {...}`
参数的！但是url上传并没有携带?key=value   （使用path跳转的传参的形式并没有测试）

![image](https://user-images.githubusercontent.com/19389294/71478485-e8576300-282a-11ea-9f48-30eb79e7c7c3.png)
![image](https://user-images.githubusercontent.com/19389294/71478514-1177f380-282b-11ea-98fc-e65262c26e37.png)
![image](https://user-images.githubusercontent.com/19389294/71478531-2d7b9500-282b-11ea-8656-5420a3d53ccb.png)
![image](https://user-images.githubusercontent.com/19389294/71478706-efcb3c00-282b-11ea-882b-cf8b335d237e.png)

**Comment by SilurianYang** [comment]
@nongzhenli  自己配置错啦 看看文档
