### ISSUE TITLE
1.3.7版本打包后H5存在异常

### ISSUE THREAD

**Issue by markrgba** [SilurianYang/uni-simple-router#48]
模式：跨平台模式；
平台：h5；
环境：线上环境（也就是打包后）；
测试地址：[test.markrgba.cn](url)；
异常表现：
1、aliasPath失效，首页必须输入全路径才可进入
2、即使全路径能进入，点击刷新又出现页面载入不了的情况
3、编程式导航name跳转无法正确匹配路由，总是跳转到路径'/'

暂时这么多

**Comment by SilurianYang** [comment]
很感谢反馈 1.3.71已修复
