### ISSUE TITLE
除了返回到顶级页面 其他页面返回不会触发该页面的onUnload生命周期，且上一个页面的onLoad会再次触发

### ISSUE THREAD

**Issue by jxzlhy** [SilurianYang/uni-simple-router#49]
例如：首页到test1页面再到test2页面，然后依次返回首页。返回的过程中，test2页面的onUnload不会触发，且test1的onLoad会再次触发
![GIF](https://user-images.githubusercontent.com/16329495/69877629-a86d9080-12fd-11ea-8ca5-a281135280dd.gif)

**Comment by SilurianYang** [comment]
## 1.3.81 已修复

**Comment by alphayan** [comment]
v1.5.5遇到问题  1刷新test1页面 触发onload  2进入test2页面  3从test2回test1页面  onload又被触发  
不刷新test1页面 从首页进入test1页面 从test1进入test2页面 从test2返回test1页面  不触发onload
