### ISSUE TITLE
我按照案例使用导航守卫 安卓真机运行不生效

### ISSUE THREAD

**Issue by ckbabby** [SilurianYang/uni-simple-router#50]
你好， 我使用案例文档添加导航守卫发现H5 可以正常 安卓调试出现页面不跳转，又没有报错的情况.
![1](https://user-images.githubusercontent.com/22540944/69949416-6bd3ac00-152c-11ea-9473-2cab77ffa78e.png)
![2](https://user-images.githubusercontent.com/22540944/69949479-860d8a00-152c-11ea-9f31-71217bfca66e.png)

**Comment by SilurianYang** [comment]
发demo

**Comment by ckbabby** [comment]
[推流APP - 副本.zip](https://github.com/SilurianYang/uni-simple-router/files/3921001/APP.-.zip)

**Comment by ckbabby** [comment]
作者大大你好，我运行您的案例正常，但是我根据文档写的代码不知道怎么的就不正常

**Comment by ckbabby** [comment]
我知道什么问题了，的确是我自己设置 NAVTYPE  问题，现在可以了，谢谢啦！
