### ISSUE TITLE
APP最多只能跳转2级页面，之后无论如何也无效，也没有报错信息，H5正常

### ISSUE THREAD

**Issue by tanranran** [SilurianYang/uni-simple-router#51]
uni-simple-router 版本 1.3.81

路由配置

![image](https://user-images.githubusercontent.com/5227840/70152800-d29dc480-16e8-11ea-8149-d08140296ad9.png)

![image](https://user-images.githubusercontent.com/5227840/70152888-f6610a80-16e8-11ea-950d-1f8d3a9c6df4.png)
![image](https://user-images.githubusercontent.com/5227840/70152896-f9f49180-16e8-11ea-8eb9-33b6726aefdb.png)
![image](https://user-images.githubusercontent.com/5227840/70152928-0547bd00-16e9-11ea-87e5-7d55731e0934.png)

换回原生（uni.navigateTo）是好的

**Comment by SilurianYang** [comment]
非H5端你应该减少使用 实例对象进行跳转 使用 `this.$Router.xxx` 更佳

**Comment by tanranran** [comment]
@SilurianYang 
这种写法可以解决，但是还是希望用 实例对象跳转
主要原因是应为： 实例对象可以封装一些逻辑在里面，很多地方需要调用多次

**Comment by SilurianYang** [comment]
> @SilurianYang
> 这种写法可以解决，但是还是希望用 实例对象跳转
> 主要原因是应为： 实例对象可以封装一些逻辑在里面，很多地方需要调用多次

这个问题不着急啦  目前的app端路由正在强化中

**Comment by tanranran** [comment]
@SilurianYang 万分感谢，爱你(๑′ᴗ‵๑)Ｉ Lᵒᵛᵉᵧₒᵤ❤

**Comment by SilurianYang** [comment]
> @SilurianYang 万分感谢，爱你(๑′ᴗ‵๑)Ｉ Lᵒᵛᵉᵧₒᵤ❤

me too
