### ISSUE TITLE
使用router-link时候，Cannot read property 'route' of undefined 报错

### ISSUE THREAD

**Issue by tongjh2** [SilurianYang/uni-simple-router#54]
router/index.js
`
import Vue from 'vue'
import Router from 'uni-simple-router'
Vue.use(Router)
const router = new Router({
    routes: [
{ "path": "/pages/my/update_name/main", "name":"my.update_name" },
.....
]
})
....
export default router;`

main.js
`import router from './router'
import { RouterMount } from 'uni-simple-router'

import routerLink from '../node_modules/uni-simple-router/component/router-link.vue'
Vue.component('router-link',routerLink)

Vue.config.productionTip = false
App.mpType = 'app'
const app = new Vue({
	...App
})
// #ifdef H5
	RouterMount(app,'#app');
// #endif`

`<router-link to="{name:'my.update_name'}" class="weui-cell weui-cell_access" hover-class="weui-cell_active">
	<div class="weui-cell__bd">昵称</div>
	<div class="weui-cell__ft weui-cell__ft_in-access"></div>
</router-link>`

`applets-patch.js:34 Uncaught (in promise) TypeError: Cannot read property 'route' of undefined
    at queryInfo (applets-patch.js:34)
    at getRouterNextInfo (util.js:270)
    at res (concat.js:168)
    at new Promise (<anonymous>)
    at concat.js:164
    at Vue.d (index.umd.min.js:1)
    at Array.<anonymous> (index.umd.min.js:1)
    at concat.js:150
queryInfo @ applets-patch.js:34
getRouterNextInfo @ util.js:270
res @ concat.js:168
(anonymous) @ concat.js:164
d @ index.umd.min.js:1
(anonymous) @ index.umd.min.js:1
(anonymous) @ concat.js:150
async function (async)
(anonymous) @ concat.js:148
beforeHooks @ concat.js:147
target.<computed> @ init.js:35
iterator @ vue-router.esm.js:1974
step @ vue-router.esm.js:1741
step @ vue-router.esm.js:1745
runQueue @ vue-router.esm.js:1749
confirmTransition @ vue-router.esm.js:2003
transitionTo @ vue-router.esm.js:1898
push @ vue-router.esm.js:2396
push @ vue-router.esm.js:2693
r @ index.umd.min.js:1
o @ index.umd.min.js:1
(anonymous) @ index.umd.min.js:1
x @ index.umd.min.js:1
(anonymous) @ index.umd.min.js:1
(anonymous) @ index.js:114
_pushTo @ index.js:107
(anonymous) @ index.js:151
(anonymous) @ index.js:150
resolveParams @ hooks.js:139
async function (async)
resolveParams @ hooks.js:105
push @ index.js:149
gotoPage @ router-link.vue:76
click @ router-link.vue?d896:11
invokeWithErrorHandling @ vue.runtime.esm.js:1865
invoker @ vue.runtime.esm.js:2190
original._wrapper @ vue.runtime.esm.js:7018
index.umd.min.js:1 [system] TypeError: Reflect.get called on non-object
    at Object.get (<anonymous>)
    at completeVim (app-patch.js:3)
    at Vue.onShow (index.js:361)
    at invokeWithErrorHandling (vue.runtime.esm.js:1865)
    at Vue../node_modules/@dcloudio/vue-cli-plugin-uni/packages/h5-vue/dist/vue.runtime.esm.js.Vue.__call_hook (vue.runtime.esm.js:8541)
    at a (index.umd.min.js:1)
    at Vue.f (index.umd.min.js:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1865)
    at Vue.$emit (vue.runtime.esm.js:3898)
    at HTMLDocument.<anonymous> (index.umd.min.js:1)`

**Comment by SilurianYang** [comment]
你这个name是否存在？
