### ISSUE TITLE
希望有一个接口能够更改当前页面this.$Route.query的值

### ISSUE THREAD

**Issue by tanranran** [SilurianYang/uni-simple-router#55]
有这样一种场景，
A页面携带参数到B页面,

此时B页面需要更具参数显示对应tab 1，

这时切换B页面tab 2,此时刷新页面,会导致tab切换到tab 1.

**Comment by SilurianYang** [comment]
很抱歉暂时可能不会提供这样的函数  在H5中你可以使用next() 再重新跳一次  或者你B页面下的自定义tab做成可以跳转路径的那种 就不会因为参数问题而导致tab active状态错乱啦

**Comment by tanranran** [comment]
@SilurianYang 目前看来解决办法只能重新跳，但是重新跳的缺点就是整个页面都得重新加载一遍。
