### ISSUE TITLE
h5端，uni.previewImage会跳转内置页面，导致全局守卫出错

### ISSUE THREAD

**Issue by huanghaodong** [SilurianYang/uni-simple-router#57]
这个内置页面的path = '/preview-image'

**Comment by SilurianYang** [comment]
请给出一个明确的实例，不管是示例还是我测试都没有发现此问题

**Comment by vincent931018** [comment]
@SilurianYang 
uni.previewImage方法的调用会触发页面的beforeRouteLeave hook😭
