### ISSUE TITLE
H5 非 hash 模式下重定向异常

### ISSUE THREAD

**Issue by wayoo** [SilurianYang/uni-simple-router#58]
** H5 非 hash 模式下重定向异常 **
不进入下面的配置就自动跳转到了首页。
```    
    {
            path: '*',
            name: 'moddle',
            redirect: (to) => {
                const name = whitelist[to.path];
                if (name) {
                    return {
                        name,
                    };
                }
                // 404
                return {
                    name: 'tabbar-index',
                };
            },
        },
````

manifest.json 文件 
```
    "h5": {
        "router": {
            "mode": "history",
            "base": ""
        },
    }
```

该模式下导致 uni-simple-router 重定向异常

**To Reproduce**
npm run serve 
访问 http://localhost:1024/xxx 其中 /xxx 是个不存在的路径

**Expected behavior**
重定向到首页，并且正常展示

**Screenshots**
![image](https://user-images.githubusercontent.com/1708809/71147115-b2cadc80-2262-11ea-9758-de77f838f486.png)
如图，从空路由自动重定向到首页，但是不出发 redirect 的回调，不渲染页面
![image](https://user-images.githubusercontent.com/1708809/71147174-e279e480-2262-11ea-96b4-593877462214.png)

**Comment by SilurianYang** [comment]
## 已知bug 请耐心等待修复
