### ISSUE TITLE
注册全局路由前置守卫跳转失败

### ISSUE THREAD

**Issue by willbb** [SilurianYang/uni-simple-router#59]
applets-patch.js:34 Uncaught (in promise) TypeError: Cannot read property 'route' of undefined
    at queryInfo (applets-patch.js:34)
    at getRouterNextInfo (util.js:270)
    at res (concat.js:168)
    at new Promise (<anonymous>)
    at concat.js:164
    at Vue.d (index.umd.min.js:1)
    at Array.<anonymous> (index.umd.min.js:1)
    at concat.js:150

**Comment by SilurianYang** [comment]
### 第一 use完成后请不要重复use
### 第二 uni模式下$Rourer 非 $router $Route非$route

**Comment by SilurianYang** [comment]
如果你不想使用新版本 你没必要配置 `vue.config.js`  所以老版本不会报错！

**Comment by willbb** [comment]
请问一下 transpileDependencies 这个该如何配置呢？
![image](https://user-images.githubusercontent.com/18067238/71305443-345f6d80-240f-11ea-8fdc-9ad1fa2235dc.png)

**Comment by SilurianYang** [comment]
多看看文档对你有帮助  不管是uni-simple-router的还是vue-cli的   而且uni-simple-router 已经给你列出来了怎么写了  你还问怎么配置

**Comment by willbb** [comment]
![image](https://user-images.githubusercontent.com/18067238/71305464-9f10a900-240f-11ea-9580-b3c8e76e24fd.png)

**Comment by willbb** [comment]
谢谢了，对前端不是太懂，所以问的问题会比较低级
