### ISSUE TITLE
内测版1.4.8版本App.vue执行异常

### ISSUE THREAD

**Issue by kang0221** [SilurianYang/uni-simple-router#61]
[demo3.zip](https://github.com/SilurianYang/uni-simple-router/files/4006694/demo3.zip)
1.自定义调试基座或者打包安装，打开APP启动动画会闪一次白屏（可能是加载了两次启动动画，通过在App.vue中plus.navigator.closeSplashscreen()解决）。
2.首页的created()方法在App.vue执行前后都会执行一次。
3.首页无onLoad()生命周期时，App.vue会执行两次。
最正式版与测试版HBuilderX打包都如此。

压缩文件项目中guide.vue为首页

**Comment by SilurianYang** [comment]
### 回答下此问题：
1. 打包后因为有添加启动图片，而1.4.8起在app端会有一个页面触发生命周期，默认是白色屏幕，所有有闪屏一下。可以在 `loddingPageHook` 生命钩子中配置 `plus.navigator.closeSplashscreen()` 解决此问题。 **已把此配置加为默认配置**
1. `created` 生命钩子在uni-app不是标准的生命钩子，所以路由不会去处理这些钩子。你应该使用标准的uni-app页面生命钩子
1. 首页无 `onLoad` 生命钩子 首次路由跳转会触发两次。**bug、已修复**

#### 最后感谢你的内测。有你积极的配合才有路由的今天，加油陌生人！！
