### ISSUE TITLE
全局前置守卫没有写next会自动显示页面，对于需要同步等待的异步任务，next会跳转2次

### ISSUE THREAD

**Issue by huangrenyun** [SilurianYang/uni-simple-router#64]
`//全局路由前置守卫
router.beforeEach((to, from, next) => {
	setTimeout(()=>{
		next()
	},2000);
})`

代码如上：
我这边的页面进去直接没有拦截能显示，过了2秒又跳转了一次。vuex-router不写next可以完全拦截，不知道uni-simple-router该怎么使用？多谢指教！

**Comment by SilurianYang** [comment]
先声明下 1.4.8以下的版本完全拦截的只能是H5、其他端都无法做到首次拦截。1.4.8起 app端也可以完全拦截啦。不过前提是必须是非nvue页面

**Comment by huangrenyun** [comment]
@SilurianYang ，你好。我这边就是chrome浏览器运行的H5，从官方下载的例子不写next()也没办法拦截，具体版本信息如下：
![image](https://user-images.githubusercontent.com/50949973/71654502-17ab2a00-2d6d-11ea-92bb-6c5c71b3948c.png)

**Comment by SilurianYang** [comment]
h5需要 1.2.5起 更新到最新版本吧

**Comment by huangrenyun** [comment]
@SilurianYang 已更新到最新版本，但是打开页面依然不能够自动拦截，只能对通过uni.navigateTo或者this.$Router.push这种主动形式的跳转方式的拦截。是不是还需要其他配置？

**Comment by SilurianYang** [comment]
> @SilurianYang 已更新到最新版本，但是打开页面依然不能够自动拦截，只能对通过uni.navigateTo或者this.$Router.push这种主动形式的跳转方式的拦截。是不是还需要其他配置？

打扰了  求你看下示例可以么？github上不是有示例么？

**Comment by huangrenyun** [comment]
@SilurianYang 可以了，谢谢耐心指点！

**Comment by qicainiao** [comment]
我这边最新的 1.5.5 的，依然有这个问题，cli创建的必须cli的方式能复现，代码用的github上的ideCreateBase这个demo。
