### ISSUE TITLE
新版本1.4.8 APP模式下启动报错

### ISSUE THREAD

**Issue by tanranran** [SilurianYang/uni-simple-router#65]
15:04:12.624 正在重启，如手机上HBuilder调试基座未启动，请手动启动...
15:04:14.992 TypeError: undefined is not an object (evaluating '__uniConfig.appLaunchInfo.path')
15:04:15.689 TypeError: undefined is not an object (evaluating '__uniConfig.appLaunchInfo.path')

换回1.3.81版本正常

**Comment by SilurianYang** [comment]
## 请提供一个可复现的demo

**Comment by jecoy** [comment]
相同的问题 不知道什么原因

**Comment by SilurianYang** [comment]
# hbx 2.5.0以下 即可

**Comment by xlkit456852** [comment]
请问年后有计划修复这个功能吗？
