### ISSUE TITLE
APP 1.4.8版本this.$Router.back(2);只能返回上一页

### ISSUE THREAD

**Issue by kang0221** [SilurianYang/uni-simple-router#66]
APP 1.4.8版本拦截了带有原生返回按钮的页面的返回事件，导致在该页面使用this.$Router.back(2)返回时被拦截，参数delta丢失，不能返回多级。暂时在pageIsHeadBack()中过滤掉返回方式为 'from:navigateBack' 临时解决，不知道会不会导致其他问题。

**Comment by SilurianYang** [comment]
## 确实有此bug 但是解决方法有点小问题  还需要处理底部拦截的显示还是隐藏 包括守卫信息

**Comment by SilurianYang** [comment]
## 请查阅v1.4.9 已修复此问题
