### ISSUE TITLE
路由配置项beforeEnter和路由实例方法router.beforeEach同时存在时，前者会执行2次

### ISSUE THREAD

**Issue by huangrenyun** [SilurianYang/uni-simple-router#67]
代码片段:
`
router.beforeEach((to, from, next) => {
	console.log(1);
	next();
	console.log(2);
}

{
	aliasPath: '/tabbar2',
	component: () => import('@/pages/component/router2.vue'),
	path: "/pages/tabbar/tabbar-2/tabbar-2",
	name: 'tabbar-2',
	beforeEnter: (to, from , next) => {
		console.log(3)
	}
},
`
运行结果：
![image](https://user-images.githubusercontent.com/50949973/71711970-47763280-2e3e-11ea-9e8b-9bc50fd6871a.png)
运行环境：
Chrome+H5
版本信息：
![image](https://user-images.githubusercontent.com/50949973/71711988-5d83f300-2e3e-11ea-8c90-8d1ce2d856f7.png)

**Comment by SilurianYang** [comment]
这个应该是在H5端首次进入的时候吧

**Comment by huangrenyun** [comment]
@SilurianYang 是的H5端每次打开页面会执行两次

**Comment by SilurianYang** [comment]
## 请查阅v1.4.9 已修复此问题
