### ISSUE TITLE
希望加入types，对代码提示， 对ts更友好

### ISSUE THREAD

**Issue by Jonny-china** [SilurianYang/uni-simple-router#68]

**Comment by qq1037305420** [comment]
// shims-simple-router.d.ts
declare interface RouteConfig {
  path: string, //pages.json中的path 必须加上 '/' 开头
  name?: string, // 命名路由
  meta?: any,   //其他格外参数
  beforeEnter?: (to: RouteConfig, from: RouteConfig, next: () => void) => void,   //路由元守卫
  component?: any,    //H5端可用
  components?: { [name: string]: any }, // 命名视图组件，H5端可用
  redirect?: string | Location | Function,  //H5端可用
  props?: boolean | Object | Function,  //H5端可用
  aliasPath?: string,    //h5端 设置一个别名路径来替换 uni-app的默认路径
  alias?: string | Array<string>,   //H5端可用
  children?: Array<RouteConfig>, // 嵌套路由，H5端可用
}

declare module 'vue/types/vue' {
  // 可以使用 `VueConstructor` 接口
  // 来声明全局属性
  interface VueConstructor {
    mpType: string
  }
  interface Vue {
    $router: {
      push: (param: Partial<RouteConfig>) => void,
      replace: (param: Partial<RouteConfig>) => void,
      replaceAll: (param: Partial<RouteConfig>) => void,
      pushTab: (param: Partial<RouteConfig>) => void,
      back: (param: number) => void,
    }

    $route: {
      path: string,
      params: { [key: string]: any },
      query: { [key: string]: any }
    }
  }
}

**Comment by kaisa911** [comment]
现在最新版的里面支持ts了吗？

**Comment by SilurianYang** [comment]
# v1.5.4 已添加
