### ISSUE TITLE
点击进入分享的页面，路由的拦截在页面的onShow 之后

### ISSUE THREAD

**Issue by haydenzhourepo** [SilurianYang/uni-simple-router#69]
需求：
在进入页面之前判断路由需不需要登录，如果需要自动登录，登录判断执行完后进入页面，执行页面内的数据请求，初始化数据， 
结果：
 点击分享的页面 是先 执行页面内的生命周期后执行 route.BeforeEach
![image](https://user-images.githubusercontent.com/21101605/71807981-92df4980-30a7-11ea-81a9-ae628b8cff44.png)

![image](https://user-images.githubusercontent.com/21101605/71808051-b4d8cc00-30a7-11ea-9568-c72f38309271.png)

**Comment by SilurianYang** [comment]
不好意思  小程序是这样的
