### ISSUE TITLE
您好，h5端通过链接直接进入页面不会走守卫钩子

### ISSUE THREAD

**Issue by Shawyau** [SilurianYang/uni-simple-router#7]
我看uni社区上也出现类似的问题，用测试demo跑也不会走。另外就是在在H5端浏览器的后退、前进事件也不会触发路由钩子，不知道大佬有没有考虑也加上和vue-router一样

**Comment by SilurianYang** [comment]
> 我看uni社区上也出现类似的问题，用测试demo跑也不会走。另外就是在在H5端浏览器的后退、前进事件也不会触发路由钩子，不知道大佬有没有考虑也加上和vue-router一样

请拉取分支1.1.3里面的已经完成相关问题 包括 [#4](https://github.com/SilurianYang/uni-simple-router/issues/4) 。如果急需使用请拉取1.1.3分支下的。注意src下的为源码，需要自己手动替换到node_modules下 npm包将会过几天发布

**Comment by Shawyau** [comment]
> > 我看uni社区上也出现类似的问题，用测试demo跑也不会走。另外就是在在H5端浏览器的后退、前进事件也不会触发路由钩子，不知道大佬有没有考虑也加上和vue-router一样
> 
> 请拉取分支1.1.3里面的已经完成相关问题 包括 [#4](https://github.com/SilurianYang/uni-simple-router/issues/4) 。如果急需使用请拉取1.1.3分支下的。注意src下的为源码，需要自己手动替换到node_modules下 npm包将会过几天发布

非常感谢，我测试了一下，发现有个小小的问题，浏览器的后退和前进时，路由守卫里的to和from都是同样的值(都为to)，还有就是在app Hide后再切回应用会报一个异常
![{B4E81467-A83C-4C5A-9D0C-FF4B4EE2ABF2}_20190812183940](https://user-images.githubusercontent.com/19165200/62859787-c0aaa700-bd30-11e9-8c4c-331e0e328102.jpg)

**Comment by SilurianYang** [comment]
@Shawyau  是的那个1.1.3分支不是最终的代码，感谢指出
