### ISSUE TITLE
pushTab编译后 微信小程序报错。

### ISSUE THREAD

**Issue by quan01994** [SilurianYang/uni-simple-router#70]
代码位于 APP.vue 的onLaunch 方法内。
````javascript
//这个是成功的。
uni.switchTab({
    url: '/pages/index/index',
    fail: function(err) {
        console.log(err)
    }
})
// 这个报错
self.$Router.pushTab({
    name: 'index'
})
````
是编译后，也就是点击发布后，微信小程序报错。无法跳转。
![image](https://user-images.githubusercontent.com/20533465/72139088-17440c00-33c9-11ea-9407-473c17850f77.png)

报错信息
![image](https://user-images.githubusercontent.com/20533465/72139232-54a89980-33c9-11ea-902c-02c053acec85.png)

**Comment by quan01994** [comment]
用的是npm 的 1.4.9

**Comment by SilurianYang** [comment]
就是发包后？

**Comment by quan01994** [comment]
@SilurianYang  对啊，dev没有报错，build玩 发布后，就报错了。。。。

**Comment by SilurianYang** [comment]
## 1.5.2 已修复
