### ISSUE TITLE
移动端Android手机第一次安装，Router跳转是失效的，进程中杀掉应用后，进入应用就正常了。

### ISSUE THREAD

**Issue by IDOshi201109** [SilurianYang/uni-simple-router#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SilurianYang** [comment]
## 问题出在
1. router还是老版本
1. hubx升级router没升级

**Comment by IDOshi201109** [comment]
谢谢您的解答：已经升级对应router版本了。
出现问题：升级到1.4.9，锤子手机是好的，但是小米手机 还是初次安装 点击router跳转失效。

1)HBuildX:2.5.1
2)package.json配置如下。
"dependencies": {
    "uni-simple-router": "^1.4.9"
  }

相关手机型号：
1、锤子坚果pro2:   Android版本7.1.1   软件版本：v6.7.3     OK
2、小米8SE： Android版本9    MIUI版本：MIUI 10.3.2稳定版  NO
3、小米8:   Android版本9      MIUI版本：MIUI 10.3.6 稳定版    NO
4、乐视2 ： Android版本6.0      EUI版本：5.9.028s(稳定版)   NO
5、华为畅享 9e 型号MRD-TL00   ： Andorid版本 9     EMUI版本：9.1.0      NO
6、锤子坚果pro2:   Android版本7.1.1   软件版本：v6.7.2     OK

**Comment by IDOshi201109** [comment]
> ## 问题出在
> 1. router还是老版本
> 2. hubx升级router没升级

谢谢您的解答：已经升级对应router版本了。
出现问题：升级到1.4.9，锤子手机是好的，但是小米手机 还是初次安装 点击router跳转失效。

1)HBuildX:2.5.1
2)package.json配置如下。
"dependencies": {
    "uni-simple-router": "^1.4.9"
  }

相关手机型号：
1、锤子坚果pro2:   Android版本7.1.1   软件版本：v6.7.3     OK
2、小米8SE： Android版本9    MIUI版本：MIUI 10.3.2稳定版  NO
3、小米8:   Android版本9      MIUI版本：MIUI 10.3.6 稳定版    NO
4、乐视2 ： Android版本6.0      EUI版本：5.9.028s(稳定版)   NO
5、华为畅享 9e 型号MRD-TL00   ： Andorid版本 9     EMUI版本：9.1.0      NO
6、锤子坚果pro2:   Android版本7.1.1   软件版本：v6.7.2     OK

**Comment by SilurianYang** [comment]
@IDOshi201109  你是跑的app端还是h5端？  app端的话 必须使用 2.5.0以下的hubx版本才可以  才出的hubx携带了 `v3` 的新特性  所以插件还不支持高版本

**Comment by IDOshi201109** [comment]
> @IDOshi201109 你是跑的app端还是h5端？ app端的话 必须使用 2.5.0以下的hubx版本才可以 才出的hubx携带了 `v3` 的新特性 所以插件还不支持高版本

app端

**Comment by IDOshi201109** [comment]
> @IDOshi201109 你是跑的app端还是h5端？ app端的话 必须使用 2.5.0以下的hubx版本才可以 才出的hubx携带了 `v3` 的新特性 所以插件还不支持高版本

谢谢你的答疑

**Comment by SilurianYang** [comment]
@IDOshi201109  还有啥问题  没有问题  我关闭issue了

**Comment by IDOshi201109** [comment]
> @IDOshi201109 还有啥问题 没有问题 我关闭issue了

HBuildX 回退到版本：2.4.6 + uni-simple-router 版本：1.4.9
app端  Android 初次安装还是跳转不了。杀掉进程进入ok，进入后台回来没用，必须杀进程重开应用。
大佬，改哪个文件呢，这块？思路提供下，感谢。

**Comment by SilurianYang** [comment]
@IDOshi201109  怎么可能  你加群解决问题吧  769241495

**Comment by IDOshi201109** [comment]
问题找到了：我的锅，以为就是升级版本就行了。
这次改动比较大，那个对应的common目录下的useRouter.js有改动。
看了最新版本对应的例子，集成替换进去好了。
uni-simple-router 版本：1.4.9
HBuildX:2.4.6

谢谢大佬的指教。
