### ISSUE TITLE
App下配置midButton，点击跳转错误，不触发uni.onTabBarMidButtonTap

### ISSUE THREAD

**Issue by TheresaFu** [SilurianYang/uni-simple-router#72]
**Describe the bug**
配置如下
```
// pages.json

"tabBar": {
...
"midButton": {
    "width": "60px",
    "height": "65px",
    "backgroundImage": "static/xx.png"
},
"list":[
...
]

// App.vue

export default {
    onLaunch: function() {
        uni.onTabBarMidButtonTap(()=> {
            this.$Router.push('/pages/tabbar/release');
	});
    }
}
```
真机调试下，点击按钮跳转错误，调试不执行uni.onTabBarMidButtonTap，控制台无报错
测试examples增加以上配置，出现相同问题
hbuildx 新建空白模板，增加以上配置，不使用uni-simple-router，测试正常

**Smartphone (please complete the following information):**
 - Device: [e.g. 华为mate10 pro]
 - OS: [e.g. EMUI 9.1]
 - Version [e.g. last]

**Comment by SilurianYang** [comment]
把配置这样设置 `holdTabbar:false，rewriteFun:false,`  不对底部菜单进行拦截

**Comment by TheresaFu** [comment]
> 把配置这样设置 `holdTabbar:false，rewriteFun:false,` 不对底部菜单进行拦截

集成uni-hold-tabbar后该配置仍不起作用
反之不集成uni-hold-tabbar该配置测试正常
测试配置如下：
```
// router/index.js

const router = new Router({
  encodeURI: false,
  APP: {
    holdTabbar: false,
    rewriteFun: false
  },
  routes: [...modules]
});

// App.vue

Vue.prototype.$holdTab = new HoldTabbar({
  // 是否注册页面 onTabEvent 生命钩子
  registerPageHook: true,
  event: {
    click: (index, { pagePath }, next) => {
      router.pushTab(pagePath);
      next();
    }
  }
});
```

**Comment by SilurianYang** [comment]
为什么你还要去集成一遍 `uni-hold-tabbar` ?  路由已经自己集成了。你只需要设置开关就好了
#### [原生tabbar的拦截](http://hhyang.cn/src/router/start/app/tabbar.html)

**Comment by TheresaFu** [comment]
明白，原来是已经集成了，不需要再额外集成
