### ISSUE TITLE
onBeforeBack H5拦截异常

### ISSUE THREAD

**Issue by MrChenYZ** [SilurianYang/uni-simple-router#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MrChenYZ** [comment]
希望下一个版本修复哈

**Comment by SilurianYang** [comment]
# v1.5.0 已修复
