### ISSUE TITLE
APP启动时进入首页，首页的onLoad事件被触发了2次。 

### ISSUE THREAD

**Issue by ok2079** [SilurianYang/uni-simple-router#76]
如题。

尝试注释掉main.js里的2行import router....，就没有onLoad被触发2次的问题了。

版本信息：HbuilderX 2.4.6.20191210、uni-simple-router@1.4.9。

[demo.zip](https://github.com/SilurianYang/uni-simple-router/files/4056854/demo.zip)

**Comment by SilurianYang** [comment]
# v1.5.0已修复
