### ISSUE TITLE
从1.4.8版本开始，因加入了 uni-hold-tabbar拦截tabbar，APP端自定义组件导航布局会有问题

### ISSUE THREAD

**Issue by shonve** [SilurianYang/uni-simple-router#78]
uni-simple-route@1.5.1
uniapp基座版本：2.5.1（未开启V3）
uni-read-pages@1.0.3

在未加入uni-simple-router 之前，无论APP还是小程序，布局均正常。在加入之后，小程序布局正常，但APP启动页布局乱了。展现的形式是自定义组件导航未占满原有空间，往状态栏压缩了。当我调整pages.json 中的路由顺序之后，总是处于第一个的启动页才会有此问题。且设置

```
APP:{
        holdTabbar:false        //默认是true
    },
```
或者
```
APP:{
       rewriteFun:false    //默认是true
    },
```
均无效。

而当我回退uni-simple-route版本至1.3.81，布局问题不复存在。

初略定位为新版本引用了 uni-hold-tabbar导致。

**Comment by SilurianYang** [comment]
我不知道为什么你那边会出现这个问题 ，我弄了个测试demo请对比下

[xxxx.zip](https://github.com/SilurianYang/uni-simple-router/files/4076652/xxxx.zip)

**Comment by shonve** [comment]
[xxxx (2).zip](https://github.com/SilurianYang/uni-simple-router/files/4076998/xxxx.2.zip)
针对demo进行问题完善，其中static下面有1.3.81和1.5.1的安卓手机端效果截图
