### ISSUE TITLE
vue-cli 命令行创建的项目，通过 npm 安装 uni-simple-router 后，插件代码没有进行条件编译

### ISSUE THREAD

**Issue by lyl123321** [SilurianYang/uni-simple-router#79]
**Describe the bug**
`vue-cli` 命令行创建的 `uni-app` 项目，通过 `npm` 或者 `yarn` 安装 `uni-simple-router` 插件后，插件代码没有进行 `uni-app` 特有的条件编译。

**To Reproduce**
1. 使用 `vue create -p dcloudio/uni-preset-vue bug-fix` 命令行创建一个名为 `bug-fix` 的 `uni-app` 项目；
2. 使用 `yarn add uni-simple-router` 安装 `uni-simple-router` 插件；
3. 在 `bug-fix/node_modules/uni-simple-router/index.js` 文件中添加测试代码：
    ```
    // #ifdef H5
    console.log('H5')
    // #endif

    // #ifndef H5
    console.log('not H5')
    // #endif
    ```
4. 在 `bug-fix/src/main.js` 文件中添加代码：
    ```
     import 'uni-simple-router'
    ```
5. 运行命令 `yarn run serve`，在浏览器中打开项目运行地址。打开控制台，可以看到控制台输出：
    ```
    H5
    not H5
    ```
6. 更有力的证据是，打开 `Sources` 面板，可以看到打包后的代码为:
    
    ```
    // #ifdef H5
    console.log('H5')
    // #endif

    // #ifndef H5
    console.log('not H5')
    // #endif
    ```
    也就是说，该项目在打包时根本没有对 `uni-app` 的条件注释进行条件编译，这些特殊注释直接被忽略了。

**Expected behavior**
希望可以对 `npm` 包进行 `uni-app` 的条件编译。
目前的 `fix` 方法只有将该 `mudule` 整个复制到 `src/plugins/` 下面了。

**Additional context**
`vue-cli` 创建的项目，`npm` 安装的插件。

**Comment by qq1037305420** [comment]
在vue.config.js 中添加
```js
transpileDependencies: ['uni-simple-router']
```
不添加这个等于不编译，不编译自然不会按照 uni的规则来编译

**Comment by lyl123321** [comment]
> 在vue.config.js 中添加 @lyl123321
> 
> ```js
> transpileDependencies: ['uni-simple-router']
> ```
> 
> 不添加这个等于不编译，不编译自然不会按照 uni的规则来编译
> @SilurianYang 标注关闭吧

其实我加了的，但是没有特地写出来，不过确实是这方面的问题。
我又试了一下，打包成`H5`应用时没有将这个`npm`包的代码编译成`es5`，也没有进行`uni-app`条件编译；
打包成小程序或者`APP`时，会将`npm`包代码编译成`es5`，也有进行条件编译......
不知道这个包是特例还是`uni-app`打包`H5`应用时不会转义`npm`包的代码，亦或者`uni-app`会智能地部分转义......
