### ISSUE TITLE
这个好像不能拦截原生tabbar的切换吧

### ISSUE THREAD

**Issue by BoneTM** [SilurianYang/uni-simple-router#8]

**Comment by SilurianYang** [comment]
很抱歉 目前是不支持。 1.1.3分支开始起则可以支持，详细请拉取1.1.3分支！src目录下为源码

**Comment by BoneTM** [comment]
> 很抱歉 目前是不支持。 1.1.3分支开始起则可以支持，详细请拉取1.1.3分支！src目录下为源码

等不及阅读源码了 你是怎么做到的
滋瓷作者

**Comment by SilurianYang** [comment]
> > 很抱歉 目前是不支持。 1.1.3分支开始起则可以支持，详细请拉取1.1.3分支！src目录下为源码
> 
> 等不及阅读源码了 你是怎么做到的
> 滋瓷作者

我的意思是你如果想拦截原生tabbar可以把 1.1.3分支下的src目录copy到npm安装的目录下，然后试试效果

**Comment by BoneTM** [comment]
> > > 很抱歉 目前是不支持。 1.1.3分支开始起则可以支持，详细请拉取1.1.3分支！src目录下为源码
> > 
> > 
> > 等不及阅读源码了 你是怎么做到的
> > 滋瓷作者
> 
> 我的意思是你如果想拦截原生tabbar可以把 1.1.3分支下的src目录copy到npm安装的目录下，然后试试效果

我知道(手动滑稽) 我就是来赞美你一波 2333
