### ISSUE TITLE
跨平台模式，1.5.1版本，编译器2.4.6，APP打开后空白但没报错

### ISSUE THREAD

**Issue by xlkit456852** [SilurianYang/uni-simple-router#81]
**Describe the bug**
使用的是跨平台模式，并且代码是复制快速上手中的代码。我原本用的编译器是最新的2.5.1，但是打包APP后打开会报错，且页面空白
···
TypeError: undefined is not an object (evaluating '__uniConfig.appLaunchInfo.path')
···
于是我把编译器的版本降为2.4.6，打包APP后打开没有报错信息，但是仍然是空白页面，H5、小程序则正常

**Smartphone (please complete the following information):**
 - Device: [荣耀20pro]
 - OS: [安卓10.0]

如果不使用uni-simple-router这个插件，我试过是可以在APP打开并使用的。请问应该如何解决？下面是项目demo代码

[wynews_front_test.zip](https://github.com/SilurianYang/uni-simple-router/files/4113308/wynews_front_test.zip)

**Comment by SilurianYang** [comment]
## 因为你使用了 v3模式  你把 v3模式关闭了 就好了 高本版hubx不会影响此问题  是 `V3` 的问题

**Comment by xlkit456852** [comment]
关闭v3模式后，仍然是一样的效果（HBX2.4.6和2.5.1都试过了），APP打开后空白，控制台里只有这个提示，没有其他错误：
···
当前没有uni-app自带的原生tabbar 无须进行拦截  告辞!! at node_modules\uni-hold-tabbar\util\util.js:31
···

**Comment by SilurianYang** [comment]
app端把tabbar拦截关闭即可 看api

**Comment by xlkit456852** [comment]
好的 把tabbar拦截关闭即可 v3模式以后可以支持吗？
