### ISSUE TITLE
脚手架搭建的typescript版uniapp，引入uni-simple-router后报错。

### ISSUE THREAD

**Issue by zzqgithb** [SilurianYang/uni-simple-router#82]
![main](https://user-images.githubusercontent.com/24291786/74665089-ed58e300-51d9-11ea-9652-4495cb245b90.jpg)

![router](https://user-images.githubusercontent.com/24291786/74665104-f5188780-51d9-11ea-9b8c-c984155a8a6d.jpg)

![error2](https://user-images.githubusercontent.com/24291786/74665110-f944a500-51d9-11ea-9c9a-9ffe250057a3.jpg)

![error](https://user-images.githubusercontent.com/24291786/74665114-fb0e6880-51d9-11ea-9a5c-4d2128c8b9aa.jpg)

![version](https://user-images.githubusercontent.com/24291786/74665123-fd70c280-51d9-11ea-8aa5-0e15d7e8e844.jpg)

**Comment by SilurianYang** [comment]
看起来是路由插件没编译对端 检查下或者提出插件到项目目录下 非node_module下
