### ISSUE TITLE
pages.json里面把不需要验证（requiresAuth）的页面放在最前面 前置路由守卫就走不通

### ISSUE THREAD

**Issue by juventusforever** [SilurianYang/uni-simple-router#83]
[ZHXQ_MiniProgram1.zip](https://github.com/SilurianYang/uni-simple-router/files/4217149/ZHXQ_MiniProgram1.zip)

[register.txt](https://github.com/SilurianYang/uni-simple-router/files/4217174/register.txt)

**Describe the bug**

**To Reproduce**
[ZHXQ_MiniProgram1.zip](https://github.com/SilurianYang/uni-simple-router/files/4217134/ZHXQ_MiniProgram1.zip)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SilurianYang** [comment]
## 配置错误 参照 快速上手 第3步、配置main.js
