### ISSUE TITLE
只要引入咱们这个组件, nvue的页面就显示不出来。不管首屏是不是nvue 都显示不出来

### ISSUE THREAD

**Issue by DaDaDaBocai** [SilurianYang/uni-simple-router#84]
在2.5.1编译器版本下，只要引入咱们这个组件 nvue的页面就显示不出来。。。不管首屏是不是nvue 都显示不出来。
详见demo
[sailor-demo.zip](https://github.com/SilurianYang/uni-simple-router/files/4217408/sailor-demo.zip)

**Comment by SilurianYang** [comment]
## 已确认是bug 感谢反馈

**Comment by SilurianYang** [comment]
## 1.5.2 已修复
