### ISSUE TITLE
TypeError: undefined is not an object (evaluating '__uniConfig.appLaunchInfo.path')

### ISSUE THREAD

**Issue by boboidream** [SilurianYang/uni-simple-router#85]
**Describe the bug**
uni-simple-router：version 1.5.1
uni-app：使用 V3 编译器时，报错：`TypeError: undefined is not an object (evaluating '__uniConfig.appLaunchInfo.path')`

经查看 v3 编译版，__uniConfig 已经没有 appLaunchInfo 属性了。

**Comment by SilurianYang** [comment]
## npm 安装时已经有说明了  V3暂时不支持 请关闭v3即可
