### ISSUE TITLE
下载下来直接运行examples报错，是不是有东西没上传

### ISSUE THREAD

**Issue by CigoZim** [SilurianYang/uni-simple-router#88]
[广告] 13:25:42.131 开源不易，需要鼓励。去给 uni-app 项目 点个 star 吧 [不再提示]
[广告] 13:25:42.131 DCloud 新春招聘开启，欢迎前端、Android、C++/QT来投简历! 详情点击
13:25:42.138 项目 'examples' 开始编译...
13:25:43.208 请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。
13:25:43.218 正在编译中...
13:25:44.394  INFO  Starting development server...
13:26:02.086 文件查找失败：'./appRouter/hooks' at node_modules/uni-simple-router/index.js:8
13:26:02.086 文件查找失败：'./appRouter/uniNav' at node_modules/uni-simple-router/index.js:9
13:26:02.087 文件查找失败：'./appRouter/util' at node_modules/uni-simple-router/index.js:3
13:26:02.087 文件查找失败：'./helpers/mixins' at node_modules/uni-simple-router/index.js:13

**Comment by SilurianYang** [comment]
最简单 你 `npm install` 一下就OK拉
