### ISSUE TITLE
您好，H5端通过链接进去依然会发生不走守卫钩子

### ISSUE THREAD

**Issue by kenhy** [SilurianYang/uni-simple-router#9]
您好，H5端通过链接进去依然会发生不走守卫钩子，第一次输入回车地址栏后，进入页面不走守卫钩子，当再次回车地址栏或者刷新的时候，才会进入守卫钩子。

**Comment by SilurianYang** [comment]
很抱歉 此问题已解决。只是最近没发新包  这段时间太忙了，如果你急着想用则可以拉取1.1.3分支下的源代码 [详情请看这个](https://github.com/SilurianYang/uni-simple-router/issues/7)
