### ISSUE TITLE
vue cli 项目运行H5，访问首页报错Cannot read property 'path' of undefined at ruleToUniNavInfo (util.js:139)

### ISSUE THREAD

**Issue by rmengheng** [SilurianYang/uni-simple-router#90]
<img width="675" alt="q1" src="https://user-images.githubusercontent.com/9190221/75620674-a2ba6c00-5bc6-11ea-8bfe-4686b9731ede.png">

uni-simple-router  v1.5.2

demo:
[router-demo.ZIP](https://github.com/SilurianYang/uni-simple-router/files/4271428/router-demo.ZIP)

**Comment by SilurianYang** [comment]
这是 uni-app 运行时 没有对路由插件进行  `loader` 处理  你可以尝试把路由项目已到根目录 再引入！

**Comment by Ttyaa** [comment]
还是一样很无奈，想放弃了

**Comment by SilurianYang** [comment]
@Ttyaa  你看下有正确配置没？ 记得重新编译
![QQ截图20200504173241](https://user-images.githubusercontent.com/31280665/80953019-49242700-8e2d-11ea-9ea6-b5d45f0c9925.png)
