### ISSUE TITLE
安卓APP前置守卫 白屏

### ISSUE THREAD

**Issue by caoyanbin1993** [SilurianYang/uni-simple-router#91]
![image](https://user-images.githubusercontent.com/20960032/75740502-d28e7e80-5d42-11ea-9aab-d7d6cf6065b2.png)

1/安卓真机调试时，打开app，进入首页出现空白
2/若让跳转至登录页则可以正常跳转
3/怀疑：from和to的路径一致时，会出现bug?

**Comment by SilurianYang** [comment]
## `当前没有uni-app自带的原生tabbar无须进行拦截告辞！！` 为啥你就没有看到呢？

把配置设置为 因为你的项目没有底部tabbar 无须拦截

```js
   holdTabbar:false,	//是否开启底部菜单拦截
    rewriteFun:false, //是否对uni-app 下的chooseLocation/openLocation 两个方法重写 目的是隐藏和显示拦截tabbar
··
