### ISSUE TITLE
按照例子接入uni-simple-router 报错Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by itors** [SilurianYang/uni-simple-router#92]
util.js:139 Uncaught (in promise) TypeError: Cannot read property 'path' of undefined
    at ruleToUniNavInfo (util.js:139)
    at Router.appletsTransitionTo (hooks.js:144)

**Comment by SilurianYang** [comment]
这是 uni-app 运行时 没有对路由插件进行 `loader` 处理 你可以尝试 配置 `vue.config.js` 下 `transpileDependencies:['uni-simple-router'] ` 如果还不行就需要把路由项目移到根目录 再引入！ 让 `loader` 去处理它 [更多请查看这篇](https://github.com/SilurianYang/uni-simple-router/issues/90)
