### ISSUE TITLE
TypeError: Cannot read property '$set' of undefined

### ISSUE THREAD

**Issue by chunjiu** [SilurianYang/uni-simple-router#93]
![QQ截图20200304095548](https://user-images.githubusercontent.com/24645857/75836944-61140600-5dfe-11ea-988b-c9789d1a4afc.png)

**Comment by SilurianYang** [comment]
这个是路由插件抛出的错么？

**Comment by chunjiu** [comment]
> 这个是路由插件抛出的错么？

是没配置好
![18](https://user-images.githubusercontent.com/24645857/75840822-1b0f7000-5e07-11ea-8398-8f97db2f355b.png)
要配置白名单
