### ISSUE TITLE
h5模式会提示"export 'callwaitHooks' was not found in './hooks'

### ISSUE THREAD

**Issue by Vi-jay** [SilurianYang/uni-simple-router#94]
h5模式会提示`"export 'callwaitHooks' was not found in './hooks'` 并且无法使用this.$Router
小程序模式正常

**Comment by SilurianYang** [comment]
这个是 uni-app 的条件编码没起作用  [点我查看详细](https://ask.dcloud.net.cn/question/90068)

**Comment by Vi-jay** [comment]
好吧 那得切换老脚手架使用？

**Comment by SilurianYang** [comment]
> 好吧 那得切换老脚手架使用？

不用  你可以可以把npm安装的插件 `copy` 一份 到项目根目录下 然后引入就可以正常编译啦
![QQ截图20200305103555](https://user-images.githubusercontent.com/31280665/75942363-275e0080-5ecd-11ea-9ccf-7ae336b54ec1.png)
![QQ截图20200305103611](https://user-images.githubusercontent.com/31280665/75942373-2d53e180-5ecd-11ea-8aec-4f894eaf3ad5.png)

**Comment by Vi-jay** [comment]
好的，感谢您的帮助🤗

**Comment by SilurianYang** [comment]
## dcloud 官方没解决之前 可以先用上面两个方式占时解决

**Comment by MiWi-Lin** [comment]
> ## dcloud 官方没解决之前 可以先用上面两个方式占时解决

貌似看你源码'./hooks'中callwaitHooks并未export
