### ISSUE TITLE
H5无法获取微信重定向后地址带参

### ISSUE THREAD

**Issue by dlt116616059** [SilurianYang/uni-simple-router#95]
请问我使用H5微信授权登录，授权后微信重定向会带上code参数，在经过路由守卫后转发后code参数丢失，请问怎么获取这个参数呢？
![image](https://user-images.githubusercontent.com/13620382/76200025-dd0db400-622b-11ea-8ece-e5822a67d80e.png)

**Comment by SilurianYang** [comment]
默认的路由获取参数是编码传输的，在微信公众号上是非编码传输的格式  所有在重定向时会被格式化为空  你需要配置  `encodeURI:false` 即可
