### ISSUE TITLE
引入uni-aimple-router，真机调试白屏报错

### ISSUE THREAD

**Issue by annli-creator** [SilurianYang/uni-simple-router#96]
**Describe the bug**
1.项目没有nvue页面
2.引入uni-simple-router，不做任何操作，真机调试白屏报错

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50018026/76487518-a1f2c700-645d-11ea-9557-429e66b7e292.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by annli-creator** [comment]
![image](https://user-images.githubusercontent.com/50018026/76487615-e7af8f80-645d-11ea-8180-93aad59c6699.png)

**Comment by SilurianYang** [comment]
## 请上传一个可复现的demo

**Comment by annli-creator** [comment]
[my-project.zip](https://github.com/SilurianYang/uni-simple-router/files/4322530/my-project.zip)


这个demo就是简单的用cli生成一个un-app，然后引入uni-simple-router，真机或模拟器调试就会报错

**Comment by SilurianYang** [comment]
在你的 `APP` 选项下 配置 如下即可，以为你没有tabbar 所以需要关闭掉  
![QQ截图20200313124339](https://user-images.githubusercontent.com/31280665/76590560-71c42a80-6528-11ea-836f-5111de503894.png)

**Comment by annli-creator** [comment]
我这边配置之后还是报同样的错误，没有解决，你那边运行demo好着么？

**Comment by SilurianYang** [comment]
@annli-creator  已确认无问题才提交的

**Comment by modefyong** [comment]
请问楼主解决了吗？我遇到同样的问题了，需要配置什么吗？
