### ISSUE TITLE
微信小程序版路由跳转失效 H5正常

### ISSUE THREAD

**Issue by qq911512630** [SilurianYang/uni-simple-router#97]
官方案例中的tabbar-1.vue文件中的script
改成如下 
<script>
export default {
	mounted() {
		this.$Router.push({name:'router1'})
		console.log(this.$Router)
	}
}
</script>
并删除 beforeEach中的tabbar-1的拦截后可复现bug

**Comment by SilurianYang** [comment]
## uni-app 就使用官方提供的生命周期  `onload` `onshow`  `onReady`

**Comment by qq911512630** [comment]
> ## uni-app 就使用官方提供的生命周期 `onload` `onshow` `onReady`

onload依然无法跳转

**Comment by SilurianYang** [comment]
## 那请上传一个可复现的demo

**Comment by qq911512630** [comment]
> ## 那请上传一个可复现的demo
https://github.com/qq911512630/demo.git 可拉代码

**Comment by SilurianYang** [comment]
## 写的啥代码 我都不想说  明明都有文档  你还说 h5 正常？ 你看看你好多错误地方
![QQ截图20200313125356](https://user-images.githubusercontent.com/31280665/76590972-daf86d80-6529-11ea-9064-ffc55a6f1816.png)
![QQ截图20200313125443](https://user-images.githubusercontent.com/31280665/76590976-dd5ac780-6529-11ea-88d8-c84a55c6abb2.png)
