### ISSUE TITLE
h5页面按f5刷新后，url参数丢失

### ISSUE THREAD

**Issue by xlkit456852** [SilurianYang/uni-simple-router#98]
**Describe the bug**
h5页面按f5刷新后，url参数丢失

**To Reproduce**
启动项目
浏览器输入http://localhost:8080/#/pages/project/edit?type=add
按F5刷新页面，url会变成http://localhost:8080/#/pages/project/edit

**Expected behavior**
url参数不会丢失

发行平台: [h5]
操作系统 [win10]
HBuilderX版本 [2.6.1]
uni-app版本 [如使用Vue-cli创建/运行项目，则提供npm run info的运行结果]
uni-simple-router版本：1.5.1
设备信息 [谷歌浏览器]

**Comment by xlkit456852** [comment]
router初始化代码如下：
```
import modules from './modules'
import Vue from 'vue'
//这里仅示范npm安装方式的引入，其它方式引入请看最上面【安装】部分
import Router from 'uni-simple-router'

Vue.use(Router)
//初始化
const router = new Router({
	APP:{
		holdTabbar:false        //默认是true
	}, 
    routes: [...modules]//路由表
});

//全局路由前置守卫
router.beforeEach((to, from, next) => {
  next()
})
// 全局路由后置守卫
router.afterEach((to, from) => {
})
export default router;
```

**Comment by SilurianYang** [comment]
默认是编码传参 你这个是没有编码的 所以你需要配置下
```js
encodeURI:false
```

**Comment by xlkit456852** [comment]
谢谢~解决了
